{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'Caracteristicas': [{'Calle': 'SAN '
                                                                                                  'SIMON '
                                                                                                  'TOLNAHUAC',
                                                                                         'CodigoPostal': '01058',
                                                                                         'Colonia': '6920',
                                                                                         'FechaInicio': datetime.date(2014, 1, 1),
                                                                                         'FechaTermino': datetime.date(2015, 1, 1),
                                                                                         'FolioReal': 'BG544-FRR-456B-FRR',
                                                                                         'NumeroExterior': 'VIOLANTE',
                                                                                         'NumeroInterior': '45',
                                                                                         'TipoInmueble': Code('3', 'Edificio habitacional'),
                                                                                         'ValorReferencia': '356825.12'}],
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 1),
                                                                                          'FormaPago': Code('4', 'Préstamo o crédito'),
                                                                                          'InstrumentoMonetario': Code('4', 'Tarjeta de Prepago'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '757897.55'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 1),
                                                                    'TipoOperacion': Code('1501', 'Arrendamiento de inmueble')}]},
                         'PersonaAviso': [{'TipoDomicilio': {'Extranjero': {'Calle': 'TOGA '
                                                                                     'TOGA',
                                                                            'CiudadPoblacion': 'TOGUIS',
                                                                            'CodigoPostal': '12448',
                                                                            'Colonia': 'NA',
                                                                            'EstadoProvincia': 'TOGUILLITA',
                                                                            'NumeroExterior': '45',
                                                                            'Pais': Code('TG', 'TOGO')}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('3130100', 'CONSTRUCCION - DECORADORES DE INTERIORES'),
                                                                             'ApellidoMaterno': 'JUAREZ',
                                                                             'ApellidoPaterno': 'ALMONTE',
                                                                             'FechaNacimiento': datetime.date(1956, 8, 16),
                                                                             'Nombre': 'NEPOMUCENO',
                                                                             'PaisNacionalidad': Code('TG', 'TOGO')}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF15454FG454'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('ARI', 'La constitución de derechos personales de uso o goce de bienes inmuebles'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}