{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Conceptos': [{'Cantidad': Decimal('10'),
                'ClaveProdServ': Code('54101500', 'Joyería fina'),
                'ClaveUnidad': Code('APZ', 'Onza troy u onza farmacéutica'),
                'ComplementoConcepto': {'instEducativas': {'AutRVOE': '1234',
                                                           'CURP': 'JUAN010101MAZBCÑ90',
                                                           'NivelEducativo': 'Preescolar',
                                                           'NombreAlumno': 'Juanito '
                                                                           'Pérez '
                                                                           'Niño',
                                                           'RfcPago': 'ABC010101AAA',
                                                           'Version': '1.0'}},
                'Descripcion': 'Lapiz Berol del No. 2',
                'Importe': Decimal('1234.50'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('123.45')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}