{'Certificado': '',
 'Complemento': {'CartaPorte': {'Mercancias': {'Mercancia': [{'BienesTransp': Code('60141405', 'Kits o materiales para juegos de simulación'),
                                                              'Cantidad': Decimal('1.000001'),
                                                              'ClaveUnidad': Code('ZZ', 'Mutuamente definido'),
                                                              'Descripcion': 'Descripcion',
                                                              'PesoEnKg': Decimal('1.123')}],
                                               'NumTotalMercancias': 1,
                                               'PesoBrutoTotal': Decimal('100.123'),
                                               'UnidadPeso': Code('SM3', 'Metro cúbico estándar')},
                                'TranspInternac': 'Sí',
                                'Ubicaciones': [{'Domicilio': {'Calle': 'Hola',
                                                               'CodigoPostal': '11850',
                                                               'Estado': 'Mexico '
                                                                         'City',
                                                               'Pais': Code('MEX', 'México')},
                                                 'FechaHoraSalidaLlegada': datetime.datetime(2021, 11, 1, 1, 23, 59),
                                                 'RFCRemitenteDestinatario': 'AAA010101AAA',
                                                 'TipoUbicacion': 'Origen'},
                                                {'Domicilio': {'Calle': 'Hola',
                                                               'CodigoPostal': '123456',
                                                               'Estado': 'Estado',
                                                               'Pais': Code('ZZZ', 'Países no declarados')},
                                                 'FechaHoraSalidaLlegada': datetime.datetime(2021, 11, 1, 1, 23, 59),
                                                 'RFCRemitenteDestinatario': 'BASJ600902KL9',
                                                 'TipoUbicacion': 'Destino'}],
                                'Version': '2.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}