{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'GastosHidrocarburos': {'AreaContractual': 'abcdefg',
                                         'Erogacion': [{'Actividades': [{'ActividadRelacionada': Code('05', 'Abandono'),
                                                                         'SubActividades': [{'SubActividadRelacionada': Code('039', 'Seguridad, Salud y Medio Ambiente'),
                                                                                             'Tareas': [{'TareaRelacionada': Code('0155', 'Auditoría de seguridad')}]}]}],
                                                        'CentroCostos': [{'Campo': 'Campo',
                                                                          'Yacimientos': [{'Pozos': [{'Pozo': 'Pozo'}],
                                                                                           'Yacimiento': 'Yacimiento'}]}],
                                                        'DocumentoRelacionado': [{'ClavePagoPedimentoVinculado': Code('22', 'GARANTÍA EN IVA E IEPS'),
                                                                                  'ClavePedimentoVinculado': Code('CT', 'PEDIMENTO COMPLEMENTARIO'),
                                                                                  'FechaFolioFiscalVinculado': datetime.date(2018, 10, 22),
                                                                                  'FolioFiscalVinculado': 'C892EBD7-83DA-4233-98A4-3e44db9e85a4',
                                                                                  'Mes': Code('10', 'Octubre'),
                                                                                  'MontoIVAPedimento': Decimal('90.000001'),
                                                                                  'MontoRetencionISR': Decimal('123'),
                                                                                  'MontoRetencionIVA': Decimal('0.123'),
                                                                                  'MontoRetencionOtrosImpuestos': Decimal('9.001'),
                                                                                  'MontoTotalErogaciones': Decimal('0.123'),
                                                                                  'MontoTotalIVA': Decimal('99.001'),
                                                                                  'NumeroPedimentoVinculado': '12  '
                                                                                                              '34  '
                                                                                                              '5678  '
                                                                                                              '1234567',
                                                                                  'OrigenErogacion': 'Extranjero',
                                                                                  'OtrosImpuestosPagadosPedimento': Decimal('1.0'),
                                                                                  'RFCProveedor': 'AAA010101AAA'}],
                                                        'MontocuErogacion': Decimal('100.999'),
                                                        'Porcentaje': Decimal('99.999'),
                                                        'TipoErogacion': 'Inversión'},
                                                       {'DocumentoRelacionado': [{'ClavePagoPedimentoVinculado': Code('22', 'GARANTÍA EN IVA E IEPS'),
                                                                                  'ClavePedimentoVinculado': Code('CT', 'PEDIMENTO COMPLEMENTARIO'),
                                                                                  'FechaFolioFiscalVinculado': datetime.date(2018, 10, 22),
                                                                                  'FolioFiscalVinculado': 'a83a8330-1511-4b1b-959a-5771D8861206',
                                                                                  'Mes': Code('10', 'Octubre'),
                                                                                  'MontoIVAPedimento': Decimal('90.000001'),
                                                                                  'MontoRetencionISR': Decimal('123'),
                                                                                  'MontoRetencionIVA': Decimal('0.001'),
                                                                                  'MontoRetencionOtrosImpuestos': Decimal('9.001'),
                                                                                  'MontoTotalErogaciones': Decimal('0.001'),
                                                                                  'MontoTotalIVA': Decimal('99.001'),
                                                                                  'NumeroPedimentoVinculado': '12  '
                                                                                                              '34  '
                                                                                                              '5678  '
                                                                                                              '1234890',
                                                                                  'OrigenErogacion': 'Nacional',
                                                                                  'OtrosImpuestosPagadosPedimento': Decimal('1.0'),
                                                                                  'RFCProveedor': 'AAA010101AAA'}],
                                                        'MontocuErogacion': Decimal('1001.999'),
                                                        'Porcentaje': Decimal('0.001'),
                                                        'TipoErogacion': 'Inversión'}],
                                         'NumeroContrato': '12345678',
                                         'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}