{'Certificado': '',
 'Complemento': {'Pagos': {'Pago': [{'DoctoRelacionado': [{'IdDocumento': 'C1DF8D01-8436-4E7D-BECF-20F31624280D',
                                                           'ImpPagado': Decimal('1.00'),
                                                           'ImpSaldoAnt': Decimal('6066.66'),
                                                           'ImpSaldoInsoluto': Decimal('0'),
                                                           'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                           'NumParcialidad': 2,
                                                           'ObjetoImpDR': Code('01', 'No objeto de impuesto')}],
                                     'FechaPago': datetime.datetime(2021, 12, 3, 12, 37, 13),
                                     'FormaDePagoP': Code('03', 'Transferencia electrónica de fondos'),
                                     'MonedaP': Code('MXN', 'Peso Mexicano'),
                                     'Monto': Decimal('6066.66')}],
                           'Totales': {'MontoTotalPagos': Decimal('15166.65')},
                           'Version': '2.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Pago',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}