{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['ED1752FE-E865-4FF2-BFE1-0F552E770DC9'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'CuentaPredial': ['51888'],
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2250000'),
                                                                    'Importe': Decimal('247500'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2250000'),
                                                                  'Importe': Decimal('360000'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00001',
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500000')},
               {'ACuentaTerceros': {'DomicilioFiscalACuentaTerceros': '99999',
                                    'NombreACuentaTerceros': 'NombreACuentaTerceros',
                                    'RegimenFiscalACuentaTerceros': Code('630', 'Enajenación de acciones en bolsa de valores'),
                                    'RfcACuentaTerceros': 'AAA010101AAA'},
                'Cantidad': Decimal('1.6'),
                'ClaveProdServ': Code('95141904', 'Unidades quirúrgicas'),
                'ClaveUnidad': Code('WEE', 'Semana'),
                'Descripcion': 'ALUMINIO',
                'Importe': Decimal('2400'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2400'),
                                                                    'Importe': Decimal('264'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2400'),
                                                                  'Importe': Decimal('384'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'InformacionAduanera': ['15  48  4567  6001234'],
                'NoIdentificacion': '00002',
                'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500')},
               {'Cantidad': Decimal('1.7'),
                'ClaveProdServ': Code('84101604', 'Ayuda gubernamental'),
                'ClaveUnidad': Code('G66', 'Litro por hora kelvin'),
                'Descripcion': 'ZAMAC',
                'Descuento': Decimal('0'),
                'Importe': Decimal('17000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('17000'),
                                                                    'Importe': Decimal('1870'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('17000'),
                                                                  'Importe': Decimal('2720'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00003',
                'ObjetoImp': Code('03', 'Sí objeto del impuesto y no obligado al desglose'),
                'Parte': [{'Cantidad': Decimal('1.0'),
                           'ClaveProdServ': Code('25201513', 'Cúpulas protectoras de la antena de avión'),
                           'Descripcion': 'PARTE EJEMPLO',
                           'Importe': Decimal('1.00'),
                           'InformacionAduanera': ['15  48  4567  6001235'],
                           'NoIdentificacion': '055155',
                           'Unidad': 'UNIDAD',
                           'ValorUnitario': Decimal('1.00')}],
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('10000')}],
 'CondicionesDePago': 'CONDICIONES',
 'Confirmacion': 'A1234',
 'Descuento': Decimal('0.00'),
 'Emisor': {'FacAtrAdquirente': '0123456789',
            'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('630', 'Enajenación de acciones en bolsa de valores'),
            'Rfc': 'AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 7, 23, 59, 59),
 'Folio': '123ABC',
 'FormaPago': Code('99', 'Por definir'),
 'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('247000'),
                                       'Impuesto': Code('001', 'ISR')},
                               '003': {'Importe': Decimal('500'),
                                       'Impuesto': Code('003', 'IEPS')}},
               'TotalImpuestosRetenidos': Decimal('247500'),
               'TotalImpuestosTrasladados': Decimal('360000'),
               'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('1.00'),
                                                   'Importe': Decimal('360000'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('1.600000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'InformacionGlobal': {'Año': 2021,
                       'Meses': Code('18', 'Noviembre-Diciembre'),
                       'Periodicidad': Code('05', 'Bimestral')},
 'LugarExpedicion': Code('99999', None),
 'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'NumRegIdTrib': '0000000000000',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'ResidenciaFiscal': Code('MEX', 'México'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('S01', 'Sin efectos fiscales')},
 'Sello': '',
 'Serie': 'A',
 'SubTotal': Decimal('1000'),
 'TipoCambio': Decimal('1.0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('1500'),
 'Version': '4.0'}