{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'detallista': {'AdditionalInformation': [{'Type': 'ATZ',
                                                           '_text': None}],
                                'Buyer': {'ContactInformation': {'PersonOrDepartmentName': {'Text': '000'}},
                                          'Gln': '0000000000000'},
                                'ContentVersion': '1.3.1',
                                'Currency': [{'CurrencyFunction': ['BILLING_CURRENCY'],
                                              'CurrencyISOCode': 'MXN'},
                                             {'CurrencyFunction': ['PAYMENT_CURRENCY'],
                                              'CurrencyISOCode': 'USD',
                                              'RateOfChange': Decimal('1.000000')}],
                                'DocumentStatus': 'ORIGINAL',
                                'DocumentStructureVersion': 'AMC8.1',
                                'OrderIdentification': {'ReferenceIdentification': [{'Type': 'ON',
                                                                                     '_text': '\n'
                                                                                              '        '
                                                                                              '4500536101'}]},
                                'RequestForPaymentIdentification': {'EntityType': 'INVOICE'},
                                'SpecialInstruction': [{'Code': 'ZZZ',
                                                        'Text': ['Monto de la '
                                                                 'venta']}],
                                'Type': 'SimpleInvoiceType'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}