{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'ComercioExterior': {'CertificadoOrigen': 1,
                                      'ClaveDePedimento': Code('A1', 'IMPORTACION O EXPORTACION DEFINITIVA'),
                                      'Destinatario': [{'Domicilio': [{'Calle': 'c3',
                                                                       'CodigoPostal': '01020',
                                                                       'Colonia': '0003',
                                                                       'Estado': 'BCN',
                                                                       'Localidad': '02',
                                                                       'Municipio': '003',
                                                                       'NumeroExterior': '3A',
                                                                       'NumeroInterior': '101',
                                                                       'Pais': Code('ZZZ', 'Países no declarados'),
                                                                       'Referencia': 'rd'}],
                                                        'Nombre': 'Nombre',
                                                        'NumRegIdTrib': '654321'}],
                                      'Emisor': {'Curp': 'PEPJ800101HDFBCDQ8',
                                                 'Domicilio': {'Calle': 'c',
                                                               'CodigoPostal': '99998',
                                                               'Colonia': Code('0001', None),
                                                               'Estado': Code('AGU', 'Aguascalientes'),
                                                               'Localidad': Code('69', None),
                                                               'Municipio': Code('001', 'Aguascalientes'),
                                                               'NumeroExterior': '123X',
                                                               'NumeroInterior': '12A',
                                                               'Pais': Code('ZZZ', 'Países no declarados'),
                                                               'Referencia': 'r'}},
                                      'Incoterm': Code('FOB', 'FRANCO A BORDO (PUERTO DE CARGA CONVENIDO)'),
                                      'Mercancias': [{'CantidadAduana': Decimal('0.001'),
                                                      'DescripcionesEspecificas': [{'Marca': 'Marca',
                                                                                    'Modelo': 'Modelo',
                                                                                    'NumeroSerie': 'NumeroSerie',
                                                                                    'SubModelo': 'SubModelo'}],
                                                      'FraccionArancelaria': Code('99999999', 'Códigos arancelarios no catalogados en la tarifa'),
                                                      'NoIdentificacion': 'n100',
                                                      'UnidadAduana': Code('99', 'SERVICIO'),
                                                      'ValorDolares': Decimal('123.45'),
                                                      'ValorUnitarioAduana': Decimal('234.56')},
                                                     {'CantidadAduana': Decimal('0.001'),
                                                      'DescripcionesEspecificas': [{'Marca': 'Marca',
                                                                                    'Modelo': 'Modelo',
                                                                                    'NumeroSerie': 'NumeroSerie',
                                                                                    'SubModelo': 'SubModelo'}],
                                                      'FraccionArancelaria': Code('99999999', 'Códigos arancelarios no catalogados en la tarifa'),
                                                      'NoIdentificacion': 'n101',
                                                      'UnidadAduana': Code('99', 'SERVICIO'),
                                                      'ValorDolares': Decimal('123.45'),
                                                      'ValorUnitarioAduana': Decimal('234.56')}],
                                      'MotivoTraslado': Code('99', 'Otros'),
                                      'NumCertificadoOrigen': 'DEADBEEF-CAFE-BABE-1234-DECADE012345',
                                      'NumeroExportadorConfiable': '1',
                                      'Observaciones': 'obs',
                                      'Propietario': [{'NumRegIdTrib': '1234567',
                                                       'ResidenciaFiscal': Code('ZZZ', 'Países no declarados')}],
                                      'Receptor': {'Domicilio': {'Calle': 'c',
                                                                 'CodigoPostal': '01010',
                                                                 'Colonia': '0002',
                                                                 'Estado': 'ZZZ',
                                                                 'Localidad': '01',
                                                                 'Municipio': '002',
                                                                 'NumeroExterior': '2',
                                                                 'NumeroInterior': '99',
                                                                 'Pais': Code('ZZZ', 'Países no declarados'),
                                                                 'Referencia': 'r1'},
                                                   'NumRegIdTrib': '234567890'},
                                      'Subdivision': 1,
                                      'TipoCambioUSD': Decimal('234.5678'),
                                      'TipoOperacion': Code('2', 'Exportación'),
                                      'TotalUSD': Decimal('123.45'),
                                      'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}