{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'certificadodedestruccion': {'InformacionAduanera': {'Aduana': 'Aduana',
                                                                      'Fecha': datetime.date(2015, 5, 31),
                                                                      'NumPedImp': '1234A'},
                                              'NumFolDesVeh': '123ABC',
                                              'Serie': Code('SERIE E', 'Para vehículos usados propiedad de personas físicas que no sometieron a las formalidades aduaneras vehículos usados de precedencia extranjera para importación definitiva '),
                                              'VehiculoDestruido': {'Año': 1999,
                                                                    'Marca': 'Marca',
                                                                    'Modelo': 'Modelo',
                                                                    'NIV': 'NIV',
                                                                    'NumFolTarjCir': '3456',
                                                                    'NumMotor': '7890123',
                                                                    'NumPlacas': '456789',
                                                                    'NumSerie': '23456',
                                                                    'TipooClase': 'TipooClase'},
                                              'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}