{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'detallista': {'AdditionalInformation': [{'Type': 'IV',
                                                           '_text': 'A'},
                                                          {'Type': 'ATZ',
                                                           '_text': '27534'}],
                                'AllowanceCharge': [{'AllowanceChargeType': 'ALLOWANCE_GLOBAL',
                                                     'MonetaryAmountOrPercentage': {'Rate': {'Base': 'INVOICE_VALUE',
                                                                                             'Percentage': Decimal('3.00')}},
                                                     'SettlementType': 'BILL_BACK',
                                                     'SpecialServicesType': 'AJ'}],
                                'Buyer': {'ContactInformation': {'PersonOrDepartmentName': {'Text': '0390   '}},
                                          'Gln': '7504000107903'},
                                'ContentVersion': '1.3.1',
                                'DeliveryNote': {'ReferenceDate': datetime.date(2017, 5, 1),
                                                 'ReferenceIdentification': ['97276954']},
                                'DocumentStatus': 'ORIGINAL',
                                'DocumentStructureVersion': 'AMC8.1',
                                'LineItem': [{'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '00636398'}],
                                              'GrossPrice': {'Amount': Decimal('40.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('10.00')},
                                              'NetPrice': {'Amount': Decimal('34.32')},
                                              'Number': 1,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('400.00')},
                                                                  'NetAmount': {'Amount': Decimal('343.17')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'cacahuate '
                                                                                              'acaramelado'},
                                              'TradeItemIdentification': {'Gtin': '00636398'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '636428'}],
                                              'GrossPrice': {'Amount': Decimal('43.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('36.89')},
                                              'Number': 2,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('215.00')},
                                                                  'NetAmount': {'Amount': Decimal('184.46')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'cacahuate '
                                                                                              'salado'},
                                              'TradeItemIdentification': {'Gtin': '636428'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '636452'}],
                                              'GrossPrice': {'Amount': Decimal('43.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('36.89')},
                                              'Number': 3,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('215.00')},
                                                                  'NetAmount': {'Amount': Decimal('184.46')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'cacahuate '
                                                                                              'enchilado'},
                                              'TradeItemIdentification': {'Gtin': '636452'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '636517'}],
                                              'GrossPrice': {'Amount': Decimal('50.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('42.89')},
                                              'Number': 4,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('250.00')},
                                                                  'NetAmount': {'Amount': Decimal('214.48')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'cacahuate '
                                                                                              'japones'},
                                              'TradeItemIdentification': {'Gtin': '636517'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '636711'}],
                                              'GrossPrice': {'Amount': Decimal('170.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('145.85')},
                                              'Number': 5,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('850.00')},
                                                                  'NetAmount': {'Amount': Decimal('729.23')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'pistaches'},
                                              'TradeItemIdentification': {'Gtin': '636711'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '13656878'}],
                                              'GrossPrice': {'Amount': Decimal('51.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('10.00')},
                                              'NetPrice': {'Amount': Decimal('43.76')},
                                              'Number': 6,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('510.00')},
                                                                  'NetAmount': {'Amount': Decimal('437.54')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'botana '
                                                                                              'surtida'},
                                              'TradeItemIdentification': {'Gtin': '13656878'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '15209968'}],
                                              'GrossPrice': {'Amount': Decimal('48.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('41.18')},
                                              'Number': 7,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('240.00')},
                                                                  'NetAmount': {'Amount': Decimal('205.90')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'botana '
                                                                                              'turca'},
                                              'TradeItemIdentification': {'Gtin': '15209968'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '15664231'}],
                                              'GrossPrice': {'Amount': Decimal('110.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('94.37')},
                                              'Number': 8,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('550.00')},
                                                                  'NetAmount': {'Amount': Decimal('471.86')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'botana '
                                                                                              'california '
                                                                                              'mix'},
                                              'TradeItemIdentification': {'Gtin': '15664231'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '15843942'}],
                                              'GrossPrice': {'Amount': Decimal('45.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('38.61')},
                                              'Number': 9,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('225.00')},
                                                                  'NetAmount': {'Amount': Decimal('193.03')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'chili '
                                                                                              'nuts'},
                                              'TradeItemIdentification': {'Gtin': '15843942'},
                                              'Type': 'SimpleInvoiceLineItemType'},
                                             {'AlternateTradeItemIdentification': [{'Type': 'SUPPLIER_ASSIGNED',
                                                                                    '_text': '37715123'}],
                                              'GrossPrice': {'Amount': Decimal('100.00')},
                                              'InvoicedQuantity': {'UnitOfMeasure': 'PCE',
                                                                   '_text': Decimal('5.00')},
                                              'NetPrice': {'Amount': Decimal('85.79')},
                                              'Number': 10,
                                              'TotalLineAmount': {'GrossAmount': {'Amount': Decimal('500.00')},
                                                                  'NetAmount': {'Amount': Decimal('428.93')}},
                                              'TradeItemDescriptionInformation': {'Language': 'ES',
                                                                                  'LongText': 'botana '
                                                                                              'hot '
                                                                                              'hawaiian'},
                                              'TradeItemIdentification': {'Gtin': '37715123'},
                                              'Type': 'SimpleInvoiceLineItemType'}],
                                'OrderIdentification': {'ReferenceDate': datetime.date(2017, 4, 30),
                                                        'ReferenceIdentification': [{'Type': 'ON',
                                                                                     '_text': '15749759'}]},
                                'RequestForPaymentIdentification': {'EntityType': 'INVOICE'},
                                'Seller': {'AlternatePartyIdentification': {'Type': 'SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY',
                                                                            '_text': '109'},
                                           'Gln': '7504000107903'},
                                'SpecialInstruction': [{'Code': 'ZZZ',
                                                        'Text': ['TRES MIL '
                                                                 'TRESCIENTOS '
                                                                 'NOVENTA Y '
                                                                 'TRES PESOS '
                                                                 '04/100 '
                                                                 'M.N.']}],
                                'TotalAllowanceCharge': [{'AllowanceOrChargeType': 'ALLOWANCE',
                                                          'Amount': Decimal('561.96'),
                                                          'SpecialServicesType': 'AJ'}],
                                'TotalAmount': {'Amount': Decimal('3955.00')},
                                'Type': 'SimpleInvoiceType'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}