{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'EstadoDeCuentaCombustible': {'Conceptos': [{'Cantidad': Decimal('100.001'),
                                                              'ClaveEstacion': '1234567890',
                                                              'Fecha': datetime.datetime(2017, 5, 30, 23, 59, 59),
                                                              'FolioOperacion': '567',
                                                              'Identificador': 'IDstring',
                                                              'Importe': Decimal('12345.12'),
                                                              'NombreCombustible': 'Gasolina',
                                                              'Rfc': 'AAA010101AAA',
                                                              'TipoCombustible': Code('2', 'Gasolina mayor o igual a 92 octanos'),
                                                              'Traslados': [{'Importe': Decimal('12.34'),
                                                                             'Impuesto': 'IVA',
                                                                             'TasaOCuota': Decimal('10.500001')},
                                                                            {'Importe': Decimal('13.45'),
                                                                             'Impuesto': 'IEPS',
                                                                             'TasaOCuota': Decimal('11.00')}],
                                                              'Unidad': '01',
                                                              'ValorUnitario': Decimal('123.45')}],
                                               'NumeroDeCuenta': '1234',
                                               'SubTotal': Decimal('5678.90'),
                                               'TipoOperacion': 'Tarjeta',
                                               'Total': Decimal('5678.90'),
                                               'Version': '1.2'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}