{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'ConsumoDeCombustibles': {'Conceptos': [{'Cantidad': Decimal('12.999'),
                                                          'ClaveEstacion': 'AB12345678',
                                                          'Determinados': [{'Importe': Decimal('88.99'),
                                                                            'Impuesto': 'IVA',
                                                                            'TasaOCuota': Decimal('15.5')},
                                                                           {'Importe': Decimal('10'),
                                                                            'Impuesto': 'IEPS',
                                                                            'TasaOCuota': Decimal('10.0')}],
                                                          'Fecha': datetime.datetime(2018, 5, 1, 12, 59, 59),
                                                          'FolioOperacion': 'A',
                                                          'Identificador': 'Foo',
                                                          'Importe': Decimal('0.8'),
                                                          'NombreCombustible': 'Bar',
                                                          'Rfc': 'BASJ600902KL9',
                                                          'TipoCombustible': Code('1', 'Gasolina menor a 92 octanos'),
                                                          'ValorUnitario': Decimal('12.7')}],
                                           'NumeroDeCuenta': '123',
                                           'SubTotal': Decimal('100.00'),
                                           'TipoOperacion': 'monedero '
                                                            'electrónico',
                                           'Total': Decimal('100.00'),
                                           'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}