{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Conceptos': [{'Cantidad': Decimal('1.00'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'ComplementoConcepto': {'VentaVehiculos': {'ClaveVehicular': '0599999',
                                                           'InformacionAduanera': [{'Aduana': 'VERACRUZ',
                                                                                    'Fecha': datetime.date(2014, 1, 3),
                                                                                    'Numero': '98699876543999'}],
                                                           'Niv': '0588888',
                                                           'Version': '1.1'}},
                'Descripcion': 'CTX199 - JETTA TREND',
                'Importe': Decimal('196000.00'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('196000.00')},
               {'Cantidad': Decimal('1.00'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'CTX199 - ACCESSORIOS AUTOMOVIL',
                'Importe': Decimal('11000.00'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('11000.00')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}