{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'renovacionysustitucionvehiculos': {'DecretoSustitVehicular': {'VehEnaj': Code('01', 'Nuevo'),
                                                                                'VehiculoNuvoSemEnajenadoFabAlPerm': {'Año': 1990,
                                                                                                                      'Modelo': 'Modelo',
                                                                                                                      'NumPlacas': '987654',
                                                                                                                      'RFC': 'PEPJ8001019Q8'},
                                                                                'VehiculoUsadoEnajenadoPermAlFab': {'Aduana': 'Aduana',
                                                                                                                    'Año': 2001,
                                                                                                                    'FechaRegulVeh': datetime.date(1999, 12, 31),
                                                                                                                    'Foliofiscal': '123A',
                                                                                                                    'Marca': 'Marca',
                                                                                                                    'Modelo': 'Modelo',
                                                                                                                    'NIV': 'NIV',
                                                                                                                    'NumFolAvisoint': 'ISO12345',
                                                                                                                    'NumFolTarjCir': '3456',
                                                                                                                    'NumMotor': '7890123',
                                                                                                                    'NumPedIm': '56789',
                                                                                                                    'NumPlacas': '456789',
                                                                                                                    'NumSerie': '987654321',
                                                                                                                    'PrecioVehUsado': Decimal('10001.56'),
                                                                                                                    'TipoVeh': Code('06', 'Vehículos destinados al transporte de personas de 15 pasajeros o más, con una antigüedad de más de 8 años'),
                                                                                                                    'TipooClase': 'TipooClase'}},
                                                     'TipoDeDecreto': Code('02', 'Decreto por el que se otorgan medidas para la sustitución de vehículos de autotransporte de pasaje y carga'),
                                                     'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}