{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'VehiculoUsado': {'ClaveVehicular': 'ABC1',
                                   'InformacionAduanera': [{'Aduana': 'oficina '
                                                                      'central',
                                                            'Fecha': datetime.date(2014, 10, 23),
                                                            'Numero': '1'},
                                                           {'Aduana': 'Otra '
                                                                      'oficina',
                                                            'Fecha': datetime.date(2014, 10, 24),
                                                            'Numero': '2'}],
                                   'Marca': 'Foo',
                                   'Modelo': '0999',
                                   'MontoAdquisicion': Decimal('1000.47'),
                                   'MontoEnajenacion': Decimal('99.91'),
                                   'NIV': '0',
                                   'NumeroMotor': 'ABCDEF123',
                                   'NumeroSerie': '12345678901234567',
                                   'Tipo': 'type',
                                   'Valor': Decimal('123.123456'),
                                   'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': Code('99999', None),
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}