{'Certificado': 'MIIF+TCCA+GgAwIBAgIUMzAwMDEwMDAwMDAzMDAwMjM3MDgwDQYJKoZIhvcNAQELBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNzA1MTgwMzU0NTZaFw0yMTA1MTgwMzU0NTZaMIHlMSkwJwYDVQQDEyBBQ0NFTSBTRVJWSUNJT1MgRU1QUkVTQVJJQUxFUyBTQzEpMCcGA1UEKRMgQUNDRU0gU0VSVklDSU9TIEVNUFJFU0FSSUFMRVMgU0MxKTAnBgNVBAoTIEFDQ0VNIFNFUlZJQ0lPUyBFTVBSRVNBUklBTEVTIFNDMSUwIwYDVQQtExxBQUEwMTAxMDFBQUEgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxGzAZBgNVBAsUEkNTRDAxX0FBQTAxMDEwMUFBQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJdUcsHIEIgwivvAantGnYVIO3+7yTdD1tkKopbL+tKSjRFo1ErPdGJxP3gxT5O+ACIDQXN+HS9uMWDYnaURalSIF9COFCdh/OH2Pn+UmkN4culr2DanKztVIO8idXM6c9aHn5hOo7hDxXMC3uOuGV3FS4ObkxTV+9NsvOAV2lMe27SHrSB0DhuLurUbZwXm+/r4dtz3b2uLgBc+Diy95PG+MIu7oNKM89aBNGcjTJw+9k+WzJiPd3ZpQgIedYBD+8QWxlYCgxhnta3k9ylgXKYXCYk0k0qauvBJ1jSRVf5BjjIUbOstaQp59nkgHh45c9gnwJRV618NW0fMeDzuKR0CAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBABKj0DCNL1lh44y+OcWFrT2icnKF7WySOVihx0oR+HPrWKBMXxo9KtrodnB1tgIx8f+Xjqyphhbw+juDSeDrb99PhC4+E6JeXOkdQcJt50Kyodl9URpCVWNWjUb3F/ypa8oTcff/eMftQZT7MQ1Lqht+xm3QhVoxTIASce0jjsnBTGD2JQ4uT3oCem8bmoMXV/fk9aJ3v0+ZIL42MpY4POGUa/iTaawklKRAL1Xj9IdIR06RK68RS6xrGk6jwbDTEKxJpmZ3SPLtlsmPUTO1kraTPIo9FCmU/zZkWGpd8ZEAAFw+ZfI+bdXBfvdDwaM2iMGTQZTTEgU5KKTIvkAnHo9O45SqSJwqV9NLfPAxCo5eRR2OGibd9jhHe81zUsp5GdE1mZiSqJU82H3cu6BiE+D3YbZeZnjrNSxBgKTIf8w+KNYPM4aWnuUMl0mLgtOxTUXi9MKnUccq3GZLA7bx7Zn211yPRqEjSAqybUMVIOho6aqzkfc3WLZ6LnGU+hyHuZUfPwbnClb7oFFz1PlvGOpNDsUb0qP42QCGBiTUseGugAzqOP6EYpVPC73gFourmdBQgfayaEvi3xjNanFkPlW1XEYNrYJB4yNjphFrvWwTY86vL2o8gZN0Utmc5fnoBTfM9r2zVKmEi6FUeJ1iaDaVNv47te9iS1ai4V4vBY8r',
 'CfdiRelacionados': [{'CfdiRelacionado': ['ED1752FE-E865-4FF2-BFE1-0F552E770DC9'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2021, 12, 19, 21, 19, 11),
                                         'NoCertificadoSAT': '30001000000300023699',
                                         'RfcProvCertif': 'PUT211201AX4',
                                         'SelloCFD': 'Gnm1yXaIig5hr1dJ+88gjLY5usQxXP2s+zdmlLl4iokWENaUUlhpG/crkUFEzcJfdq1FbBxV/d/GN50MGuw2fP5f6MkRYz75UKaKfzubUak+SCkDzYot5jZRkO6hXKe4+KAfaulP7wa8Q7oSW5ccivppLnikme0CS3KtGBrQHU/q3pjNrw+jMvsnpUc1tx91REqMWrzMTZ2D6UkGdqn8i/0mLRU2vT8vPaNg/Hr2jpVVAgQmPtfvnfnORCWSm/5qZg9Tli7nTRRVwupF4o9ajH2/Is7LoCsIgZUg3wCHkZCjaKk2mJoK7FyMTsPXRRSGhoYgwi1kNHs1aY4RHNwe5w==',
                                         'SelloSAT': 'HMfYv7KqRFwXB2mNCZSpVMKu2lPWALFP90zLahg0X85/c9U74SEJ7Y98v2ALvEyl4r9LrGsgJv8z3vDx4w/xET57kvJNtfDEOb4/qeKclXDUAdSOIXnJ6h5F6RyTAgsyrmOf1A0Ez3aGihfX1zdKpfICchWUyOA0L88/WUOSBLI31nT35ZckDXfIvy7YfPZDPnoy5VVyFjeL1os7lvQ0L4H+MetiEf7eyx9vggYnisTfuv1izfRPAnvkdyOcgrJ/wkqvGx0u+BIMFvSrqHskBl/D4gMj0M+3PDxce1FGmzkz29iPql5mNJas3xpHx6z0eTPvLBlbq+9E0fI0ao+IPA==',
                                         'UUID': '499e9a70-36ac-448a-bbd9-f3f52102e4be',
                                         'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'CuentaPredial': ['51888'],
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2250000'),
                                                                    'Importe': Decimal('247500'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2250000'),
                                                                  'Importe': Decimal('360000'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00001',
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500000')},
               {'ACuentaTerceros': {'DomicilioFiscalACuentaTerceros': '99999',
                                    'NombreACuentaTerceros': 'NombreACuentaTerceros',
                                    'RegimenFiscalACuentaTerceros': Code('630', 'Enajenación de acciones en bolsa de valores'),
                                    'RfcACuentaTerceros': 'AAA010101AAA'},
                'Cantidad': Decimal('1.6'),
                'ClaveProdServ': Code('95141904', 'Unidades quirúrgicas'),
                'ClaveUnidad': Code('WEE', 'Semana'),
                'Descripcion': 'ALUMINIO',
                'Importe': Decimal('2400'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2400'),
                                                                    'Importe': Decimal('264'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2400'),
                                                                  'Importe': Decimal('384'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'InformacionAduanera': ['15  48  4567  6001234'],
                'NoIdentificacion': '00002',
                'ObjetoImp': Code('02', 'Sí objeto de impuesto'),
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500')},
               {'Cantidad': Decimal('1.7'),
                'ClaveProdServ': Code('84101604', 'Ayuda gubernamental'),
                'ClaveUnidad': Code('G66', 'Litro por hora kelvin'),
                'Descripcion': 'ZAMAC',
                'Descuento': Decimal('0'),
                'Importe': Decimal('17000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('17000'),
                                                                    'Importe': Decimal('1870'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('17000'),
                                                                  'Importe': Decimal('2720'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00003',
                'ObjetoImp': Code('03', 'Sí objeto del impuesto y no obligado al desglose'),
                'Parte': [{'Cantidad': Decimal('1.0'),
                           'ClaveProdServ': Code('25201513', 'Cúpulas protectoras de la antena de avión'),
                           'Descripcion': 'PARTE EJEMPLO',
                           'Importe': Decimal('1.00'),
                           'InformacionAduanera': ['15  48  4567  6001235'],
                           'NoIdentificacion': '055155',
                           'Unidad': 'UNIDAD',
                           'ValorUnitario': Decimal('1.00')}],
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('10000')}],
 'CondicionesDePago': 'CONDICIONES',
 'Confirmacion': 'A1234',
 'Descuento': Decimal('0.00'),
 'Emisor': {'FacAtrAdquirente': '0123456789',
            'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('630', 'Enajenación de acciones en bolsa de valores'),
            'Rfc': 'AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 7, 23, 59, 59),
 'Folio': '123ABC',
 'FormaPago': Code('99', 'Por definir'),
 'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('247000'),
                                       'Impuesto': Code('001', 'ISR')},
                               '003': {'Importe': Decimal('500'),
                                       'Impuesto': Code('003', 'IEPS')}},
               'TotalImpuestosRetenidos': Decimal('247500'),
               'TotalImpuestosTrasladados': Decimal('360000'),
               'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('1.00'),
                                                   'Importe': Decimal('360000'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('1.600000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'InformacionGlobal': {'Año': 2021,
                       'Meses': Code('18', 'Noviembre-Diciembre'),
                       'Periodicidad': Code('05', 'Bimestral')},
 'LugarExpedicion': Code('99999', None),
 'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'NumRegIdTrib': '0000000000000',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'ResidenciaFiscal': Code('MEX', 'México'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('S01', 'Sin efectos fiscales')},
 'Sello': 'Gnm1yXaIig5hr1dJ+88gjLY5usQxXP2s+zdmlLl4iokWENaUUlhpG/crkUFEzcJfdq1FbBxV/d/GN50MGuw2fP5f6MkRYz75UKaKfzubUak+SCkDzYot5jZRkO6hXKe4+KAfaulP7wa8Q7oSW5ccivppLnikme0CS3KtGBrQHU/q3pjNrw+jMvsnpUc1tx91REqMWrzMTZ2D6UkGdqn8i/0mLRU2vT8vPaNg/Hr2jpVVAgQmPtfvnfnORCWSm/5qZg9Tli7nTRRVwupF4o9ajH2/Is7LoCsIgZUg3wCHkZCjaKk2mJoK7FyMTsPXRRSGhoYgwi1kNHs1aY4RHNwe5w==',
 'Serie': 'A',
 'SubTotal': Decimal('1000'),
 'TipoCambio': Decimal('1.0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('1500'),
 'Version': '4.0'}