{'Certificado': '',
 'CfdiRelacionados': [{'CfdiRelacionado': ['F4F09AEF-57F2-4BE0-A828-87D1A80ED61C'],
                       'TipoRelacion': Code('09', 'Factura generada por pagos diferidos')}],
 'Complemento': {'CartaPorte': {'EntradaSalidaMerc': 'Salida',
                                'FiguraTransporte': [{'Domicilio': {'Calle': 'Calle',
                                                                    'CodigoPostal': '123456',
                                                                    'Colonia': 'Colonia',
                                                                    'Estado': 'Estado',
                                                                    'Localidad': 'Localidad',
                                                                    'Municipio': 'Municipio',
                                                                    'NumeroExterior': '2',
                                                                    'NumeroInterior': '1',
                                                                    'Pais': Code('ZZZ', 'Países no declarados'),
                                                                    'Referencia': 'Referencia'},
                                                      'NombreFigura': '3456',
                                                      'NumLicencia': '12345678',
                                                      'NumRegIdTribFigura': '123456',
                                                      'PartesTransporte': [Code('PT12', 'Locomotora')],
                                                      'RFCFigura': 'BASJ600902KL9',
                                                      'ResidenciaFiscalFigura': Code('ZZZ', 'Países no declarados'),
                                                      'TipoFigura': Code('04', 'Notificado')}],
                                'Mercancias': {'Autotransporte': {'IdentificacionVehicular': {'AnioModeloVM': 2021,
                                                                                              'ConfigVehicular': Code('C2', 'Camión Unitario (2 llantas en el eje delantero y 4 llantas en el eje trasero)'),
                                                                                              'PlacaVM': '123ABC'},
                                                                  'NumPermisoSCT': '6789',
                                                                  'PermSCT': Code('TPAF01', 'Autotransporte Federal de carga general'),
                                                                  'Remolques': [{'Placa': 'Placa',
                                                                                 'SubTipoRem': Code('CTR032', 'Volteo Desmontable')}],
                                                                  'Seguros': {'AseguraCarga': 'AseguraCarga',
                                                                              'AseguraMedAmbiente': 'AseguraMedAmbiente',
                                                                              'AseguraRespCivil': 'AseguraRespCivil',
                                                                              'PolizaCarga': 'PolizaCarga',
                                                                              'PolizaMedAmbiente': 'PolizaMedAmbiente',
                                                                              'PolizaRespCivil': 'PolizaRespCivil',
                                                                              'PrimaSeguro': Decimal('12.123456')}},
                                               'CargoPorTasacion': Decimal('10.123456'),
                                               'Mercancia': [{'BienesTransp': Code('60141405', 'Kits o materiales para juegos de simulación'),
                                                              'Cantidad': Decimal('1.000001'),
                                                              'CantidadTransporta': [{'Cantidad': Decimal('1.000001'),
                                                                                      'CvesTransporte': Code('05', None),
                                                                                      'IDDestino': 'DE654321',
                                                                                      'IDOrigen': 'OR123456'}],
                                                              'ClaveSTCC': '1234567',
                                                              'ClaveUnidad': Code('ZZ', 'Mutuamente definido'),
                                                              'CveMaterialPeligroso': Code('M0005', None),
                                                              'DescripEmbalaje': 'DescripEmbalaje',
                                                              'Descripcion': 'Descripcion',
                                                              'DetalleMercancia': {'NumPiezas': 42,
                                                                                   'PesoBruto': Decimal('11.000'),
                                                                                   'PesoNeto': Decimal('9.00'),
                                                                                   'PesoTara': Decimal('9.123'),
                                                                                   'UnidadPesoMerc': Code('SM3', 'Metro cúbico estándar')},
                                                              'Dimensiones': '30/40/30cm',
                                                              'Embalaje': Code('Z01', 'No aplica'),
                                                              'FraccionArancelaria': Code('9807000100', 'Mercancías producidas en territorio nacional que retornen en el mismo estado en que fueron exportadas o retornadas del territorio nacional, de conformidad con los lineamientos establecidos por la Secretaría de Economía'),
                                                              'GuiasIdentificacion': [{'DescripGuiaIdentificacion': 'DescripGuiaIdentificacion',
                                                                                       'NumeroGuiaIdentificacion': '1234567890',
                                                                                       'PesoGuiaIdentificacion': Decimal('1.234')}],
                                                              'MaterialPeligroso': 'No',
                                                              'Moneda': Code('ZWL', 'Zimbabwe Dólar'),
                                                              'Pedimentos': ['12  '
                                                                             '34  '
                                                                             '5678  '
                                                                             '1234567'],
                                                              'PesoEnKg': Decimal('1.123'),
                                                              'UUIDComercioExt': 'c09b4f17-601c-40a1-b446-addb087e7e2b',
                                                              'Unidad': 'Unidad',
                                                              'ValorMercancia': Decimal('10.123456')}],
                                               'NumTotalMercancias': 1,
                                               'PesoBrutoTotal': Decimal('100.123'),
                                               'PesoNetoTotal': Decimal('101.234'),
                                               'TransporteAereo': {'CodigoTransportista': Code('CA156', 'Volaris (Concesionaria Vuela Cia De Aviación)'),
                                                                   'LugarContrato': 'LugarContrato',
                                                                   'MatriculaAeronave': 'A123456',
                                                                   'NombreAseg': 'NombreAseg',
                                                                   'NombreEmbarcador': 'NombreEmbarcador',
                                                                   'NumPermisoSCT': 'NumPermisoSCT',
                                                                   'NumPolizaSeguro': '345',
                                                                   'NumRegIdTribEmbarc': 'NumRegIdTribEmbarc',
                                                                   'NumeroGuia': '12345678901234',
                                                                   'PermSCT': Code('TPTA04', 'Permiso para el servicio nacional e internacional no regular de taxi aéreo'),
                                                                   'RFCEmbarcador': 'AAA010101AAA',
                                                                   'ResidenciaFiscalEmbarc': Code('ZZZ', 'Países no declarados')},
                                               'TransporteFerroviario': {'Carro': [{'Contenedor': [{'PesoContenedorVacio': Decimal('9.998'),
                                                                                                    'PesoNetoMercancia': Decimal('10.001'),
                                                                                                    'TipoContenedor': Code('TC05', 'Contenedor de 16.1 Mts de longitud')}],
                                                                                    'GuiaCarro': 'GuiaCarro',
                                                                                    'MatriculaCarro': 'MatriculaCarro',
                                                                                    'TipoCarro': Code('TC05', 'Plataforma Intermodal'),
                                                                                    'ToneladasNetasCarro': Decimal('12.001')}],
                                                                         'DerechosDePaso': [{'KilometrajePagado': Decimal('12.3'),
                                                                                             'TipoDerechoDePaso': Code('CDP119', 'TEMP-2')}],
                                                                         'NombreAseg': 'NombreAseg',
                                                                         'NumPolizaSeguro': 'NumPolizaSeguro',
                                                                         'TipoDeServicio': Code('TS04', 'Tren unitario Intermodal'),
                                                                         'TipoDeTrafico': Code('TT04', 'Tráfico interlineal en tránsito')},
                                               'TransporteMaritimo': {'AnioEmbarcacion': 2021,
                                                                      'Calado': Decimal('876'),
                                                                      'Contenedor': [{'MatriculaContenedor': 'ABC45678901',
                                                                                      'NumPrecinto': '123456',
                                                                                      'TipoContenedor': Code('CM009', 'Contenedor flat racks')}],
                                                                      'Eslora': Decimal('678'),
                                                                      'LineaNaviera': 'LineaNaviera',
                                                                      'Manga': Decimal('12'),
                                                                      'Matricula': 'ABC3456',
                                                                      'NacionalidadEmbarc': Code('ZZZ', 'Países no declarados'),
                                                                      'NombreAgenteNaviero': 'NombreAgenteNaviero',
                                                                      'NombreAseg': '2367',
                                                                      'NombreEmbarc': '789',
                                                                      'NumAutorizacionNaviero': 'SCT418/021/2021',
                                                                      'NumCertITC': 'NumCertITC',
                                                                      'NumConocEmbarc': '789',
                                                                      'NumPermisoSCT': '567',
                                                                      'NumPolizaSeguro': '631',
                                                                      'NumViaje': '78',
                                                                      'NumeroOMI': 'IMO1234567',
                                                                      'PermSCT': Code('TPAF03', 'Autotransporte Federal de Carga Especializada de materiales y residuos peligrosos'),
                                                                      'TipoCarga': Code('PYD', 'Petróleo y Derivados'),
                                                                      'TipoEmbarcacion': Code('B15', 'Extraordinaria especialización'),
                                                                      'UnidadesDeArqBruto': Decimal('23.456')},
                                               'UnidadPeso': Code('SM3', 'Metro cúbico estándar')},
                                'PaisOrigenDestino': Code('ZZZ', 'Países no declarados'),
                                'TotalDistRec': Decimal('123.9'),
                                'TranspInternac': 'Sí',
                                'Ubicaciones': [{'DistanciaRecorrida': Decimal('123.45'),
                                                 'Domicilio': {'Calle': 'Calle',
                                                               'CodigoPostal': '11850',
                                                               'Colonia': 'Colonia',
                                                               'Estado': 'Mexico '
                                                                         'City',
                                                               'Localidad': 'Localidad',
                                                               'Municipio': 'Municipio',
                                                               'NumeroExterior': '2',
                                                               'NumeroInterior': '1',
                                                               'Pais': Code('MEX', 'México'),
                                                               'Referencia': 'Referencia'},
                                                 'FechaHoraSalidaLlegada': datetime.datetime(2021, 11, 1, 1, 23, 59),
                                                 'IDUbicacion': 'OR123456',
                                                 'NavegacionTrafico': 'Cabotaje',
                                                 'NombreEstacion': 'NombreEstacion',
                                                 'NombreRemitenteDestinatario': 'NombreRemitenteDestinatario',
                                                 'NumEstacion': Code('EF001', None),
                                                 'NumRegIdTrib': '123456',
                                                 'RFCRemitenteDestinatario': 'AAA010101AAA',
                                                 'ResidenciaFiscal': Code('ZZZ', 'Países no declarados'),
                                                 'TipoEstacion': Code('03', 'Destino Final Nacional'),
                                                 'TipoUbicacion': 'Origen'},
                                                {'DistanciaRecorrida': Decimal('123.45'),
                                                 'Domicilio': {'Calle': 'Calle',
                                                               'CodigoPostal': '123456',
                                                               'Colonia': 'Colonia',
                                                               'Estado': 'Estado',
                                                               'Localidad': 'Localidad',
                                                               'Municipio': 'Municipio',
                                                               'NumeroExterior': '2',
                                                               'NumeroInterior': '1',
                                                               'Pais': Code('ZZZ', 'Países no declarados'),
                                                               'Referencia': 'Referencia'},
                                                 'FechaHoraSalidaLlegada': datetime.datetime(2021, 11, 1, 1, 23, 59),
                                                 'IDUbicacion': 'DE234567',
                                                 'NavegacionTrafico': 'Cabotaje',
                                                 'NombreEstacion': 'NombreEstacion',
                                                 'NombreRemitenteDestinatario': 'NombreRemitenteDestinatario',
                                                 'NumEstacion': Code('EF001', None),
                                                 'NumRegIdTrib': '012345',
                                                 'RFCRemitenteDestinatario': 'BASJ600902KL9',
                                                 'ResidenciaFiscal': Code('ZZZ', 'Países no declarados'),
                                                 'TipoEstacion': Code('03', 'Destino Final Nacional'),
                                                 'TipoUbicacion': 'Destino'}],
                                'Version': '2.0',
                                'ViaEntradaSalida': Code('05', None)}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Descripcion',
                'Importe': Decimal('0'),
                'ObjetoImp': Code('01', 'No objeto de impuesto'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Exportacion': Code('03', 'Temporal'),
 'Fecha': datetime.datetime(2021, 12, 8, 23, 59, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '99999',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '30001000000300023708',
 'Receptor': {'DomicilioFiscalReceptor': '99999',
              'Nombre': 'Juanito Bananas De la Sierra',
              'RegimenFiscalReceptor': Code('630', 'Enajenación de acciones en bolsa de valores'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '4.0'}