{'Certificado': '',
 'Conceptos': [{'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'CuentaPredial': '1234567890',
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Importe': Decimal('15390.30'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1539.03'),
                                               'Impuesto': '001',
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': 'Tasa'},
                                              {'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1641.64'),
                                               'Impuesto': '002',
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': 'Tasa'}],
                              'Traslados': [{'Base': Decimal('15390.30'),
                                             'Importe': Decimal('2462.45'),
                                             'Impuesto': '002',
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': 'Tasa'}]},
                'ObjetoImp': '02',
                'ValorUnitario': Decimal('15390.29999999999927240423858165740966796875'),
                '_traslados_incluidos': False}],
 'Descuento': None,
 'Emisor': {'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'Impuestos': {'Retenciones': [{'Importe': Decimal('1539.03'),
                                'Impuesto': '001'},
                               {'Importe': Decimal('1641.64'),
                                'Impuesto': '002'}],
               'TotalImpuestosRetenidos': Decimal('3180.67'),
               'TotalImpuestosTrasladados': Decimal('2462.45'),
               'Traslados': [{'Base': Decimal('15390.30'),
                              'Importe': Decimal('2462.45'),
                              'Impuesto': '002',
                              'TasaOCuota': Decimal('0.160000'),
                              'TipoFactor': 'Tasa'}]},
 'LugarExpedicion': '56820',
 'Moneda': 'MXN',
 'NoCertificado': '',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'RegimenFiscalReceptor': '601',
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': '',
 'Serie': 'A',
 'SubTotal': Decimal('15390.30'),
 'TipoDeComprobante': 'I',
 'Total': Decimal('14672.08'),
 'Version': '4.0'}