{'Addenda': None,
 'Certificado': '',
 'CfdiRelacionados': None,
 'Complemento': None,
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': Decimal('1.00'),
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': '1234567890',
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('15390.30'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1539.03'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1641.64'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('15390.30'),
                                             'Importe': Decimal('2462.45'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('15390.30')}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'Retenciones': [{'Importe': Decimal('1539.03'),
                                'Impuesto': <Impuesto.ISR: '001'>},
                               {'Importe': Decimal('1641.64'),
                                'Impuesto': <Impuesto.IVA: '002'>}],
               'TotalImpuestosRetenidos': Decimal('3180.67'),
               'TotalImpuestosTrasladados': Decimal('2462.45'),
               'Traslados': [{'Base': Decimal('15390.30'),
                              'Importe': Decimal('2462.45'),
                              'Impuesto': <Impuesto.IVA: '002'>,
                              'TasaOCuota': Decimal('0.160000'),
                              'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': '',
 'Serie': 'A',
 'SubTotal': Decimal('15390.30'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('14672.08'),
 'Version': '4.0'}