{'Addenda': None,
 'Certificado': 'MIIGAjCCA+qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0NjAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjIwMTcwMjQwWhcNMjMwNjE5MTcwMjQwWjCB9zEmMCQGA1UEAxQdSEVSUkVSSUEgJiBFTEVDVFJJQ09TIFMgREUgQ1YxJjAkBgNVBCkUHUhFUlJFUklBICYgRUxFQ1RSSUNPUyBTIERFIENWMSYwJAYDVQQKFB1IRVJSRVJJQSAmIEVMRUNUUklDT1MgUyBERSBDVjELMAkGA1UEBhMCTVgxKTAnBgkqhkiG9w0BCQEWGnBydWViYXMuc2F0QHBydWViYXMuZ29iLm14MSUwIwYDVQQtFBxIJkU5NTExMjg0NjkgLyBYT0pJNzQwOTE5VTQ4MR4wHAYDVQQFExUgLyBYT0pJNzQwOTE5TVFURE1OMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCystUoikV7leAFvyR4CyNAfcWugApKe9c4F7PwoE8z8waUOXUdWMVGIzt++OCPcc570xZ4IQFZwn6zjB8apZ2IqAmPeEoO89wC8jViNvo7YKiF++gWo3DBGl795wVlfrqb94zRQtokj7YuU33RsyNH0XudY8DShM/qvA2eqX5M0c/8CzTJesDoQJxvJDetYLR+ksJASj+PuDJedK/OoKE5S9LmwgZEAQ1HKyjDnMolY4VdmiGdw/Aljh2iO4TY4IB7vHry23mJOm+HdwJqwXg48A1Vp86JtbkDCg3IzI+PAEdncP3WjVkmkJyKSI899un7VXeUoh9oHIJcFdXrHOdxAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggIBAI2Qaj4co5YUuWa6jtUZFpKAxx5StDlOmVhyBpf3GFEvtTEvS7mLTHTARIOOcmHFHHc8mmVD3dPsUTrDxlo1qWR2qwrvrUn38bxkEF5IJK/XKcG0LOupl67V2gvnrm5bVkT9kJuYjYHdPFuSao4yEJhzHnMHOvT6rC3hhjywo6QGegQTuR+oTrwHQeU8SplNqkwd6k/GWL7Ba/2bVhH79lB4QpjuO2BXip0sHhLbctwu98Sp1FSiaooDlMzQeQoVWW8QgUQp15LaClsOTZRnXxztOR/h6cd25XQezdxqEoV0rS9BW+sgABPQNXDRWK87aeJ3R5lByjUhbt0eONod42l/emAiDE9S85tztQ4KkvMFA3e0vIth70sinS5eV/j1l4Ws+Ft/pdNA/AP3a2R6b+Lw4P7hCBVLtunx8pbh15KzX5g947JN5KVhMKvnqciCoMC9GowLzua/VNJX5pPiKXD6fm5bljW5JQ5F4Ue30Hve6lmftLGDXtOCDfj74+Zs3f3Y9gXkPAsK4y2WyZ1Xpw9dAIJJv5HajJwxbQVP2B48aN0ai46Dc6tQEp+Oa4oNHTRRyNNlqXwEb+IGtQ4FwiL13c55gOaSie1buy26a0yAO3ogcDfNyTcbfC73W9R0Zi4gsb+6xLuHZOLTJWUWLY9bE43P++KbWCGKz0uwIA3u',
 'CfdiRelacionados': None,
 'Complemento': {'Pago': [{'DoctoRelacionado': [{'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('17852.75'),
                                                 'ImpSaldoAnt': Decimal('17852.75'),
                                                 'ImpSaldoInsoluto': Decimal('0.00'),
                                                 'ImpuestosDR': {'TrasladosDR': [{'BaseDR': Decimal('15390.30'),
                                                                                  'ImporteDR': Decimal('2462.45'),
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': Decimal('0.160000'),
                                                                                  'TipoFactorDR': Code('Tasa', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 1,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'},
                                                {'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('17852.75'),
                                                 'ImpSaldoAnt': Decimal('17852.75'),
                                                 'ImpSaldoInsoluto': Decimal('0.00'),
                                                 'ImpuestosDR': {'TrasladosDR': [{'BaseDR': Decimal('15390.30'),
                                                                                  'ImporteDR': Decimal('2462.45'),
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': Decimal('0.160000'),
                                                                                  'TipoFactorDR': Code('Tasa', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 1,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'}],
                           'FechaPago': datetime.datetime(2020, 1, 2, 22, 40, 38),
                           'FormaDePagoP': '03',
                           'MonedaP': Code('MXN', 'Peso Mexicano'),
                           'Monto': Decimal('35705.50'),
                           'TipoCambioP': None}],
                 'Version': '1.0'},
 'Conceptos': {'ACuentaTerceros': None,
               'Cantidad': 1,
               'ClaveProdServ': '84111506',
               'ClaveUnidad': 'ACT',
               'ComplementoConcepto': None,
               'CuentaPredial': None,
               'Descripcion': 'Pago',
               'Descuento': None,
               'Importe': Decimal('0'),
               'Impuestos': None,
               'InformacionAduanera': None,
               'NoIdentificacion': None,
               'ObjetoImp': '01',
               'Parte': None,
               'Unidad': None,
               'ValorUnitario': Decimal('0'),
               '_traslados_incluidos': False},
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'Nombre': 'HERRERIA & ELECTRICOS',
            'RegimenFiscal': '606',
            'Rfc': RFC('H&E951128469')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': None,
 'Moneda': 'XXX',
 'NoCertificado': '30001000000400002460',
 'Receptor': {'Nombre': 'KIJ, S.A DE C.V.',
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'P01'},
 'Sello': 'snK2vv1fQIvMi5aVzKz2Q79ptb3SGyov2zFmsj8gIu90qu6yuWteGdLGTR5LpTOk0n/tpJCzF+H4jr1hrJ55RUx5+4Pep/C1UaYBkHXjUlKrGDtx8rN1V2/uuqtOnGHgzDvs7dH7SRZmKVhcH1KmEoabwP6cNFMDDQxGI9ufRUOyxrrmEZlRjgesgv3DOm6cO9wXxZpM5KPD/kwHFCi4TZWqvIjPAWpSQb2eWftUnzlgst3FhIEJ6DBImyVA0vcIspd2YPYwRi7jscIpMzYLHyp5rVDze7n9W+6sXjOawKWvFIF0mP2yNoXF6/r1ev1xybMuGZimAOTJt6TIt3rYIg==',
 'Serie': 'A',
 'SubTotal': Decimal('0'),
 'TipoCambio': None,
 'TipoDeComprobante': 'P',
 'Total': Decimal('0'),
 'Version': '3.3'}