{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': {'Pago': [{'DoctoRelacionado': [{'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('14672.08'),
                                                 'ImpSaldoAnt': Decimal('14672.08'),
                                                 'ImpSaldoInsoluto': Decimal('0.00'),
                                                 'ImpuestosDR': {'RetencionesDR': [{'BaseDR': Decimal('15390.30'),
                                                                                    'ImporteDR': Decimal('1539.03'),
                                                                                    'ImpuestoDR': Code('001', 'ISR'),
                                                                                    'TasaOCuotaDR': Decimal('0.100000'),
                                                                                    'TipoFactorDR': Code('Tasa', None)},
                                                                                   {'BaseDR': Decimal('15390.30'),
                                                                                    'ImporteDR': Decimal('1641.64'),
                                                                                    'ImpuestoDR': Code('002', 'IVA'),
                                                                                    'TasaOCuotaDR': Decimal('0.106667'),
                                                                                    'TipoFactorDR': Code('Tasa', None)}],
                                                                 'TrasladosDR': [{'BaseDR': Decimal('15390.30'),
                                                                                  'ImporteDR': Decimal('2462.45'),
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': Decimal('0.160000'),
                                                                                  'TipoFactorDR': Code('Tasa', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 1,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'}],
                           'FechaPago': datetime.datetime(2020, 1, 2, 22, 40, 38),
                           'FormaDePagoP': '03',
                           'MonedaP': Code('MXN', 'Peso Mexicano'),
                           'Monto': Decimal('14672.08'),
                           'TipoCambioP': None}],
                 'Version': '1.0'},
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '84111506',
                'ClaveUnidad': 'ACT',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'Pago',
                'Descuento': None,
                'Importe': Decimal('0'),
                'Impuestos': None,
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '01',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('0')}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': None,
 'Moneda': 'XXX',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'Nombre': 'KIJ, S.A DE C.V.',
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'P01'},
 'Sello': 'QjM4vJVlnuqW0uUuighav0ws5O4YQNVOhLMQTMIYubbBaSv8op+jpjVPaR/UQr9Y0CAnL12NZZBqLE2POELVTslGUi2SyxOTakaTuddvGiE/YEo6Cr/SgmzkNMOoCjJd6yi9NL8kly2/c2UpYvRaMKzzml/tbmAswNiOwZ+A3Z4w8Hcf85UG+LQT9tU6DKNcZ+s30YNdcVsvL4Hjj9OOBHTMtewFCaxbbZy1Q8jumWBqWZ0x+cI6ei3co0A9eINnRneXrHg299gl+3jPFP8G7LLCKndGUM7B9SK12qhLefY5GB1ui9QKj/IGqG7vH9nyBpqupMdoF3SYhKtygAJRKA==',
 'Serie': 'A',
 'SubTotal': Decimal('0'),
 'TipoCambio': None,
 'TipoDeComprobante': 'P',
 'Total': Decimal('0'),
 'Version': '3.3'}