{'Certificado': '',
 'Complemento': {'Arrendamientoenfideicomiso': {'DeduccCorresp': Decimal('0.00'),
                                                'PagProvEfecPorFiduc': Decimal('0.00'),
                                                'RendimFideicom': Decimal('0.00'),
                                                'Version': '1.0'},
                 'Dividendos': {'DividOUtil': {'CveTipDivOUtil': Code('01', 'Proviene de CUFIN'),
                                               'MontISRAcredRetExtranjero': Decimal('0.00'),
                                               'MontISRAcredRetMexico': Decimal('0.00'),
                                               'TipoSocDistrDiv': 'Sociedad '
                                                                  'Nacional'},
                                'Version': '1.0'},
                 'EnajenaciondeAcciones': {'ContratoIntermediacion': 'NO HAY '
                                                                     'CONTRATO',
                                           'Ganancia': Decimal('0.00'),
                                           'Perdida': Decimal('0.00'),
                                           'Version': '1.0'},
                 'Fideicomisonoempresarial': {'DeduccOSalidas': {'IntegracEgresos': 'Nada',
                                                                 'MontTotEgresPeriodo': Decimal('0.00'),
                                                                 'PartPropDelFideicom': Decimal('0.00'),
                                                                 'PropDelMontTot': Decimal('20.000000')},
                                              'IngresosOEntradas': {'IntegracIngresos': 'ESTE '
                                                                                        'ES '
                                                                                        'EL '
                                                                                        'CONCEPTO',
                                                                    'MontTotEntradasPeriodo': Decimal('0.00'),
                                                                    'PartPropAcumDelFideicom': Decimal('0.00'),
                                                                    'PropDelMontTot': Decimal('20.815484')},
                                              'RetEfectFideicomiso': {'DescRetRelPagFideic': 'Descripción',
                                                                      'MontRetRelPagFideic': Decimal('0.00')},
                                              'Version': '1.0'},
                 'Intereses': {'MontIntNominal': Decimal('1.000'),
                               'MontIntReal': Decimal('2.000'),
                               'OperFinancDerivad': 'NO',
                               'Perdida': Decimal('3.000'),
                               'RetiroAORESRetInt': 'NO',
                               'SistFinanciero': 'NO',
                               'Version': '1.0'},
                 'Intereseshipotecarios': {'CreditoDeInstFinanc': 'NO',
                                           'SaldoInsoluto': Decimal('0.00'),
                                           'Version': '1.0'},
                 'Operacionesconderivados': {'MontGanAcum': Decimal('1.0'),
                                             'MontPerdDed': Decimal('1.0'),
                                             'Version': '1.0'},
                 'Pagosaextranjeros': {'Beneficiario': {'CURP': 'AAAA010101HJCXXX01',
                                                        'ConceptoPago': Code('6', 'Organizaciones Internacionales o de gobierno'),
                                                        'DescripcionConcepto': 'ESTA '
                                                                               'ES '
                                                                               'LA '
                                                                               'DESCRIPCION',
                                                        'NomDenRazSocB': 'PRUEBA '
                                                                         'DE '
                                                                         'PERSONA '
                                                                         'FISICA',
                                                        'RFC': 'AAAA010101AA0'},
                                       'EsBenefEfectDelCobro': 'SI',
                                       'NoBeneficiario': {'ConceptoPago': Code('6', 'Organizaciones Internacionales o de gobierno'),
                                                          'DescripcionConcepto': 'ESTA '
                                                                                 'ES '
                                                                                 'LA '
                                                                                 'DESCRIPCION',
                                                          'PaisDeResidParaEfecFisc': Code('IT', 'ITALIA (REPUBLICA ITALIANA)')},
                                       'Version': '1.0'},
                 'Planesderetiro': {'AportacionesODepositos': [{'MontAportODep': Decimal('1000000.00'),
                                                                'TipoAportacionODeposito': Code('c', 'Aportaciones adicionales efectuadas en términos del artículo 258')}],
                                    'HuboRetirosAnioInmAnt': 'SI',
                                    'HuboRetirosAnioInmAntPer': 'NO',
                                    'MontIntRealesDevengAniooInmAnt': Decimal('0.00'),
                                    'SistemaFinanc': 'NO',
                                    'Version': '1.1'},
                 'Premios': {'EntidadFederativa': Code('18', 'NAYARIT'),
                             'MontTotPago': Decimal('50000'),
                             'MontTotPagoExent': Decimal('0'),
                             'MontTotPagoGrav': Decimal('50000'),
                             'Version': '1.0'},
                 'SectorFinanciero': {'DescripFideicom': 'DEScRIPCION DEL '
                                                         'FIDEICOM',
                                      'IdFideicom': '191216',
                                      'Version': '1.0'},
                 'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2021, 12, 9, 16, 24),
                                         'NoCertificadoSAT': '30001000000300023699',
                                         'RfcProvCertif': 'AAA010101AAA',
                                         'SelloCFD': 'Gnm1yXaIig5hr1dJ+88gjLY5usQxXP2s+zdmlLl4iokWENaUUlhpG/crkUFEzcJfdq1FbBxV/d/GN50MGuw2fP5f6MkRYz75UKaKfzubUak+SCkDzYot5jZRkO6hXKe4+KAfaulP7wa8Q7oSW5ccivppLnikme0CS3KtGBrQHU/q3pjNrw+jMvsnpUc1tx91REqMWrzMTZ2D6UkGdqn8i/0mLRU2vT8vPaNg/Hr2jpVVAgQmPtfvnfnORCWSm/5qZg9Tli7nTRRVwupF4o9ajH2/Is7LoCsIgZUg3wCHkZCjaKk2mJoK7FyMTsPXRRSGhoYgwi1kNHs1aY4RHNwe5w==',
                                         'SelloSAT': 'f1aiyIzFn04YNpLzS6+BN5V+qchEzrjo3yiBvbzSMSqd90OEL46+FCfZVZXCeev4yj2t27mhgWOhu6uBI/R6HRb5/U0VDc7XgUE+IZ4UV00Xd6HJXAZAGXH6+ebKYpxjxevz3C0zKrvsneQBMUPlG8zgnU1hJkyNrDp2KD3ybq71VO4r3kLHL/KtSlqZhoKtGPUWJ06Q3vDQ15WI3sOUbg2cuyJ2LIr3U+EYP4BHnCiHgq/S3KwWIqEAZxz/6lm4J3ZTnhFI9GTtMQWPyKCGxyRiRV9jX8sVuo9QL/ZijimHT8eUpeuxz/2rY0OmfmKrNzEm7wb7SU/oxfMskuHK5A==',
                                         'UUID': '02e3bc7c-beda-41bf-8a6b-f74915e9b61f',
                                         'Version': '1.1'}},
 'CveRetenc': Code('01', 'Servicios profesionales'),
 'Emisor': {'NomDenRazSocE': 'PERSONA FÍSICA DE PRUEBA',
            'RegimenFiscalE': Code('630', 'Enajenación de acciones en bolsa de valores'),
            'RfcE': 'AAAA010101AAA'},
 'FechaExp': datetime.datetime(2021, 12, 12, 12, 45, 29),
 'LugarExpRetenc': '99999',
 'NoCertificado': '30001000000300023708',
 'Periodo': {'Ejercicio': Code('2027', None),
             'MesFin': Code('12', 'Diciembre'),
             'MesIni': Code('01', 'Enero')},
 'Receptor': {'Extranjero': {'NomDenRazSocR': 'PERSONA FISICA NACIONAL DE '
                                              'PRUEBA'},
              'NacionalidadR': 'Extranjero'},
 'Sello': '',
 'Totales': {'ISRCorrespondiente': Decimal('11.2'),
             'ImpRetenidos': [{'MontoRet': Decimal('1.00'),
                               'TipoPagoRet': Code('02', 'Pago definitivo IEPS')}],
             'MontoTotExent': Decimal('1.00'),
             'MontoTotGrav': Decimal('1.00'),
             'MontoTotOperacion': Decimal('1.00'),
             'MontoTotRet': Decimal('1.00')},
 'Version': '2.0'}