{'Certificado': '',
 'Complemento': {},
 'CveRetenc': Code('01', 'Servicios profesionales'),
 'Emisor': {'NomDenRazSocE': 'PERSONA FÍSICA DE PRUEBA',
            'RegimenFiscalE': Code('630', 'Enajenación de acciones en bolsa de valores'),
            'RfcE': 'AAAA010101AAA'},
 'FechaExp': datetime.datetime(2021, 12, 12, 12, 45, 29),
 'LugarExpRetenc': '99999',
 'NoCertificado': '30001000000300023708',
 'Periodo': {'Ejercicio': Code('2027', None),
             'MesFin': Code('12', 'Diciembre'),
             'MesIni': Code('01', 'Enero')},
 'Receptor': {'Extranjero': {'NomDenRazSocR': 'PERSONA FISICA NACIONAL DE '
                                              'PRUEBA'},
              'NacionalidadR': 'Extranjero'},
 'Sello': '',
 'Totales': {'ISRCorrespondiente': Decimal('11.2'),
             'ImpRetenidos': [{'MontoRet': Decimal('1.00'),
                               'TipoPagoRet': Code('02', 'Pago definitivo IEPS')}],
             'MontoTotExent': Decimal('1.00'),
             'MontoTotGrav': Decimal('1.00'),
             'MontoTotOperacion': Decimal('1.00'),
             'MontoTotRet': Decimal('1.00')},
 'Version': '2.0'}