{'Addenda': {},
 'Cert': 'MIIEdDCCA1ygAwIBAgIUMjAwMDEwMDAwMDAxMDAwMDU4NjcwDQYJKoZIhvcNAQEFBQAwggFvMRgwFgYDVQQDDA9BLkMuIGRlIHBydWViYXMxLzAtBgNVBAoMJlNlcnZpY2lvIGRlIEFkbWluaXN0cmFjacOzbiBUcmlidXRhcmlhMTgwNgYDVQQLDC9BZG1pbmlzdHJhY2nDs24gZGUgU2VndXJpZGFkIGRlIGxhIEluZm9ybWFjacOzbjEpMCcGCSqGSIb3DQEJARYaYXNpc25ldEBwcnVlYmFzLnNhdC5nb2IubXgxJjAkBgNVBAkMHUF2LiBIaWRhbGdvIDc3LCBDb2wuIEd1ZXJyZXJvMQ4wDAYDVQQRDAUwNjMwMDELMAkGA1UEBhMCTVgxGTAXBgNVBAgMEERpc3RyaXRvIEZlZGVyYWwxEjAQBgNVBAcMCUNveW9hY8OhbjEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMTIwMAYJKoZIhvcNAQkCDCNSZXNwb25zYWJsZTogSMOpY3RvciBPcm5lbGFzIEFyY2lnYTAeFw0xMjA3MjcxNzAyMDBaFw0xNjA3MjcxNzAyMDBaMIHbMSkwJwYDVQQDEyBBQ0NFTSBTRVJWSUNJT1MgRU1QUkVTQVJJQUxFUyBTQzEpMCcGA1UEKRMgQUNDRU0gU0VSVklDSU9TIEVNUFJFU0FSSUFMRVMgU0MxKTAnBgNVBAoTIEFDQ0VNIFNFUlZJQ0lPUyBFTVBSRVNBUklBTEVTIFNDMSUwIwYDVQQtExxBQUEwMTAxMDFBQUEgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxETAPBgNVBAsTCFVuaWRhZCAxMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2TTQSPONBOVxpXv9wLYo8jezBrb34i/tLx8jGdtyy27BcesOav2c1NS/Gdv10u9SkWtwdy34uRAVe7H0a3VMRLHAkvp2qMCHaZc4T8k47Jtb9wrOEh/XFS8LgT4y5OQYo6civfXXdlvxWU/gdM/e6I2lg6FGorP8H4GPAJ/qCNwIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQUFAAOCAQEATxMecTpMbdhSHo6KVUg4QVF4Op2IBhiMaOrtrXBdJgzGotUFcJgdBCMjtTZXSlq1S4DG1jr8p4NzQlzxsdTxaB8nSKJ4KEMgIT7E62xRUj15jI49qFz7f2uMttZLNThipunsN/NF1XtvESMTDwQFvas/Ugig6qwEfSZc0MDxMpKLEkEePmQwtZD+zXFSMVa6hmOu4M+FzGiRXbj4YJXn9Myjd8xbL/c+9UIcrYoZskxDvMxc6/6M3rNNDY3OFhBK+V/sPMzWWGt8S1yjmtPfXgFs1t65AZ2hcTwTAuHrKwDatJ1ZPfa482ZBROAAX1waz7WwXp0gso7sDCm2/yUVww==',
 'Complemento': {'SectorFinanciero': {'DescripFideicom': 'Inversiones '
                                                         'relacionadas a '
                                                         'hidrocarburos '
                                                         'nacionales',
                                      'IdFideicom': 'YHNL28191234',
                                      'NomFideicom': 'Inversión Bolsa Mexicana '
                                                     'de Valores - PXT',
                                      'Version': '1.0'},
                 'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2015, 2, 24, 11, 2, 52),
                                         'NoCertificadoSAT': '20001000000300003693',
                                         'SelloCFD': 'bmqdDtL5teyhDVxnKXXtet2D3AmW4ESroehshWMSTCMbEaaU+Mtv6lD1VTJ86ehoesqEZ7r9XVGFaq9zt/QPBxx7kHVm58iCgCSqhF7ud6FUEBztRdTdovinL5l65TzGVRXQjVs4NHBPQXveiLfZnOCf8uwCBo7KR3TD2Woh1CU=',
                                         'SelloSAT': 'Vz6Edbwbq1NJ7i/2+Iv5qRQEn0LfN/ASqqfUogtLzwG1CTIFBiMPuBzIXC1Y1OYu5n/DO1MuhtqwTD0EB9JKBNLIQRL5FTI8BlNeNbmMyjK9XlJbwdPIej5tm/h3EqF34E+AKeSK0cfxfBkz2xbaxvESwc+2VrsVJmOKCKBHA4I=',
                                         'UUID': 'd3446292-1355-4149-aef9-ccfeff8240dc',
                                         'Version': '1.0'}},
 'CveRetenc': Code('25', 'Otro tipo de retenciones'),
 'DescRetenc': 'Otro tipo de retenciones - Sector Financiero',
 'Emisor': {'CURPE': 'AAAA010101HNLMNLD2',
            'NomDenRazSocE': 'Empresa DEMO para Rentenciones S de TST',
            'RFCEmisor': 'AAA010101AAA'},
 'FechaExp': datetime.datetime(2015, 2, 24, 11, 2, 52, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800))),
 'FolioInt': 'TEST00012',
 'NumCert': '20001000000100005867',
 'Periodo': {'Ejerc': 2014, 'MesFin': 6, 'MesIni': 6},
 'Receptor': {'Nacional': {'CURPR': 'VAHE820926HNLLRD02',
                           'NomDenRazSocR': 'PÚBLICO EN GENERAL S DE TST',
                           'RFCRecep': 'XAXX010101000'},
              'Nacionalidad': 'Nacional'},
 'Sello': 'bmqdDtL5teyhDVxnKXXtet2D3AmW4ESroehshWMSTCMbEaaU+Mtv6lD1VTJ86ehoesqEZ7r9XVGFaq9zt/QPBxx7kHVm58iCgCSqhF7ud6FUEBztRdTdovinL5l65TzGVRXQjVs4NHBPQXveiLfZnOCf8uwCBo7KR3TD2Woh1CU=',
 'Totales': {'ImpRetenidos': [{'BaseRet': Decimal('1000.00'),
                               'Impuesto': Code('01', 'ISR'),
                               'MontoRet': Decimal('500.00'),
                               'TipoPagoRet': 'Pago definitivo'},
                              {'BaseRet': Decimal('1000.00'),
                               'Impuesto': Code('02', 'IVA'),
                               'MontoRet': Decimal('500.00'),
                               'TipoPagoRet': 'Pago provisional'}],
             'MontoTotExent': Decimal('1000.00'),
             'MontoTotGrav': Decimal('13000.00'),
             'MontoTotOperacion': Decimal('14000.00'),
             'MontoTotRet': Decimal('3500.00')},
 'Version': '1.0'}