{'Addenda': {},
 'Cert': 'MIIEdDCCA1ygAwIBAgIUMjAwMDEwMDAwMDAxMDAwMDU4NjcwDQYJKoZIhvcNAQEFBQAwggFvMRgwFgYDVQQDDA9BLkMuIGRlIHBydWViYXMxLzAtBgNVBAoMJlNlcnZpY2lvIGRlIEFkbWluaXN0cmFjacOzbiBUcmlidXRhcmlhMTgwNgYDVQQLDC9BZG1pbmlzdHJhY2nDs24gZGUgU2VndXJpZGFkIGRlIGxhIEluZm9ybWFjacOzbjEpMCcGCSqGSIb3DQEJARYaYXNpc25ldEBwcnVlYmFzLnNhdC5nb2IubXgxJjAkBgNVBAkMHUF2LiBIaWRhbGdvIDc3LCBDb2wuIEd1ZXJyZXJvMQ4wDAYDVQQRDAUwNjMwMDELMAkGA1UEBhMCTVgxGTAXBgNVBAgMEERpc3RyaXRvIEZlZGVyYWwxEjAQBgNVBAcMCUNveW9hY8OhbjEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMTIwMAYJKoZIhvcNAQkCDCNSZXNwb25zYWJsZTogSMOpY3RvciBPcm5lbGFzIEFyY2lnYTAeFw0xMjA3MjcxNzAyMDBaFw0xNjA3MjcxNzAyMDBaMIHbMSkwJwYDVQQDEyBBQ0NFTSBTRVJWSUNJT1MgRU1QUkVTQVJJQUxFUyBTQzEpMCcGA1UEKRMgQUNDRU0gU0VSVklDSU9TIEVNUFJFU0FSSUFMRVMgU0MxKTAnBgNVBAoTIEFDQ0VNIFNFUlZJQ0lPUyBFTVBSRVNBUklBTEVTIFNDMSUwIwYDVQQtExxBQUEwMTAxMDFBQUEgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxETAPBgNVBAsTCFVuaWRhZCAxMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2TTQSPONBOVxpXv9wLYo8jezBrb34i/tLx8jGdtyy27BcesOav2c1NS/Gdv10u9SkWtwdy34uRAVe7H0a3VMRLHAkvp2qMCHaZc4T8k47Jtb9wrOEh/XFS8LgT4y5OQYo6civfXXdlvxWU/gdM/e6I2lg6FGorP8H4GPAJ/qCNwIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQUFAAOCAQEATxMecTpMbdhSHo6KVUg4QVF4Op2IBhiMaOrtrXBdJgzGotUFcJgdBCMjtTZXSlq1S4DG1jr8p4NzQlzxsdTxaB8nSKJ4KEMgIT7E62xRUj15jI49qFz7f2uMttZLNThipunsN/NF1XtvESMTDwQFvas/Ugig6qwEfSZc0MDxMpKLEkEePmQwtZD+zXFSMVa6hmOu4M+FzGiRXbj4YJXn9Myjd8xbL/c+9UIcrYoZskxDvMxc6/6M3rNNDY3OFhBK+V/sPMzWWGt8S1yjmtPfXgFs1t65AZ2hcTwTAuHrKwDatJ1ZPfa482ZBROAAX1waz7WwXp0gso7sDCm2/yUVww==',
 'Complemento': {'Planesderetiro': {'HuboRetirosAnioInmAnt': 'NO',
                                    'HuboRetirosAnioInmAntPer': 'NO',
                                    'MontIntRealesDevengAniooInmAnt': Decimal('567.21'),
                                    'MontTotAportAnioInmAnterior': Decimal('62812.8734'),
                                    'MontTotExedenteAnioInmAnt': Decimal('0.00'),
                                    'MontTotExentRetiradoAnioInmAnt': Decimal('0.00'),
                                    'MontTotRetiradoAnioInmAnt': Decimal('0.00'),
                                    'MontTotRetiradoAnioInmAntPer': Decimal('0.00'),
                                    'SistemaFinanc': 'SI',
                                    'Version': '1.0'},
                 'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2015, 2, 24, 11, 2, 50),
                                         'NoCertificadoSAT': '20001000000300003693',
                                         'SelloCFD': 'WIOikzPVRwYkE2EQvKwocNhn/KEGxVT4EEaWcLDb1DogoTjHhCYrkrF96EqQR1TQxhu0BL1cQ60mLJ0wTOEYLjmLVS4KZ9tjqs/tYcbv9FRjywj5rKQNAnrHmArXt+7Gyhceu9gQEXCHhcbdTRs6hwh+A58ojFX+KqSkUCIuj/w=',
                                         'SelloSAT': 'nEnFxEiSWlUvvZXqx36n0c6a3ZTPsyVqLViMhnd34ct8NIJMzCsZZf2tQ0hONfZxECP3ILn9n/ViVZ1u2nPRDI/1nq+SxNN113R29DM2A//GbH2BNdDc8aKks/YXB63lryuj7F2dlGXcWl12Zfu70MMerKJVCBEGjxJ2Ei7ZYhk=',
                                         'UUID': 'ddd43fd2-07eb-4788-8d88-149755b16bf7',
                                         'Version': '1.0'}},
 'CveRetenc': Code('22', 'Planes personales de retiro'),
 'DescRetenc': 'Planes personales de retiro',
 'Emisor': {'CURPE': 'AAAA010101HNLMNLD2',
            'NomDenRazSocE': 'Empresa DEMO para Rentenciones S de TST',
            'RFCEmisor': 'AAA010101AAA'},
 'FechaExp': datetime.datetime(2015, 2, 24, 11, 2, 50, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800))),
 'FolioInt': 'TEST00010',
 'NumCert': '20001000000100005867',
 'Periodo': {'Ejerc': 2014, 'MesFin': 6, 'MesIni': 6},
 'Receptor': {'Nacional': {'CURPR': 'VAHE820926HNLLRD02',
                           'NomDenRazSocR': 'PÚBLICO EN GENERAL S DE TST',
                           'RFCRecep': 'XAXX010101000'},
              'Nacionalidad': 'Nacional'},
 'Sello': 'WIOikzPVRwYkE2EQvKwocNhn/KEGxVT4EEaWcLDb1DogoTjHhCYrkrF96EqQR1TQxhu0BL1cQ60mLJ0wTOEYLjmLVS4KZ9tjqs/tYcbv9FRjywj5rKQNAnrHmArXt+7Gyhceu9gQEXCHhcbdTRs6hwh+A58ojFX+KqSkUCIuj/w=',
 'Totales': {'ImpRetenidos': [{'BaseRet': Decimal('1000.00'),
                               'Impuesto': Code('01', 'ISR'),
                               'MontoRet': Decimal('500.00'),
                               'TipoPagoRet': 'Pago definitivo'},
                              {'BaseRet': Decimal('1000.00'),
                               'Impuesto': Code('02', 'IVA'),
                               'MontoRet': Decimal('500.00'),
                               'TipoPagoRet': 'Pago provisional'}],
             'MontoTotExent': Decimal('1000.00'),
             'MontoTotGrav': Decimal('13000.00'),
             'MontoTotOperacion': Decimal('14000.00'),
             'MontoTotRet': Decimal('3500.00')},
 'Version': '1.0'}