{'Certificado': '',
 'Complemento': {'CFDIRegistroFiscal': {'Folio': '2107200000004798',
                                        'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('60106400', 'Equipo de enseñanza de electrónica y suministros'),
                'ClaveUnidad': Code('H87', 'Pieza'),
                'Descripcion': 'MALLA PARA DESOLDAR',
                'Importe': Decimal('24.13'),
                'Impuestos': {'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('24.13'),
                                                                  'Importe': Decimal('3.86'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('0.160000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'ValorUnitario': Decimal('24.13')},
               {'Cantidad': Decimal('4'),
                'ClaveProdServ': Code('60106400', 'Equipo de enseñanza de electrónica y suministros'),
                'ClaveUnidad': Code('H87', 'Pieza'),
                'Descripcion': 'ARDUINO PRO MICRO ATMEGA32U4',
                'Importe': Decimal('786.20'),
                'Impuestos': {'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('786.20'),
                                                                  'Importe': Decimal('125.79'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('0.160000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'ValorUnitario': Decimal('196.55')}],
 'Emisor': {'Nombre': 'ARMY JAN LEOL TOMAS',
            'RegimenFiscal': Code('612', 'Personas Físicas con Actividades Empresariales y Profesionales'),
            'Rfc': 'ABC123456ABC'},
 'Fecha': datetime.datetime(2021, 7, 10, 14, 23, 5),
 'FormaPago': Code('28', 'Tarjeta de débito'),
 'Impuestos': {'TotalImpuestosTrasladados': Decimal('129.65'),
               'Traslados': {'002|Tasa|0.160000': {'Importe': Decimal('129.65'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('0.160000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'LugarExpedicion': '72420',
 'MetodoPago': Code('PUE', 'Pago en una sola exhibición'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '00001000000123456789',
 'Receptor': {'Nombre': 'DESARROLLOS',
              'Rfc': 'DES123456ABC',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': '',
 'SubTotal': Decimal('810.33'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('939.98'),
 'Version': '3.3'}