{'Anio': 2057,
 'Certificado': 'Certificado0',
 'Ctas': [{'CodAgrup': Code('000', 'Código para uso exclusivo de contribuyentes del sector financiero'),
           'Desc': 'Desc0',
           'Natur': 'A',
           'Nivel': 50,
           'NumCta': 'NumCta0',
           'SubCtaDe': 'SubCtaDe0'},
          {'CodAgrup': Code('000', 'Código para uso exclusivo de contribuyentes del sector financiero'),
           'Desc': 'Desc1',
           'Natur': 'A',
           'Nivel': 50,
           'NumCta': 'NumCta1',
           'SubCtaDe': 'SubCtaDe1'}],
 'Mes': '01',
 'NoCertificado': 'noCertificado1111111',
 'RFC': '&&&000000000',
 'Sello': 'Sello0',
 'Version': '1.1'}