{'Anio': 2057,
 'Certificado': 'Certificado0',
 'Mes': '01',
 'NoCertificado': 'noCertificado1111111',
 'NumOrden': 'AAA0000000/00',
 'NumTramite': '0000000000',
 'Poliza': [{'Concepto': 'Concepto0',
             'Fecha': datetime.date(2006, 5, 4),
             'NumUnIdenPol': 'NumUnIdenPol0',
             'Transaccion': [{'Cheque': [{'BanEmisExt': 'BanEmisExt0',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef0',
                                          'CtaOri': 'CtaOri0',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num0',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')},
                                         {'BanEmisExt': 'BanEmisExt1',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef1',
                                          'CtaOri': 'CtaOri1',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num1',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')}],
                              'CompExt': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt0',
                                           'TaxID': 'TaxID0',
                                           'TipCamb': Decimal('50.00000')},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt1',
                                           'TaxID': 'TaxID1',
                                           'TipCamb': Decimal('50.00000')}],
                              'CompNal': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'}],
                              'CompNalOtr': [{'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')},
                                             {'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')}],
                              'Concepto': 'Concepto1',
                              'Debe': Decimal('-1073741773.00'),
                              'DesCta': 'DesCta0',
                              'Haber': Decimal('-1073741773.00'),
                              'NumCta': 'NumCta0',
                              'OtrMetodoPago': [{'Benef': 'Benef4',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'Benef': 'Benef5',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}],
                              'Transferencia': [{'BancoDestExt': 'BancoDestExt0',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt0',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef2',
                                                 'CtaDest': 'CtaDest0',
                                                 'CtaOri': 'CtaOri2',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'BancoDestExt': 'BancoDestExt1',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt1',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef3',
                                                 'CtaDest': 'CtaDest1',
                                                 'CtaOri': 'CtaOri3',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}]},
                             {'Cheque': [{'BanEmisExt': 'BanEmisExt2',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef6',
                                          'CtaOri': 'CtaOri4',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num2',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')},
                                         {'BanEmisExt': 'BanEmisExt3',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef7',
                                          'CtaOri': 'CtaOri5',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num3',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')}],
                              'CompExt': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt2',
                                           'TaxID': 'TaxID2',
                                           'TipCamb': Decimal('50.00000')},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt3',
                                           'TaxID': 'TaxID3',
                                           'TipCamb': Decimal('50.00000')}],
                              'CompNal': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'}],
                              'CompNalOtr': [{'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')},
                                             {'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')}],
                              'Concepto': 'Concepto2',
                              'Debe': Decimal('-1073741773.00'),
                              'DesCta': 'DesCta1',
                              'Haber': Decimal('-1073741773.00'),
                              'NumCta': 'NumCta1',
                              'OtrMetodoPago': [{'Benef': 'Benef10',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'Benef': 'Benef11',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}],
                              'Transferencia': [{'BancoDestExt': 'BancoDestExt2',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt2',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef8',
                                                 'CtaDest': 'CtaDest2',
                                                 'CtaOri': 'CtaOri6',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'BancoDestExt': 'BancoDestExt3',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt3',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef9',
                                                 'CtaDest': 'CtaDest3',
                                                 'CtaOri': 'CtaOri7',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}]}]},
            {'Concepto': 'Concepto3',
             'Fecha': datetime.date(2006, 5, 4),
             'NumUnIdenPol': 'NumUnIdenPol1',
             'Transaccion': [{'Cheque': [{'BanEmisExt': 'BanEmisExt4',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef12',
                                          'CtaOri': 'CtaOri8',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num4',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')},
                                         {'BanEmisExt': 'BanEmisExt5',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef13',
                                          'CtaOri': 'CtaOri9',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num5',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')}],
                              'CompExt': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt4',
                                           'TaxID': 'TaxID4',
                                           'TipCamb': Decimal('50.00000')},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt5',
                                           'TaxID': 'TaxID5',
                                           'TipCamb': Decimal('50.00000')}],
                              'CompNal': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'}],
                              'CompNalOtr': [{'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')},
                                             {'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')}],
                              'Concepto': 'Concepto4',
                              'Debe': Decimal('-1073741773.00'),
                              'DesCta': 'DesCta2',
                              'Haber': Decimal('-1073741773.00'),
                              'NumCta': 'NumCta2',
                              'OtrMetodoPago': [{'Benef': 'Benef16',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'Benef': 'Benef17',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}],
                              'Transferencia': [{'BancoDestExt': 'BancoDestExt4',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt4',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef14',
                                                 'CtaDest': 'CtaDest4',
                                                 'CtaOri': 'CtaOri10',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'BancoDestExt': 'BancoDestExt5',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt5',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef15',
                                                 'CtaDest': 'CtaDest5',
                                                 'CtaOri': 'CtaOri11',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}]},
                             {'Cheque': [{'BanEmisExt': 'BanEmisExt6',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef18',
                                          'CtaOri': 'CtaOri12',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num6',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')},
                                         {'BanEmisExt': 'BanEmisExt7',
                                          'BanEmisNal': Code('002', 'BANAMEX'),
                                          'Benef': 'Benef19',
                                          'CtaOri': 'CtaOri13',
                                          'Fecha': datetime.date(2006, 5, 4),
                                          'Moneda': Code('AED', 'Dirham de EAU'),
                                          'Monto': Decimal('-1073741773.00'),
                                          'Num': 'Num7',
                                          'RFC': '&&&000000000',
                                          'TipCamb': Decimal('50.00000')}],
                              'CompExt': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt6',
                                           'TaxID': 'TaxID6',
                                           'TipCamb': Decimal('50.00000')},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'NumFactExt': 'NumFactExt7',
                                           'TaxID': 'TaxID7',
                                           'TipCamb': Decimal('50.00000')}],
                              'CompNal': [{'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'},
                                          {'Moneda': Code('AED', 'Dirham de EAU'),
                                           'MontoTotal': Decimal('-1073741773.00'),
                                           'RFC': '&&&000000000',
                                           'TipCamb': Decimal('50.00000'),
                                           'UUID_CFDI': '00000000-0000-0000-0000-000000000000'}],
                              'CompNalOtr': [{'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')},
                                             {'CFD_CBB_NumFol': 50,
                                              'CFD_CBB_Serie': 'A',
                                              'Moneda': Code('AED', 'Dirham de EAU'),
                                              'MontoTotal': Decimal('-1073741773.00'),
                                              'RFC': '&&&000000000',
                                              'TipCamb': Decimal('50.00000')}],
                              'Concepto': 'Concepto5',
                              'Debe': Decimal('-1073741773.00'),
                              'DesCta': 'DesCta3',
                              'Haber': Decimal('-1073741773.00'),
                              'NumCta': 'NumCta3',
                              'OtrMetodoPago': [{'Benef': 'Benef22',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'Benef': 'Benef23',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'MetPagoPol': Code('01', 'Efectivo'),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}],
                              'Transferencia': [{'BancoDestExt': 'BancoDestExt6',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt6',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef20',
                                                 'CtaDest': 'CtaDest6',
                                                 'CtaOri': 'CtaOri14',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')},
                                                {'BancoDestExt': 'BancoDestExt7',
                                                 'BancoDestNal': Code('002', 'BANAMEX'),
                                                 'BancoOriExt': 'BancoOriExt7',
                                                 'BancoOriNal': Code('002', 'BANAMEX'),
                                                 'Benef': 'Benef21',
                                                 'CtaDest': 'CtaDest7',
                                                 'CtaOri': 'CtaOri15',
                                                 'Fecha': datetime.date(2006, 5, 4),
                                                 'Moneda': Code('AED', 'Dirham de EAU'),
                                                 'Monto': Decimal('-1073741773.00'),
                                                 'RFC': '&&&000000000',
                                                 'TipCamb': Decimal('50.00000')}]}]}],
 'RFC': '&&&000000000',
 'Sello': 'Sello0',
 'TipoSolicitud': 'AF',
 'Version': '1.1'}