{'Certificado': '',
 'Complemento': {'ComercioExterior': {'CertificadoOrigen': 1,
                                      'ClaveDePedimento': Code('A1', 'IMPORTACION O EXPORTACION DEFINITIVA'),
                                      'Destinatario': [{'Domicilio': [{'Calle': 'c3',
                                                                       'CodigoPostal': '64290',
                                                                       'Colonia': '0202',
                                                                       'Estado': 'BCN',
                                                                       'Localidad': '07',
                                                                       'Municipio': '039',
                                                                       'NumeroExterior': '3A',
                                                                       'NumeroInterior': '101',
                                                                       'Pais': Code('ZZZ', 'Países no declarados'),
                                                                       'Referencia': 'rd'}],
                                                        'Nombre': 'Nombre',
                                                        'NumRegIdTrib': '654321'}],
                                      'Emisor': {'Curp': 'PEPJ800101HDFBCDQ8',
                                                 'Domicilio': {'Calle': 'c',
                                                               'CodigoPostal': '99980',
                                                               'Colonia': Code('0750', 'Moyahua Centro'),
                                                               'Estado': Code('ZAC', 'Zacatecas'),
                                                               'Localidad': Code('15', 'Moyahua de Estrada'),
                                                               'Municipio': Code('033', 'Moyahua de Estrada'),
                                                               'NumeroExterior': '123X',
                                                               'NumeroInterior': '12A',
                                                               'Pais': Code('ZZZ', 'Países no declarados'),
                                                               'Referencia': 'r'}},
                                      'Incoterm': Code('FOB', 'FRANCO A BORDO (PUERTO DE CARGA CONVENIDO)'),
                                      'Mercancias': [{'CantidadAduana': Decimal('0.001'),
                                                      'DescripcionesEspecificas': [{'Marca': 'Marca',
                                                                                    'Modelo': 'Modelo',
                                                                                    'NumeroSerie': 'NumeroSerie',
                                                                                    'SubModelo': 'SubModelo'}],
                                                      'FraccionArancelaria': Code('99999999', 'Códigos arancelarios no catalogados en la tarifa'),
                                                      'NoIdentificacion': 'n100',
                                                      'UnidadAduana': Code('99', 'SERVICIO'),
                                                      'ValorDolares': Decimal('123.45'),
                                                      'ValorUnitarioAduana': Decimal('234.56')},
                                                     {'CantidadAduana': Decimal('0.001'),
                                                      'DescripcionesEspecificas': [{'Marca': 'Marca',
                                                                                    'Modelo': 'Modelo',
                                                                                    'NumeroSerie': 'NumeroSerie',
                                                                                    'SubModelo': 'SubModelo'}],
                                                      'FraccionArancelaria': Code('99999999', 'Códigos arancelarios no catalogados en la tarifa'),
                                                      'NoIdentificacion': 'n101',
                                                      'UnidadAduana': Code('99', 'SERVICIO'),
                                                      'ValorDolares': Decimal('123.45'),
                                                      'ValorUnitarioAduana': Decimal('234.56')}],
                                      'MotivoTraslado': Code('99', 'Otros'),
                                      'NumCertificadoOrigen': 'DEADBEEF-CAFE-BABE-1234-DECADE012345',
                                      'NumeroExportadorConfiable': '1',
                                      'Observaciones': 'obs',
                                      'Propietario': [{'NumRegIdTrib': '1234567',
                                                       'ResidenciaFiscal': Code('ZZZ', 'Países no declarados')}],
                                      'Receptor': {'Domicilio': {'Calle': 'c',
                                                                 'CodigoPostal': '64280',
                                                                 'Colonia': '0197',
                                                                 'Estado': 'NLE',
                                                                 'Localidad': '07',
                                                                 'Municipio': '039',
                                                                 'NumeroExterior': '2',
                                                                 'NumeroInterior': '99',
                                                                 'Pais': Code('ZZZ', 'Países no declarados'),
                                                                 'Referencia': 'r1'},
                                                   'NumRegIdTrib': '234567890'},
                                      'Subdivision': 1,
                                      'TipoCambioUSD': Decimal('234.5678'),
                                      'TipoOperacion': Code('2', 'Exportación'),
                                      'TotalUSD': Decimal('123.45'),
                                      'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'ValorUnitario': Decimal('1500000')}],
 'Emisor': {'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 5, 1, 1, 23, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'Impuestos': {},
 'LugarExpedicion': '45079',
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': '',
 'SubTotal': Decimal('1000'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('1500'),
 'Version': '3.3'}