{'Certificado': '',
 'CfdiRelacionados': {'CfdiRelacionado': ['ED1752FE-E865-4FF2-BFE1-0F552E770DC9'],
                      'TipoRelacion': Code('02', 'Nota de débito de los documentos relacionados')},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'CuentaPredial': '51888',
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2250000'),
                                                                    'Importe': Decimal('247500'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2250000'),
                                                                  'Importe': Decimal('360000'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00001',
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500000')},
               {'Cantidad': Decimal('1.6'),
                'ClaveProdServ': Code('95141904', 'Unidades quirúrgicas'),
                'ClaveUnidad': Code('WEE', 'Semana'),
                'Descripcion': 'ALUMINIO',
                'Importe': Decimal('2400'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2400'),
                                                                    'Importe': Decimal('264'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2400'),
                                                                  'Importe': Decimal('384'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'InformacionAduanera': ['15  48  4567  6001234'],
                'NoIdentificacion': '00002',
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500')},
               {'Cantidad': Decimal('1.7'),
                'ClaveProdServ': Code('84101604', 'Ayuda gubernamental'),
                'ClaveUnidad': Code('G66', 'Litro por hora kelvin'),
                'Descripcion': 'ZAMAC',
                'Descuento': Decimal('0'),
                'Importe': Decimal('17000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('17000'),
                                                                    'Importe': Decimal('1870'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('17000'),
                                                                  'Importe': Decimal('2720'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00003',
                'Parte': [{'Cantidad': Decimal('1.0'),
                           'ClaveProdServ': Code('25201513', 'Cúpulas protectoras de la antena de avión'),
                           'Descripcion': 'PARTE EJEMPLO',
                           'Importe': Decimal('1.00'),
                           'InformacionAduanera': ['15  48  4567  6001235'],
                           'NoIdentificacion': '055155',
                           'Unidad': 'UNIDAD',
                           'ValorUnitario': Decimal('1.00')}],
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('10000')},
               {'Cantidad': Decimal('1.00'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('Q24', 'Reciprocidad de Pulgada'),
                'CuentaPredial': '51888',
                'Descripcion': 'SOME MERCHANDISE',
                'Importe': Decimal('33.00'),
                'Impuestos': {'Traslados': {'002|Exento': {'Base': Decimal('33.00'),
                                                           'Impuesto': Code('002', 'IVA'),
                                                           'TipoFactor': Code('Exento', None)}}},
                'NoIdentificacion': '6201',
                'Unidad': 'PIEZA',
                'ValorUnitario': Decimal('33.00')},
               {'Cantidad': Decimal('10'),
                'ClaveProdServ': Code('54101500', 'Joyería fina'),
                'ClaveUnidad': Code('APZ', 'Onza troy u onza farmacéutica'),
                'ComplementoConcepto': {'instEducativas': {'AutRVOE': '1234',
                                                           'CURP': 'JUAN010101MAZBCÑ90',
                                                           'NivelEducativo': 'Preescolar',
                                                           'NombreAlumno': 'Juanito '
                                                                           'Pérez '
                                                                           'Niño',
                                                           'RfcPago': 'ABC010101AAA',
                                                           'Version': '1.0'}},
                'Descripcion': 'Lapiz Berol del No. 2',
                'Importe': Decimal('1234.50'),
                'ValorUnitario': Decimal('123.45')}],
 'CondicionesDePago': 'CONDICIONES',
 'Confirmacion': 'Az123',
 'Descuento': Decimal('0.00'),
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 5, 20, 23, 23, 59),
 'Folio': '123ABC',
 'FormaPago': Code('02', 'Cheque nominativo'),
 'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('247000'),
                                       'Impuesto': Code('001', 'ISR')},
                               '003': {'Importe': Decimal('500'),
                                       'Impuesto': Code('003', 'IEPS')}},
               'TotalImpuestosRetenidos': Decimal('247500'),
               'TotalImpuestosTrasladados': Decimal('360000'),
               'Traslados': {'002|Tasa|1.600000': {'Importe': Decimal('360000'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('1.600000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'LugarExpedicion': Code('45079', None),
 'MetodoPago': Code('PUE', 'Pago en una sola exhibición'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Nombre': 'Juanito Bananas De la Sierra',
              'NumRegIdTrib': '987654321',
              'ResidenciaFiscal': Code('MEX', 'México'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': '',
 'Serie': 'A',
 'SubTotal': Decimal('1000'),
 'TipoCambio': Decimal('1.0'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('1500'),
 'Version': '3.3'}