{'Certificado': 'MIIF6zCCA9OgAwIBAgIUMjAwMDEwMDAwMDAzMDAwMDU2OTIwDQYJKoZIhvcNAQELBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNDExMjUwMDM3MjlaFw0xODExMjUwMDM3MjlaMIHXMScwJQYDVQQDFB5BTExJQU5DRSBFTVBF0U9TIFMgREUgUkwgREUgQ1YxJzAlBgNVBCkUHkFMTElBTkNFIEVNUEXRT1MgUyBERSBSTCBERSBDVjEnMCUGA1UEChQeQUxMSUFOQ0UgRU1QRdFPUyBTIERFIFJMIERFIENWMSUwIwYDVQQtExxBQ081NjA1MThLVzcgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGTlNSMDgxEzARBgNVBAsTClN1Y3Vyc2FsIDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6Rh93b3u9Av4e2WU8x28p2jRNcqSL2lcpQBw+95IBf0QdQn3y5Ghx2m/RhYwEOod9gUS7ER2E/+Rea5y0YItrcuPY0tWsql2ofER24luXBWxiD3+wjXbmoBSdmC+L/2/ZOl3m8Wk6iLxRIzTwDAGyQZup3LwVPC1zmWWVFM+d6TfGW4Ffe8sfR3XFRZusJQpO7JFDZUzCs/uFplVgtr1L2sYquhpwX4efUHpBFPYBIkXpUJMX3X5dAJyakEIJjw8mL3f5vyUkegHHngAO0ytbHayJ5eBApbRr7KYRQZbiSCn2UTtB9H5hSWN55iBwnCp4sPgD0PzcTzFAsyb+G4t9AgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQCudqGjViZmgXKYh3JB2BSHy2/tPm1O5xrqWKe8IFzTIZKhDSfMBdmaF58MxfIpt2ccy3NDcr46n5ksnA4efkeNiZcR4U9W9dy19TjfHdZ4h8U/1jpk1DRb9AQO7/B7WCQL3ZY5yiRSJj+e4JG0SqrtPUgmMQIG6XNQUecAkDvqVEdPuovmvoQetKzFzJVt+KboaT3V5Wpmi56ojjupDnSM6ENqTmRrWSzizjVSTIYdLAu1d5k20MufxRd8IHP8VZED4BFvqeXJZkfaep/er0o7KzZZrcSCGCKtW1w8lMr9dX4fCDmcxNB4M22SqX0fx1IMvAGts2c6CXFFGe245wR1YqCvzAfyXTt/dYwh5kqWPjEm+PRUWD1woxkrpgn2P3Iv9BHXAlIvT+O943t6JQ9XBDlp1U/RNXDxvA/uWomCOUOrIkNsg4oQnxkc2geRtju5qkYhr7MEg8tyKYTNGqxNHJ+mOC4D3C0lC4lFerdnwEHrKk4+Pq0h9/f5AbFC73Crz4Vx7QjPvX6MjVcGvlfka+ov4zdtIc83/dPij3CSTUv9OCDrnfnaHlz8yQcF94dAOeW7ykYuimbZ6Hdi7JsnFMVHfDeDt9jDgQBBzoAdaJUxoYOA809sI1eZJR4kHEonlaiCGFqV6HpS6EtBVtfXft6j4DpLXQBqu8bIgYoSZA==',
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2017, 11, 24, 15, 27, 34),
                                         'NoCertificadoSAT': '20001000000300022323',
                                         'RfcProvCertif': '',
                                         'SelloCFD': 'qySB1JfC1da540KY1tB9OJf0TG7wfZrxHBz1X8j/J2ReJANu/up2c2bcaY01JgUKjltz7Ku7rBUx2mTEDXRIcGI4XqqhkakOq6rT06xOUUiD9QOoxf0gEdxypMpZ7OSgOZE03UtLApxkIrqLaQxxPXoG0I8trsjmBc/byYR+epEBuwqiHFdt1sOuc6QAO/qPTj0rXxIpyXFeB1LVoK45+oVeoZPBQBqWr2MstYRMiFVsw2bR8w4+PTI6aegXKd826eJx6+Ll7FF4EN47unl4H2wlDgAd+OBH9ZKSidp3EmjrPPqiA2FjmX+2QiClWNxvUZSQmS7EH+4PxWf+PbyW/g==',
                                         'SelloSAT': 'p207sZZ4snpsJO4VqyeKBFCqsxz58vxSo0mkzcbWTbfZuuK4uOe0hPcxTAiE0x3eeKFhjW4FBkVrWadf22kMg4z3Umf3UQHDNO+chbmGljGhM/xOj2iCKCRjnyht3EkUrzRuLK1ms6L1ozx0vZcc7MX7I7COJYxV7vqMJgfKiWdTjblfra2aY24HaXd4HMy1HFeS5KYzOi9SrYBNG/3FeB3ODThjQoFHxxggVVqfTv8cJDwigyRwyoOVcJGhdXmJVKLE8MW78m3jPZBczQRPJkN2FHMbmC30ssSPNcNp+ytDklGHEdD3wq6jQiOTaZ1Ja0hfrU2lFaLtISuf99TdVQ==',
                                         'UUID': '1FBA4626-947B-49AC-BCD4-A4AF266B3DBF',
                                         'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1.000'),
                'ClaveProdServ': Code('47111603', 'Máquinas de vapor para planchar'),
                'ClaveUnidad': Code('H87', 'Pieza'),
                'Descripcion': 'PRODUCTO TASA EXENTA DE I.V.A.ÑS',
                'Importe': Decimal('100.00'),
                'Impuestos': {'Traslados': {'002|Exento': {'Base': Decimal('100.00'),
                                                           'Impuesto': Code('002', 'IVA'),
                                                           'TipoFactor': Code('Exento', None)}}},
                'NoIdentificacion': '6950',
                'Unidad': 'PIEZA',
                'ValorUnitario': Decimal('100.00')},
               {'Cantidad': Decimal('1.000'),
                'ClaveProdServ': Code('47111603', 'Máquinas de vapor para planchar'),
                'ClaveUnidad': Code('H87', 'Pieza'),
                'Descripcion': 'PRODUCTO TASA 0% DE I.V.A.ÑS',
                'Importe': Decimal('100.00'),
                'Impuestos': {'Traslados': {'002|Tasa|0.000000': {'Base': Decimal('100.00'),
                                                                  'Importe': Decimal('0.00'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('0.000000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '6947',
                'Unidad': 'PIEZA',
                'ValorUnitario': Decimal('100.00')},
               {'Cantidad': Decimal('1.000'),
                'ClaveProdServ': Code('47111603', 'Máquinas de vapor para planchar'),
                'ClaveUnidad': Code('H87', 'Pieza'),
                'Descripcion': 'PRODUCTO TASA 16% DE I.V.A.ÑS',
                'Importe': Decimal('86.21'),
                'Impuestos': {'Traslados': {'002|Tasa|0.160000': {'Base': Decimal('86.21'),
                                                                  'Importe': Decimal('13.79'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('0.160000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '6946',
                'Unidad': 'PIEZA',
                'ValorUnitario': Decimal('86.21')}],
 'Descuento': Decimal('0.00'),
 'Emisor': {'Nombre': 'DESARROLLOS MAPASAC & MAPASOFT IT SYSTEMS',
            'RegimenFiscal': Code('601', 'General de Ley Personas Morales'),
            'Rfc': 'ACO560518KW7'},
 'Fecha': datetime.datetime(2017, 11, 24, 15, 19, 24),
 'Folio': '999175',
 'FormaPago': Code('03', 'Transferencia electrónica de fondos'),
 'Impuestos': {'TotalImpuestosRetenidos': Decimal('0.00'),
               'TotalImpuestosTrasladados': Decimal('13.79'),
               'Traslados': {'002|Tasa|0.160000': {'Importe': Decimal('13.79'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('0.160000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'LugarExpedicion': '66050',
 'MetodoPago': Code('PPD', 'Pago en parcialidades o diferido'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '20001000000300005692',
 'Receptor': {'Nombre': 'MARTIN PAREDES DOMINGUEZ',
              'Rfc': 'MEBS780711118',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': 'qySB1JfC1da540KY1tB9OJf0TG7wfZrxHBz1X8j/J2ReJANu/up2c2bcaY01JgUKjltz7Ku7rBUx2mTEDXRIcGI4XqqhkakOq6rT06xOUUiD9QOoxf0gEdxypMpZ7OSgOZE03UtLApxkIrqLaQxxPXoG0I8trsjmBc/byYR+epEBuwqiHFdt1sOuc6QAO/qPTj0rXxIpyXFeB1LVoK45+oVeoZPBQBqWr2MstYRMiFVsw2bR8w4+PTI6aegXKd826eJx6+Ll7FF4EN47unl4H2wlDgAd+OBH9ZKSidp3EmjrPPqiA2FjmX+2QiClWNxvUZSQmS7EH+4PxWf+PbyW/g==',
 'Serie': 'A',
 'SubTotal': Decimal('286.21'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('300.00'),
 'Version': '3.3'}