{'Certificado': 'MIIE/DCCA+SgAwIBAgIUNDAwMDEwMDAwMDAzMDAwMDAzMzcwDQYJKoZIhvcNAQELBQAwggFcMRowGAYDVQQDDBFBLkMuIDEgZGUgcHJ1ZWJhczEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMTQwMgYJKoZIhvcNAQkCDCVSZXNwb25zYWJsZTogQXJhY2VsaSBHYW5kYXJhIEJhdXRpc3RhMB4XDTEyMTAyMzIxNTIxOVoXDTE2MTAyMzIxMDcyM1owgcAxHDAaBgNVBAMTE0FEQU4gTUVORE9aQSBHQVJDSUExHDAaBgNVBCkTE0FEQU4gTUVORE9aQSBHQVJDSUExHDAaBgNVBAoTE0FEQU4gTUVORE9aQSBHQVJDSUExCzAJBgNVBAYTAk1YMSIwIAYJKoZIhvcNAQkBFhNlbGNvcnJlb0Bjb3JyZW8uY29tMRYwFAYDVQQtEw1HQU1BNjAwNTA0SlAxMRswGQYDVQQFExJHQU1BNjAwNTA0TURGQ1lMMDAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCGV/eru7/6lMhfNhuAGwhK9XJGKHV6IrHjd/Xi+sFLGBNkI2u113taTt6biRvJrWPOW04DOeKUf5Es9BZUhIRfr3WGiUc8a3I++7AqJXmpiVGVhfjyqPPJcoaapI88XA07EkvnsH+dpLRUJRYaM8DoqmWmIX7ZzxqpbARUDKz0XR/ccK0wtDeYC0/+yybVT6ukuc38O6MJjQm0Y71OgB0q+rkt5i3bqLnn0zYAQw/0KmgDeRrGehm/8GxOknNY9mZGH8fmqkItR9VqSZ6n8bLDQsjUS35Gykz06FsyrNT72lmfdF93ID+BLD2pfBf4oCyA+mlMF/i2+oBzhCxEkMRZAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggEBADgxGayoWzGAOefPaH0Qj00uAbrggrwprNEWigVNl90xdGIzmMZG6cbfJIYjMcssOX64S8MhaQEk0hMUpIId8jmi9MYOrsp4sJTxxsvOPdWyUMXblkgUYMdFHJlC3HKfmQjdgkGZopS+eU9/z0RpW1tLCS6ScF17C9plagIgZ24X948fNPoSNBb7ZhsUX1/lyejR+Nuq3z9rQXtD1zIQExFZWRxR/WKvqNCLY7NSdRGDbdtKJyAHyhbIXMFuI+nkvZ8EdZB8hIOv6T7ML0TLnDWcT8NKhtAG5qzq70L1E1ruv62oOrwMEu2EXyxXm7wbw3NRjQ/hShEBWWMw2WR/p0Q=',
 'CfdiRelacionados': {'CfdiRelacionado': ['ED1752FE-E865-4FF2-BFE1-0F552E770DC9'],
                      'TipoRelacion': Code('02', 'Nota de débito de los documentos relacionados')},
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2017, 5, 10, 15, 22, 28),
                                         'NoCertificadoSAT': '20001000000100005761',
                                         'RfcProvCertif': 'AAA010101AAA',
                                         'SelloCFD': 'KsM7MmEbGNBW90sP7QnrqJwt/gJVithjKP9+Vmnm3wLZUl6nG4skH/o1H5M8z7vM7jbuam2fB8C1+DYx927r4p9vbarTY0HAHe4F63WiEQPCSV5dLz1RWCteLhF2Z6mir1DJTGlSHJ9bpHVjyEvuI/X+4a5TcgcFUfxDbAvHr9L+BwfYUKGnok8qFgucswOBUcAJZQvTfO14ZrXFv3noMSU55po05xhhiWy+jAjjF9N2q5eIgI5YyRH1fjdrpjWNoBIO5B/sfNJW/YD0HYkyDOWR1gnzJNJd/S5TiGlAHpsNGtONCQYsAi+ou0rb5IJhfIOzO2pAfz7rI7Lsp9KLtA==',
                                         'SelloSAT': 'etZ7vYz5xSa9q/nFCbFr1m09De27xWNJha+KpVoBhCtQwu4M9fPE6t9MvuiwGRRi+Oe9xsQcQoYK21IL80ALxPA2+8u8CU25IV98KTEEgcbGhEl4m9kq8q0kZhdudu8VeUKhwBl7QFftP0TftJVBQs112a/yJLFIe6ONtVow9hU=',
                                         'UUID': 'ea8152af-b116-4812-817a-3b4f9617c99c',
                                         'Version': '1.1'}},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'CuentaPredial': '51888',
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2250000'),
                                                                    'Importe': Decimal('247500'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2250000'),
                                                                  'Importe': Decimal('360000'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00001',
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500000')},
               {'Cantidad': Decimal('1.6'),
                'ClaveProdServ': Code('95141904', 'Unidades quirúrgicas'),
                'ClaveUnidad': Code('WEE', 'Semana'),
                'Descripcion': 'ALUMINIO',
                'Importe': Decimal('2400'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('2400'),
                                                                    'Importe': Decimal('264'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('2400'),
                                                                  'Importe': Decimal('384'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'InformacionAduanera': ['15  48  4567  6001234'],
                'NoIdentificacion': '00002',
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('1500')},
               {'Cantidad': Decimal('1.7'),
                'ClaveProdServ': Code('84101604', 'Ayuda gubernamental'),
                'ClaveUnidad': Code('G66', 'Litro por hora kelvin'),
                'Descripcion': 'ZAMAC',
                'Descuento': Decimal('0'),
                'Importe': Decimal('17000'),
                'Impuestos': {'Retenciones': {'001|Tasa|0.300000': {'Base': Decimal('17000'),
                                                                    'Importe': Decimal('1870'),
                                                                    'Impuesto': Code('001', 'ISR'),
                                                                    'TasaOCuota': Decimal('0.300000'),
                                                                    'TipoFactor': Code('Tasa', None)}},
                              'Traslados': {'002|Tasa|1.600000': {'Base': Decimal('17000'),
                                                                  'Importe': Decimal('2720'),
                                                                  'Impuesto': Code('002', 'IVA'),
                                                                  'TasaOCuota': Decimal('1.600000'),
                                                                  'TipoFactor': Code('Tasa', None)}}},
                'NoIdentificacion': '00003',
                'Parte': [{'Cantidad': Decimal('1.0'),
                           'ClaveProdServ': Code('25201513', 'Cúpulas protectoras de la antena de avión'),
                           'Descripcion': 'PARTE EJEMPLO',
                           'Importe': Decimal('1.00'),
                           'InformacionAduanera': ['15  48  4567  6001235'],
                           'NoIdentificacion': '055155',
                           'Unidad': 'UNIDAD',
                           'ValorUnitario': Decimal('1.00')}],
                'Unidad': 'TONELADA',
                'ValorUnitario': Decimal('10000')}],
 'CondicionesDePago': 'CONDICIONES',
 'Confirmacion': 'Az123',
 'Descuento': Decimal('0.00'),
 'Emisor': {'Nombre': 'Esta es una demostración',
            'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 5, 1, 1, 23, 59),
 'Folio': '123ABC',
 'FormaPago': Code('02', 'Cheque nominativo'),
 'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('247000'),
                                       'Impuesto': Code('001', 'ISR')},
                               '003': {'Importe': Decimal('500'),
                                       'Impuesto': Code('003', 'IEPS')}},
               'TotalImpuestosRetenidos': Decimal('247500'),
               'TotalImpuestosTrasladados': Decimal('360000'),
               'Traslados': {'002|Tasa|1.600000': {'Importe': Decimal('360000'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('1.600000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'LugarExpedicion': Code('45079', None),
 'MetodoPago': Code('PUE', 'Pago en una sola exhibición'),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Nombre': 'Juanito Bananas De la Sierra',
              'NumRegIdTrib': '987654321',
              'ResidenciaFiscal': Code('MEX', 'México'),
              'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': 'KsM7MmEbGNBW90sP7QnrqJwt/gJVithjKP9+Vmnm3wLZUl6nG4skH/o1H5M8z7vM7jbuam2fB8C1+DYx927r4p9vbarTY0HAHe4F63WiEQPCSV5dLz1RWCteLhF2Z6mir1DJTGlSHJ9bpHVjyEvuI/X+4a5TcgcFUfxDbAvHr9L+BwfYUKGnok8qFgucswOBUcAJZQvTfO14ZrXFv3noMSU55po05xhhiWy+jAjjF9N2q5eIgI5YyRH1fjdrpjWNoBIO5B/sfNJW/YD0HYkyDOWR1gnzJNJd/S5TiGlAHpsNGtONCQYsAi+ou0rb5IJhfIOzO2pAfz7rI7Lsp9KLtA==',
 'Serie': 'A',
 'SubTotal': Decimal('1000'),
 'TipoCambio': Decimal('1.0'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('1500'),
 'Version': '3.3'}