{'Certificado': '',
 'Complemento': {'Pagos': {'Pago': [{'CadPago': 'CadPago',
                                     'CertPago': 'CertPago',
                                     'CtaBeneficiario': '1234567890',
                                     'CtaOrdenante': '9876543210',
                                     'DoctoRelacionado': [{'Folio': 'Folio12',
                                                           'IdDocumento': 'DEADBEEF-CAFE-BABE-1234-123456789012',
                                                           'ImpPagado': Decimal('1.234'),
                                                           'ImpSaldoAnt': Decimal('1.789'),
                                                           'ImpSaldoInsoluto': Decimal('0.456'),
                                                           'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                           'MonedaDR': Code('ZWL', 'Zimbabwe Dólar'),
                                                           'NumParcialidad': 109,
                                                           'Serie': 'Serie56',
                                                           'TipoCambioDR': Decimal('0.000001')}],
                                     'FechaPago': datetime.datetime(2017, 5, 1, 2, 1, 1),
                                     'FormaDePagoP': Code('99', 'Por definir'),
                                     'Impuestos': [{'Retenciones': {'001': {'Importe': Decimal('21.655'),
                                                                            'Impuesto': Code('001', 'ISR')},
                                                                    '003': {'Importe': Decimal('10.345'),
                                                                            'Impuesto': Code('003', 'IEPS')}},
                                                    'TotalImpuestosRetenidos': Decimal('32.00'),
                                                    'TotalImpuestosTrasladados': Decimal('21.00'),
                                                    'Traslados': {'001|Exento|0.160000': {'Importe': Decimal('0.544'),
                                                                                          'Impuesto': Code('001', 'ISR'),
                                                                                          'TasaOCuota': Decimal('0.160000'),
                                                                                          'TipoFactor': Code('Exento', None)},
                                                                  '002|Cuota|0.298800': {'Importe': Decimal('20.456'),
                                                                                         'Impuesto': Code('002', 'IVA'),
                                                                                         'TasaOCuota': Decimal('0.298800'),
                                                                                         'TipoFactor': Code('Cuota', None)}}}],
                                     'MonedaP': Code('ZWL', 'Zimbabwe Dólar'),
                                     'Monto': Decimal('10.123'),
                                     'NomBancoOrdExt': 'NOM123456',
                                     'NumOperacion': '123',
                                     'RfcEmisorCtaBen': 'AAA010101AAA',
                                     'RfcEmisorCtaOrd': 'AAA010101AAA',
                                     'SelloPago': 'DEADBEEF',
                                     'TipoCadPago': Code('01', 'SPEI'),
                                     'TipoCambioP': Decimal('0.001')}],
                           'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'ValorUnitario': Decimal('1500000')}],
 'Emisor': {'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 5, 1, 1, 23, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'Impuestos': {'Retenciones': {'001': {'Importe': Decimal('247500'),
                                       'Impuesto': Code('001', 'ISR')}},
               'TotalImpuestosRetenidos': Decimal('247500'),
               'TotalImpuestosTrasladados': Decimal('360000'),
               'Traslados': {'002|Tasa|1.600000': {'Importe': Decimal('360000'),
                                                   'Impuesto': Code('002', 'IVA'),
                                                   'TasaOCuota': Decimal('1.600000'),
                                                   'TipoFactor': Code('Tasa', None)}}},
 'LugarExpedicion': Code('45079', None),
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': '',
 'SubTotal': Decimal('1000'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('1500'),
 'Version': '3.3'}