{'Certificado': '',
 'Complemento': {'Pagos': {'Pago': [{'FechaPago': datetime.datetime(2017, 9, 13, 1, 2, 59),
                                     'FormaDePagoP': Code('02', 'Cheque nominativo'),
                                     'MonedaP': Code('ZWL', 'Zimbabwe Dólar'),
                                     'Monto': Decimal('10.12'),
                                     'TipoCambioP': Decimal('1')}],
                           'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ClaveProdServ': Code('84111506', 'Servicios de facturación'),
                'ClaveUnidad': Code('ACT', 'Actividad'),
                'Descripcion': 'Pago',
                'Importe': Decimal('0'),
                'ValorUnitario': Decimal('0')}],
 'Emisor': {'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': 'AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 9, 14, 1, 2, 3),
 'LugarExpedicion': '45079',
 'Moneda': Code('XXX', 'Los códigos asignados para las transacciones en que intervenga ninguna moneda'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Rfc': 'AAA010101AAA', 'UsoCFDI': Code('P01', 'Por definir')},
 'Sello': '',
 'SubTotal': Decimal('0'),
 'TipoDeComprobante': Code('P', 'Pago'),
 'Total': Decimal('0'),
 'Version': '3.3'}