{'Certificado': '',
 'Complemento': {'detallista': {'AdditionalInformation': [{'Type': 'ATZ',
                                                           '_text': None}],
                                'Buyer': {'ContactInformation': {'PersonOrDepartmentName': {'Text': '000'}},
                                          'Gln': '0000000000000'},
                                'ContentVersion': '1.3.1',
                                'Currency': [{'CurrencyFunction': ['BILLING_CURRENCY'],
                                              'CurrencyISOCode': 'MXN'},
                                             {'CurrencyFunction': ['PAYMENT_CURRENCY'],
                                              'CurrencyISOCode': 'USD',
                                              'RateOfChange': Decimal('1.000000')}],
                                'DocumentStatus': 'ORIGINAL',
                                'DocumentStructureVersion': 'AMC8.1',
                                'OrderIdentification': {'ReferenceIdentification': [{'Type': 'ON',
                                                                                     '_text': '\n'
                                                                                              '        '
                                                                                              '4500536101'}]},
                                'RequestForPaymentIdentification': {'EntityType': 'INVOICE'},
                                'SpecialInstruction': [{'Code': 'ZZZ',
                                                        'Text': ['Monto de la '
                                                                 'venta']}],
                                'Type': 'SimpleInvoiceType'}},
 'Conceptos': [{'Cantidad': Decimal('1.5'),
                'ClaveProdServ': Code('01010101', 'No existe en el catálogo'),
                'ClaveUnidad': Code('C81', 'Radián'),
                'Descripcion': 'ACERO',
                'Importe': Decimal('2250000'),
                'ValorUnitario': Decimal('1500000')}],
 'Emisor': {'RegimenFiscal': Code('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
            'Rfc': ' AAA010101AAA'},
 'Fecha': datetime.datetime(2017, 5, 1, 1, 23, 59),
 'FormaPago': Code('02', 'Cheque nominativo'),
 'LugarExpedicion': '45079',
 'Moneda': Code('MXN', 'Peso Mexicano'),
 'NoCertificado': '40001000000300000337',
 'Receptor': {'Rfc': 'BASJ600902KL9',
              'UsoCFDI': Code('G03', 'Gastos en general')},
 'Sello': '',
 'SubTotal': Decimal('1000'),
 'TipoDeComprobante': Code('I', 'Ingreso'),
 'Total': Decimal('1500'),
 'Version': '3.3'}