{'data': b'<s:Envelope xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xml'
         b'ns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header/><s:Body>'
         b'<des:SolicitaDescarga><des:solicitud FechaFinal="2021-01-01T00:00:00'
         b'" FechaInicial="2021-01-01T00:00:00" RfcEmisor="ABC123456ABC" RfcSol'
         b'icitante="XIQB891116QE4" TipoSolicitud="CFDI" TipoComprobante="I" Es'
         b'tadoComprobante="1"><des:RfcReceptores><des:RfcReceptor>ABC123456ABC'
         b'</des:RfcReceptor></des:RfcReceptores><ds:Signature xmlns:ds="http:/'
         b'/www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMet'
         b'hod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><ds'
         b':SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sh'
         b'a1"/><ds:Reference URI=""><ds:Transforms><ds:Transform Algorithm="ht'
         b'tp://www.w3.org/2000/09/xmldsig#enveloped-signature"/></ds:Transform'
         b's><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1'
         b'"/><ds:DigestValue>0/sBu1R2d+wzvxf+hMQ+S2KqQQE=</ds:DigestValue></ds'
         b':Reference></ds:SignedInfo><ds:SignatureValue>AKGqUpVXIz1g05W/MXN31O'
         b'i6K4GDMVI7maTUlBS8jZbeiizShXSRjmVewrEcEnwFpHLwYVK+SAlLLIwdyA0isUqLmg'
         b'BzC9cFTQnowIkOotbnZd8gqyy6geRcJgDvk3PJpI0LFBJCoC8wgzWQssy7maUmuuS7Pv'
         b'VdTCs9jaOsqtf4I4PpSz/yr1cUvF5ITpcjGIXdQp4jv0vSbrcx0KDbZ/feelBgdCphJE'
         b'gr7PkSiTVENleJHmsz+qKL4i1ZJCrspnurndqZSPNbiYdEOXfhV0lzXgs7a7Q1pGn2/Q'
         b'KdateECUIUrXc5hCyYRHPhGeuLbqJpIILz3rJ6TgnOrs8VeA==</ds:SignatureValu'
         b'e><ds:KeyInfo><ds:X509Data><ds:X509IssuerSerial><ds:X509IssuerName>u'
         b'nstructuredName=responsable: ACDMA-SAT,x500UniqueIdentifier=2.5.4.45'
         b',L=COYOACAN,ST=CIUDAD DE MEXICO,C=MX,postalCode=06370,street=3ra cer'
         b'rada de cadiz,emailAddress=oscar.martinez@sat.gob.mx,OU=SAT-IES Auth'
         b'ority,O=SERVICIO DE ADMINISTRACION TRIBUTARIA,CN=AC UAT</ds:X509Issu'
         b'erName><ds:X509SerialNumber>2922331628702060017597661984443262345740'
         b'38446385</ds:X509SerialNumber></ds:X509IssuerSerial><ds:X509Certific'
         b'ate>MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQEL'
         b'BQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlO'
         b'SVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgw'
         b'JgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQz'
         b'cmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkw'
         b'FwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UE'
         b'LRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQw'
         b'HhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5J'
         b'Q0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAc'
         b'BgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG'
         b'9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZR'
         b'RTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQAD'
         b'ggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqI'
         b'B4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY'
         b'+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlq'
         b'spnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZ'
         b'Y66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvk'
         b'NHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gw'
         b'EQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjAN'
         b'BgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXz'
         b'Z9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1E'
         b'qRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6'
         b'Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GL'
         b'pB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIz'
         b'PZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE'
         b'3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0l'
         b'ACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8'
         b'SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcR'
         b'mOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4U'
         b'WhpTivKnrqNWL7qAHLSP1tnmG8s=</ds:X509Certificate></ds:X509Data></ds:'
         b'KeyInfo></ds:Signature></des:solicitud></des:SolicitaDescarga></s:Bo'
         b'dy></s:Envelope>',
 'headers': {'Accept': 'text/xml',
             'Authorization': 'WRAP access_token="token_comprobante"',
             'Cache-Control': 'no-cache',
             'Content-type': 'text/xml;charset="utf-8"',
             'SOAPAction': 'http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescarga'},
 'url': 'https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc',
 'verify': True}