{'data': b'<s:Envelope xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xml'
         b'ns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header/><s:Body>'
         b'<des:SolicitaDescargaEmitidos><des:solicitud FechaFinal="2021-01-01T'
         b'00:00:00" FechaInicial="2021-01-01T00:00:00" RfcEmisor="ABC123456ABC'
         b'" RfcSolicitante="XIQB891116QE4" TipoSolicitud="CFDI" TipoComprobant'
         b'e="I" EstadoComprobante="1"><des:RfcReceptores><des:RfcReceptor>ABC1'
         b'23456ABC</des:RfcReceptor></des:RfcReceptores><ds:Signature xmlns:ds'
         b'="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:Canonicaliz'
         b'ationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-200103'
         b'15"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsi'
         b'g#rsa-sha1"/><ds:Reference URI=""><ds:Transforms><ds:Transform Algor'
         b'ithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></ds:T'
         b'ransforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmld'
         b'sig#sha1"/><ds:DigestValue>M1NwuSlhMi51sRAjM1CZOqYPuK4=</ds:DigestVa'
         b'lue></ds:Reference></ds:SignedInfo><ds:SignatureValue>hqDE9Z/czCEX/K'
         b'ueQ81G2MiBkvfpRFUtekxU9pozHjhJrLq2Qh26M2GZoUQ6odvS2qPaEKNhLOC1oyNLNY'
         b'n4MibuoFh6Z8QXc4lGsELtxFAlL27LJi5XKpBym0gMkfR+VcI+fLPbVJM0R2xE6BffPX'
         b'X2dcirHkePE8MTh6s+Ao29UNVmKWNUleSPnxoLIkiki6ViBF49IP2oNdQh5pugxFxhh0'
         b'iPUS8fefxgo8yW9yqIGNBmRjUh/qu63W4NBXWg0GP+l5y3aYZ/x+M8QnjvJ23fCvIatb'
         b'/3XAMGPkqQ3MBG1kfiuT7+zirDUF5IzLUZ3+APFNnUBN4MnIFlPvInzw==</ds:Signa'
         b'tureValue><ds:KeyInfo><ds:X509Data><ds:X509IssuerSerial><ds:X509Issu'
         b'erName>unstructuredName=responsable: ACDMA-SAT,x500UniqueIdentifier='
         b'2.5.4.45,L=COYOACAN,ST=CIUDAD DE MEXICO,C=MX,postalCode=06370,street'
         b'=3ra cerrada de cadiz,emailAddress=oscar.martinez@sat.gob.mx,OU=SAT-'
         b'IES Authority,O=SERVICIO DE ADMINISTRACION TRIBUTARIA,CN=AC UAT</ds:'
         b'X509IssuerName><ds:X509SerialNumber>29223316287020600175976619844432'
         b'6234574038446385</ds:X509SerialNumber></ds:X509IssuerSerial><ds:X509'
         b'Certificate>MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZI'
         b'hvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERF'
         b'IEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9y'
         b'aXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYD'
         b'VQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYT'
         b'Ak1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjER'
         b'MA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RN'
         b'QS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMV'
         b'QkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpB'
         b'REExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAj'
         b'BgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4'
         b'OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcN'
         b'AQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv'
         b'1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVU'
         b'qZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJ'
         b'eUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjj'
         b'USJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYi'
         b'sTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8E'
         b'BAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEF'
         b'BQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaF'
         b'zQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DL'
         b'HfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ'
         b'4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBV'
         b'XtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3'
         b'Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMz'
         b'u16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb'
         b'0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4'
         b'yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokS'
         b'AHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T'
         b'7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=</ds:X509Certificate></ds:X509Da'
         b'ta></ds:KeyInfo></ds:Signature></des:solicitud></des:SolicitaDescarg'
         b'aEmitidos></s:Body></s:Envelope>',
 'headers': {'Accept': 'text/xml',
             'Authorization': 'WRAP access_token="token_comprobante"',
             'Cache-Control': 'no-cache',
             'Content-type': 'text/xml;charset="utf-8"',
             'SOAPAction': 'http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescargaEmitidos'},
 'url': 'https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc',
 'verify': True}