{'data': b'<s:Envelope xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xml'
         b'ns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header/><s:Body>'
         b'<des:SolicitaDescargaEmitidos><des:solicitud FechaFinal="2021-01-01T'
         b'00:00:00" FechaInicial="2021-01-01T00:00:00" RfcEmisor="ABC123456ABC'
         b'" RfcSolicitante="XIQB891116QE4" TipoSolicitud="CFDI" TipoComprobant'
         b'e="I" EstadoComprobante="Vigente"><des:RfcReceptores><des:RfcRecepto'
         b'r>ABC123456ABC</des:RfcReceptor></des:RfcReceptores><ds:Signature xm'
         b'lns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:Canon'
         b'icalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-'
         b'20010315"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/'
         b'xmldsig#rsa-sha1"/><ds:Reference URI=""><ds:Transforms><ds:Transform'
         b' Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>'
         b'</ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/0'
         b'9/xmldsig#sha1"/><ds:DigestValue>5tIk7lQ/sABBcSmGghjvPQBuriM=</ds:Di'
         b'gestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>WSWnx4Qw'
         b'ZUfBg/dwjx5+LttzT7FCQXq89N401qJmfAbKZGzVy86Xkrqp/9n/ZRaoFigVmBiYua2c'
         b'm1AmXeRjI1inaFoIAaNrZeu37InyVpS3kqXUrHHGdtBJ5ESUIWcUfLItr1xnsNlspUa1'
         b'oBnjrp+FU8Rq0pgC9cTbV24moO2S6D66bM7T3asQfc0ZfAJBXPwelsVsamNL4ge4b0oS'
         b'h8R4Y0VVwrNR9YpIrpBFFf4gDonz1POucOBF6+oHVGWAt9iz15R6Wnyownimti3epoeO'
         b'iQc/3qJLfiSK7TCbHP6uaxl8k94zhuwK/usKDuYnecs+Cp05UIslf0AEG90X0g==</ds'
         b':SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509IssuerSerial><ds:X5'
         b'09IssuerName>unstructuredName=responsable: ACDMA-SAT,x500UniqueIdent'
         b'ifier=2.5.4.45,L=COYOACAN,ST=CIUDAD DE MEXICO,C=MX,postalCode=06370,'
         b'street=3ra cerrada de cadiz,emailAddress=oscar.martinez@sat.gob.mx,O'
         b'U=SAT-IES Authority,O=SERVICIO DE ADMINISTRACION TRIBUTARIA,CN=AC UA'
         b'T</ds:X509IssuerName><ds:X509SerialNumber>29223316287020600175976619'
         b'8444326234574038446385</ds:X509SerialNumber></ds:X509IssuerSerial><d'
         b's:X509Certificate>MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQ'
         b'YJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0'
         b'lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQX'
         b'V0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR'
         b'0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBg'
         b'NVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQU'
         b'NBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOi'
         b'BBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1'
         b'UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIF'
         b'FVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTV'
         b'gxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDV'
         b'hJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKo'
         b'ZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnw'
         b'Tap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI'
         b'0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnD'
         b'uVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUh'
         b'VlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7'
         b'tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBg'
         b'NVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBg'
         b'grBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtE'
         b'RUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3b'
         b'A8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiC'
         b'P27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6J'
         b'xUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9'
         b'ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+Cmp'
         b'KZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8'
         b'vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk35'
         b'2Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2om'
         b'hZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PK'
         b'xDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=</ds:X509Certificate></ds:'
         b'X509Data></ds:KeyInfo></ds:Signature></des:solicitud></des:SolicitaD'
         b'escargaEmitidos></s:Body></s:Envelope>',
 'headers': {'Accept': 'text/xml',
             'Authorization': 'WRAP access_token="token_comprobante"',
             'Cache-Control': 'no-cache',
             'Content-type': 'text/xml;charset="utf-8"',
             'SOAPAction': 'http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescargaEmitidos'},
 'url': 'https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc',
 'verify': True}