{'data': b'<s:Envelope xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xml'
         b'ns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header/><s:Body>'
         b'<des:SolicitaDescargaFolio><des:solicitud RfcSolicitante="XIQB891116'
         b'QE4" Folio="6114cfd0-87d2-45b8-99b1-7c19475c9cda"><ds:Signature xmln'
         b's:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:Canonic'
         b'alizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20'
         b'010315"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xm'
         b'ldsig#rsa-sha1"/><ds:Reference URI=""><ds:Transforms><ds:Transform A'
         b'lgorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></'
         b'ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/'
         b'xmldsig#sha1"/><ds:DigestValue>ARW+UvRAtgrNCpVItbIu5iCJijk=</ds:Dige'
         b'stValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>jV90YdLq/E'
         b'gkkGx8y9+a8vSwq2hUfVM/Sk/BkUK6WbCaU0qNV2OcohEDogiu7bq4bLDfL+4G5Xx1Ue'
         b'WBKRVsofkAabln+Irin33ojDPE7NVWoSs5brfYm9TBwn1kpjK2Cd91ElW8VnCAc6lSm0'
         b'8JWZ9jvR1NeHbvYd4/3wzfypzIP/GABoI+0Ud60Yw6hypFc7fH8luvDLcMhIGci1sAsc'
         b'6b2RK4o2NgADlrp6sbE8nSAm0nSIOAVwROjVB6W1zp/MBDClOFn8zJn+Xbk4Q6jNkesl'
         b'9hztV2Qxhz06xU0l94iQ/gkItSeZ79pcktS7lSclwqvoO3txu9XvrxY5dq6Q==</ds:S'
         b'ignatureValue><ds:KeyInfo><ds:X509Data><ds:X509IssuerSerial><ds:X509'
         b'IssuerName>unstructuredName=responsable: ACDMA-SAT,x500UniqueIdentif'
         b'ier=2.5.4.45,L=COYOACAN,ST=CIUDAD DE MEXICO,C=MX,postalCode=06370,st'
         b'reet=3ra cerrada de cadiz,emailAddress=oscar.martinez@sat.gob.mx,OU='
         b'SAT-IES Authority,O=SERVICIO DE ADMINISTRACION TRIBUTARIA,CN=AC UAT<'
         b'/ds:X509IssuerName><ds:X509SerialNumber>2922331628702060017597661984'
         b'44326234574038446385</ds:X509SerialNumber></ds:X509IssuerSerial><ds:'
         b'X509Certificate>MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJ'
         b'KoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lP'
         b'IERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0'
         b'aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0w'
         b'GwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNV'
         b'BAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNB'
         b'TjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBB'
         b'Q0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UE'
         b'AxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFV'
         b'RVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgx'
         b'JTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJ'
         b'UUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZI'
         b'hvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTa'
         b'p8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0G'
         b'GoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuV'
         b'p6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVl'
         b'GRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn'
         b'6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNV'
         b'HQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggr'
         b'BgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERU'
         b'XnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8'
         b'E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP2'
         b'7LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxU'
         b'nYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9Cl'
         b'ETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ'
         b'0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vG'
         b'yJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352S'
         b'qjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZ'
         b'BokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxD'
         b'e/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=</ds:X509Certificate></ds:X5'
         b'09Data></ds:KeyInfo></ds:Signature></des:solicitud></des:SolicitaDes'
         b'cargaFolio></s:Body></s:Envelope>',
 'headers': {'Accept': 'text/xml',
             'Authorization': 'WRAP access_token="token_comprobante"',
             'Cache-Control': 'no-cache',
             'Content-type': 'text/xml;charset="utf-8"',
             'SOAPAction': 'http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescargaFolio'},
 'url': 'https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc',
 'verify': True}