{'data': b'<s:Envelope xmlns:des="http://DescargaMasivaTerceros.sat.gob.mx" xml'
         b'ns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header/><s:Body>'
         b'<des:SolicitaDescarga><des:solicitud RfcSolicitante="XIQB891116QE4" '
         b'TipoSolicitud="CFDI" Folio="6114cfd0-87d2-45b8-99b1-7c19475c9cda"><d'
         b's:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:Signed'
         b'Info><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001'
         b'/REC-xml-c14n-20010315"/><ds:SignatureMethod Algorithm="http://www.w'
         b'3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI=""><ds:Transforms'
         b'><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#envelope'
         b'd-signature"/></ds:Transforms><ds:DigestMethod Algorithm="http://www'
         b'.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>iDhVJvHNmNY/BPf2bOWFE'
         b'fRF/j8=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:Signature'
         b'Value>GtEarcWrgXhosSdFmsFpupy8FNUyMG5k45S03cdQKaSeRN9p8SDlKCDDKbvDOE'
         b'8nwrzTRH2u8IPu7HxVXMLxDptF7/x9V6U/B1rFMYZbVjxDwuWiEMnXelTgRb/KA2/GL2'
         b'bKNgxdmWRl4QROgwn3awWVlGiCnP8u791B7bCxUpzpDDfUFeVMsL0CRafnsS9fwPmE79'
         b'MdliYrk4BYZtv7CINBdyplNZhkxQSbTWktQq/4lEunyzryzkFKBMfcpEJBQVpkO0aJBO'
         b'lxzelQNTTjUJOBf9OJ5+qcWTYewTiIZT6LNTnxhoLON1QTOOPEB1gy6vsQi5YURh9pTV'
         b'dJlNs5Tg==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Issue'
         b'rSerial><ds:X509IssuerName>unstructuredName=responsable: ACDMA-SAT,x'
         b'500UniqueIdentifier=2.5.4.45,L=COYOACAN,ST=CIUDAD DE MEXICO,C=MX,pos'
         b'talCode=06370,street=3ra cerrada de cadiz,emailAddress=oscar.martine'
         b'z@sat.gob.mx,OU=SAT-IES Authority,O=SERVICIO DE ADMINISTRACION TRIBU'
         b'TARIA,CN=AC UAT</ds:X509IssuerName><ds:X509SerialNumber>292233162870'
         b'206001759766198444326234574038446385</ds:X509SerialNumber></ds:X509I'
         b'ssuerSerial><ds:X509Certificate>MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0'
         b'MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNV'
         b'BAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsM'
         b'EVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBz'
         b'YXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwF'
         b'MDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYD'
         b'VQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJl'
         b'c3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQy'
         b'WjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJF'
         b'TklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTEL'
         b'MAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgx'
         b'FjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIw'
         b'NTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3'
         b'XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+Kp'
         b'tHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9a'
         b'SP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng'
         b'8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICx'
         b'FrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0T'
         b'AQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQG'
         b'CCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9Sell'
         b'L9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHK'
         b'cEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hN'
         b'T9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zo'
         b'lYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7'
         b'DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5'
         b'Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3'
         b'Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5'
         b'EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZW'
         b'vunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzU'
         b'bEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=</ds:X509Cer'
         b'tificate></ds:X509Data></ds:KeyInfo></ds:Signature></des:solicitud><'
         b'/des:SolicitaDescarga></s:Body></s:Envelope>',
 'headers': {'Accept': 'text/xml',
             'Authorization': 'WRAP access_token="token_comprobante"',
             'Cache-Control': 'no-cache',
             'Content-type': 'text/xml;charset="utf-8"',
             'SOAPAction': 'http://DescargaMasivaTerceros.sat.gob.mx/ISolicitaDescargaService/SolicitaDescarga'},
 'url': 'https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc',
 'verify': True}