{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'Aportaciones': {'FechaAportacion': datetime.date(2016, 12, 5),
                                                                                     'TipoAportacion': [{'RecursosPropios': {'DatosAportacion': [{'AportacionNumerario': {'AportacionFideicomiso': 'NO',
                                                                                                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                                                                                                          'Moneda': Code('1', 'MXN'),
                                                                                                                                                                          'MontoAportacion': '16000.00',
                                                                                                                                                                          'NombreInstitucion': 'INSTITUCION'}}]}}]},
                                                                    'DesarrollosInmobiliarios': {'DatosDesarrollo': [{'CaracteristicasDesarrollo': [{'Calle': 'CALLE',
                                                                                                                                                     'CodigoPostal': '02000',
                                                                                                                                                     'Colonia': 'COLONIA',
                                                                                                                                                     'CostoUnidad': '1500.00',
                                                                                                                                                     'MontoDesarrollo': '150000.00',
                                                                                                                                                     'OtrasEmpresas': 'NO',
                                                                                                                                                     'TipoDesarrollo': '5',
                                                                                                                                                     'UnidadesComercializadas': '10.00'}],
                                                                                                                      'EntidadFederativa': '9',
                                                                                                                      'Modificacion': 'NO',
                                                                                                                      'ObjetoAvisoAnterior': 'NO',
                                                                                                                      'RegistroLicencia': 'REG2016-1'}]},
                                                                    'TipoOperacion': Code('1601', None)}]},
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF1'}],
              'MesReportado': '201612',
              'SujetoObligado': {'ClaveActividad': Code('DIN', None),
                                 'ClaveSujetoObligado': 'XXXX890505DF4'}}]}