{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2015, 9, 21),
                                                                    'TipoActividad': {'OtorgamientoPoder': {'Autoridad': {'DomicilioOficina': {'Nacional': {'Calle': 'CALLE',
                                                                                                                                                            'CodigoPostal': '02000',
                                                                                                                                                            'Colonia': 'CENTRO '
                                                                                                                                                                       'DE '
                                                                                                                                                                       'AZCAPOTZALCO',
                                                                                                                                                            'NumeroExterior': '41',
                                                                                                                                                            'NumeroInterior': 'D'}},
                                                                                                                          'TipoAutoridad': {'Administrativo': {'Cargo': 'CARGO',
                                                                                                                                                               'InstrumentoPublico': '1456000',
                                                                                                                                                               'Organo': 'ORGANO'}}},
                                                                                                            'DatosApoderado': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'XXXX',
                                                                                                                                                                  'ApellidoPaterno': 'GONZALEZ',
                                                                                                                                                                  'FechaNacimiento': datetime.date(2003, 3, 3),
                                                                                                                                                                  'Nombre': 'LAURA',
                                                                                                                                                                  'PaisNacionalidad': Code('NG', 'NIGERIA')}},
                                                                                                                                'TipoPoder': '3'}],
                                                                                                            'DatosPoderdante': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'PEREZ',
                                                                                                                                                                   'ApellidoPaterno': 'PEREZ',
                                                                                                                                                                   'Nombre': 'PEDRO',
                                                                                                                                                                   'PaisNacionalidad': Code('CC', 'ISLAS COCOS'),
                                                                                                                                                                   'Rfc': 'DRFA870604DE3'}}},
                                                                                                                                {'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'RAZON '
                                                                                                                                                                                       'SOCIAL',
                                                                                                                                                                  'PaisNacionalidad': Code('TC', 'ISLAS TURCAS Y CAICOS'),
                                                                                                                                                                  'Rfc': 'DER450512HH6'}}}],
                                                                                                            'PersonaSolicita': {'ApellidoMaterno': 'HERNANDEZ',
                                                                                                                                'ApellidoPaterno': 'XXXX',
                                                                                                                                'FechaNacimiento': datetime.date(1993, 3, 3),
                                                                                                                                'Nombre': 'JORGE',
                                                                                                                                'PaisNacionalidad': Code('AI', 'ANGUILA')}}}}]},
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF789'}],
              'MesReportado': '201509',
              'TribunalDependencia': {'ClaveActividad': Code('FES', None),
                                      'ClaveTribunalDependencia': 'HYT870503SE3'}}]}