{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '234234',
                                                                    'TipoActividad': {'ModificacionPatrimonial': {'DatosModificacion': {'DatosAccionista': [{'NumeroAcciones': '50.00',
                                                                                                                                                             'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'VILLA',
                                                                                                                                                                                               'ApellidoPaterno': 'SALAS',
                                                                                                                                                                                               'FechaNacimiento': datetime.date(1977, 10, 15),
                                                                                                                                                                                               'Nombre': 'ALMA',
                                                                                                                                                                                               'PaisNacionalidad': Code('MX', 'MEXICO')}}}],
                                                                                                                                        'FinalCapitalFijo': '11560.25',
                                                                                                                                        'FinalCapitalVariable': '100567.34',
                                                                                                                                        'InicialCapitalFijo': '12300.55',
                                                                                                                                        'InicialCapitalVariable': '10056.00',
                                                                                                                                        'TipoModificacionCapitalFijo': '2',
                                                                                                                                        'TipoModificacionCapitalVariable': '2'},
                                                                                                                  'PersonaMoralModifica': {'DenominacionRazon': 'CHOCOLATEAZTECA',
                                                                                                                                           'FechaConstitucion': datetime.date(2000, 8, 11),
                                                                                                                                           'GiroMercantil': Code('5231100', None),
                                                                                                                                           'InstrumentoPublico': '4500',
                                                                                                                                           'MotivoModificacion': '3',
                                                                                                                                           'NumeroTotalAcciones': '12334.55',
                                                                                                                                           'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                           'Rfc': 'CHO000811KJL'}}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANOI',
                                           'ApellidoPaterno': 'RODRIGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': '201406'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}