{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '1234568790',
                                                                    'TipoActividad': {'Avaluo': {'DatosPropietario': {'PropietarioSolicita': 'NO',
                                                                                                                      'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'OLI',
                                                                                                                                                        'ApellidoPaterno': 'CAS',
                                                                                                                                                        'FechaNacimiento': datetime.date(1982, 9, 3),
                                                                                                                                                        'Nombre': 'MAR',
                                                                                                                                                        'PaisNacionalidad': Code('AF', 'AFGANISTAN')}}},
                                                                                                 'TipoBien': '1',
                                                                                                 'ValorAvaluo': '580000.98'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'OLI',
                                           'ApellidoPaterno': 'CAS',
                                           'FechaNacimiento': datetime.date(1982, 3, 9),
                                           'Nombre': 'MAR'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'AAA111'}],
              'MesReportado': '201401',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'CAOM820309AM3'}}]}