{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'Destinatario': {'DestinatarioPersonaAviso': 'NO',
                                                                                     'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'SOLANO',
                                                                                                                       'ApellidoPaterno': 'RODRIGUEZ',
                                                                                                                       'FechaNacimiento': datetime.date(1978, 5, 22),
                                                                                                                       'Nombre': 'JOSE'}}},
                                                                    'Entrega': {'FechaEntrega': datetime.date(2014, 1, 1),
                                                                                'TipoEntrega': {'Nacional': {'CodigoPostal': '09230'}}},
                                                                    'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'Recepcion': {'CodigoPostal': '09230',
                                                                                  'FechaRecepcion': datetime.date(2014, 1, 1),
                                                                                  'TipoServicio': '1'},
                                                                    'TipoBien': [{'DatosEfectivoInstrumentos': {'InstrumentoMonetario': Code('2', 'Tarjeta de Crédito'),
                                                                                                                'Moneda': Code('4', 'AED'),
                                                                                                                'MontoOperacion': '444.00'}}],
                                                                    'TipoOperacion': Code('1001', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'X',
                                                                                  'ApellidoPaterno': 'LOPEZ',
                                                                                  'FechaNacimiento': datetime.date(1989, 5, 16),
                                                                                  'Nombre': 'PEDRO',
                                                                                  'PaisNacionalidad': Code('AD', 'ANDORRA')}}}],
                         'PersonaAviso': [{'Telefono': {'NumeroTelefono': '5515485454'},
                                           'TipoDomicilio': {'Nacional': {'Calle': 'REVOLUCION',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '458'}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                 'MORALISTA',
                                                                            'FechaConstitucion': datetime.date(2005, 12, 12),
                                                                            'GiroMercantil': Code('1119000', None),
                                                                            'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'PEREZ',
                                                                                                       'ApellidoPaterno': 'GOMEZ',
                                                                                                       'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                       'Nombre': 'JUAN',
                                                                                                       'Rfc': 'GOPJ801212R45'}}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF15454FG454'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('TCV', 'La prestación habitual o profesional de servicios de traslado o custodia de dinero o valores, con excepción de aquellos en los que intervenga el Banco de México y las instituciones dedicadas al depósito de valores'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}