{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('1501', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2013, 12, 12),
                                                                    'InstrumentoPublico': 'A',
                                                                    'TipoActividad': {'ContratoMutuoCredito': {'DatosAcreedor': [{'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1300003', None),
                                                                                                                                                                    'ApellidoMaterno': 'C',
                                                                                                                                                                    'ApellidoPaterno': 'C',
                                                                                                                                                                    'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                                                                                    'Nombre': 'C',
                                                                                                                                                                    'PaisNacionalidad': Code('AQ', 'ANTARTIDA')}}}],
                                                                                                               'DatosDeudor': [{'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1300003', None),
                                                                                                                                                                  'ApellidoMaterno': 'C',
                                                                                                                                                                  'ApellidoPaterno': 'C',
                                                                                                                                                                  'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                                                                                  'Nombre': 'C',
                                                                                                                                                                  'PaisNacionalidad': Code('AQ', 'ANTARTIDA')}}}],
                                                                                                               'DatosGarantia': [{'DatosBienMutuo': {'DatosInmueble': {'CodigoPostal': '06000',
                                                                                                                                                                       'FolioReal': '1111111',
                                                                                                                                                                       'TipoInmueble': Code('1', 'Casa/Casa en condominio'),
                                                                                                                                                                       'ValorReferencia': '1000000.00'}},
                                                                                                                                  'TipoGarantia': '2',
                                                                                                                                  'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'C',
                                                                                                                                                                    'ApellidoPaterno': 'C',
                                                                                                                                                                    'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                                                                                    'Nombre': 'C'}}},
                                                                                                                                 {'DatosBienMutuo': {'DatosOtro': {'DescripcionGarantia': 'OTRO'}},
                                                                                                                                  'TipoGarantia': '99',
                                                                                                                                  'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'C',
                                                                                                                                                                   'FechaConstitucion': datetime.date(1980, 12, 12)}}},
                                                                                                                                 {'TipoGarantia': '3',
                                                                                                                                  'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'FID',
                                                                                                                                                                  'Rfc': 'FID121212AAA'}}}],
                                                                                                               'DatosLiquidacion': [{'Moneda': Code('1', 'MXN'),
                                                                                                                                     'MontoOperacion': '10000000.00'}],
                                                                                                               'TipoOtorgamiento': '2'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'C',
                                           'ApellidoPaterno': 'C',
                                           'FechaNacimiento': datetime.date(1990, 12, 12),
                                           'Nombre': 'C'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'AA'}],
              'MesReportado': '201312',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'GOGC631212AAA'}}]}