{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('1302', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '01030',
                                                                    'DatosDonativo': {'TipoDonativo': [{'LiquidacionNumerario': {'FechaPago': datetime.date(2014, 6, 1),
                                                                                                                                 'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                                                                 'Moneda': Code('3', 'EUR'),
                                                                                                                                 'MontoOperacion': '175847.00'}},
                                                                                                       {'LiquidacionEspecie': {'BienDonado': '2',
                                                                                                                               'Moneda': Code('6', 'ALL'),
                                                                                                                               'MontoOperacion': '150.00'}},
                                                                                                       {'LiquidacionEspecie': {'BienDonado': '1',
                                                                                                                               'DatosBienDonado': {'DatosInmueble': {'CodigoPostal': '01030',
                                                                                                                                                                     'FolioReal': 'JGJ5JRJ5J5JEE-5',
                                                                                                                                                                     'TipoInmueble': Code('2', 'Departamento')}},
                                                                                                                               'Moneda': Code('3', 'EUR'),
                                                                                                                               'MontoOperacion': '14500.00'}},
                                                                                                       {'LiquidacionEspecie': {'BienDonado': '99',
                                                                                                                               'DatosBienDonado': {'DatosOtro': {'DescripcionBienDonado': 'MONUMENTO'}},
                                                                                                                               'Moneda': Code('2', 'USD'),
                                                                                                                               'MontoOperacion': '13578.00'}},
                                                                                                       {'LiquidacionEspecie': {'BienDonado': '7',
                                                                                                                               'Moneda': Code('1', 'MXN'),
                                                                                                                               'MontoOperacion': '1587945.00'}}]},
                                                                    'FechaOperacion': datetime.date(2014, 7, 1),
                                                                    'TipoOperacion': Code('1301', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'KASSA',
                                                                                 'FechaConstitucion': datetime.date(1925, 2, 15),
                                                                                 'PaisNacionalidad': Code('DE', 'ALEMANIA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Nacional': {'Calle': 'INSURGENTES',
                                                                          'CodigoPostal': '01030',
                                                                          'Colonia': 'AXOTLA',
                                                                          'NumeroExterior': '785',
                                                                          'NumeroInterior': 'B45'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1113000', None),
                                                                             'ApellidoMaterno': 'PEREZ',
                                                                             'ApellidoPaterno': 'GOMEZ',
                                                                             'Nombre': 'JOSELITO',
                                                                             'PaisNacionalidad': Code('PW', 'PALAOS'),
                                                                             'Rfc': 'PEGJ780219R56'}}},
                                          {'TipoDomicilio': {'Extranjero': {'Calle': 'STURGENSSEN',
                                                                            'CiudadPoblacion': 'MUNICH',
                                                                            'CodigoPostal': '115501',
                                                                            'Colonia': 'COLONIA',
                                                                            'EstadoProvincia': 'MUNICH',
                                                                            'NumeroExterior': '45',
                                                                            'Pais': Code('DE', 'ALEMANIA')}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'ASFASF',
                                                                            'FechaConstitucion': datetime.date(1895, 5, 16),
                                                                            'GiroMercantil': Code('1121000', None),
                                                                            'PaisNacionalidad': Code('AO', 'ANGOLA'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'LOPEZ',
                                                                                                       'ApellidoPaterno': 'LOPEZ',
                                                                                                       'Nombre': 'JUAN',
                                                                                                       'Rfc': 'LOLJ900505P09'}}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF12458RT5'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('DON', 'La recepción de donativos, por parte de las asociaciones y sociedades sin fines de lucro'),
                                 'ClaveSujetoObligado': 'OGS750505F56'}}]}