{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2015, 10, 2),
                                                                    'TipoActividad': {'DerechosInmuebles': {'DatosInmuebles': {'CaracteristicasInmueble': [{'Calle': 'CALLE',
                                                                                                                                                            'CodigoPostal': '56000',
                                                                                                                                                            'Colonia': 'TEZOYUCA',
                                                                                                                                                            'DimensionConstruido': '160.00',
                                                                                                                                                            'DimensionTerreno': '150.00',
                                                                                                                                                            'FolioReal': 'FOLIO123',
                                                                                                                                                            'NumeroExterior': '500',
                                                                                                                                                            'NumeroInterior': 'A',
                                                                                                                                                            'TipoInmueble': Code('2', 'Departamento'),
                                                                                                                                                            'ValorCatastral': '159000.00'},
                                                                                                                                                           {'Calle': 'CALLE',
                                                                                                                                                            'CodigoPostal': '06500',
                                                                                                                                                            'Colonia': 'CUAUHTEMOC',
                                                                                                                                                            'DimensionConstruido': '1000.00',
                                                                                                                                                            'DimensionTerreno': '900.00',
                                                                                                                                                            'FolioReal': 'FOLI987',
                                                                                                                                                            'NumeroExterior': '100',
                                                                                                                                                            'NumeroInterior': '1',
                                                                                                                                                            'TipoInmueble': Code('4', 'Edificio comercial'),
                                                                                                                                                            'ValorCatastral': '650000.00'}]},
                                                                                                            'Expediente': 'EXPD123',
                                                                                                            'Materia': 'MATERIA',
                                                                                                            'Organo': 'ORG '
                                                                                                                      'JUR',
                                                                                                            'PersonasActo': {'DatosPersonaActo': [{'Caracter': '1',
                                                                                                                                                   'Telefono': {'NumeroTelefono': '5400000000'},
                                                                                                                                                   'TipoDomicilio': {'Nacional': {'Calle': 'CALLE',
                                                                                                                                                                                  'CodigoPostal': '02300',
                                                                                                                                                                                  'Colonia': 'INDUSTRIAL '
                                                                                                                                                                                             'VALLEJO',
                                                                                                                                                                                  'NumeroExterior': '6'}},
                                                                                                                                                   'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'XXXX',
                                                                                                                                                                                     'ApellidoPaterno': 'PEREZ',
                                                                                                                                                                                     'FechaNacimiento': datetime.date(1999, 6, 6),
                                                                                                                                                                                     'Nombre': 'JUAN',
                                                                                                                                                                                     'PaisNacionalidad': Code('GH', 'GHANA')}}},
                                                                                                                                                  {'Caracter': '9',
                                                                                                                                                   'CaracterOtro': 'OTRO '
                                                                                                                                                                   'CARACTER',
                                                                                                                                                   'Telefono': {'NumeroTelefono': '871200000002'},
                                                                                                                                                   'TipoDomicilio': {'Extranjero': {'Calle': 'CALLE',
                                                                                                                                                                                    'CiudadPoblacion': 'CIUDAD',
                                                                                                                                                                                    'CodigoPostal': '540000',
                                                                                                                                                                                    'Colonia': 'COLONIA',
                                                                                                                                                                                    'EstadoProvincia': 'ESTADO',
                                                                                                                                                                                    'NumeroExterior': '9',
                                                                                                                                                                                    'Pais': Code('DE', 'ALEMANIA')}},
                                                                                                                                                   'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'DENOMINACION',
                                                                                                                                                                                    'FechaConstitucion': datetime.date(1993, 3, 3),
                                                                                                                                                                                    'PaisNacionalidad': Code('AL', 'ALBANIA'),
                                                                                                                                                                                    'RepresentanteApoderado': {'ApellidoMaterno': 'GARCIA',
                                                                                                                                                                                                               'ApellidoPaterno': 'GARCIA',
                                                                                                                                                                                                               'FechaNacimiento': datetime.date(1999, 6, 6),
                                                                                                                                                                                                               'Nombre': 'JOSE'}}}}]},
                                                                                                            'TipoActo': '9',
                                                                                                            'TipoActoOtro': 'OTRO '
                                                                                                                            'TIPO '
                                                                                                                            'DE '
                                                                                                                            'ACTO',
                                                                                                            'TipoJuicio': 'JUICIO'}}}]},
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF45'}],
              'MesReportado': '201510',
              'TribunalDependencia': {'ClaveActividad': Code('FES', None),
                                      'ClaveTribunalDependencia': 'LOU890506DE3'}}]}