{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '234234',
                                                                    'TipoActividad': {'ConstitucionPersonasMorales': {'CapitalSocial': {'CapitalFijo': '12810.00',
                                                                                                                                        'CapitalVariable': '1541800.44'},
                                                                                                                      'ConsejoVigilancia': 'NO',
                                                                                                                      'DatosAccionista': [{'CargoAccionista': '1',
                                                                                                                                           'NumeroAcciones': '30.00',
                                                                                                                                           'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'RIO',
                                                                                                                                                                             'ApellidoPaterno': 'FLORES',
                                                                                                                                                                             'FechaNacimiento': datetime.date(1977, 3, 17),
                                                                                                                                                                             'Nombre': 'MARIBEL',
                                                                                                                                                                             'PaisNacionalidad': Code('MX', 'MEXICO')}}},
                                                                                                                                          {'CargoAccionista': '5',
                                                                                                                                           'NumeroAcciones': '20.00',
                                                                                                                                           'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'DOMINGUEZ',
                                                                                                                                                                             'ApellidoPaterno': 'CASTRO',
                                                                                                                                                                             'FechaNacimiento': datetime.date(1978, 6, 11),
                                                                                                                                                                             'Nombre': 'SAUL',
                                                                                                                                                                             'PaisNacionalidad': Code('MX', 'MEXICO')}}}],
                                                                                                                      'DenominacionRazon': 'LAAZTECA',
                                                                                                                      'EntidadFederativa': '07',
                                                                                                                      'FolioMercantil': '231GH',
                                                                                                                      'GiroMercantil': Code('4640000', None),
                                                                                                                      'InstrumentoPublico': '12549655',
                                                                                                                      'MotivoConstitucion': '3',
                                                                                                                      'NumeroTotalAcciones': '12334.00',
                                                                                                                      'TipoPersonaMoral': '2'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANOI',
                                           'ApellidoPaterno': 'RODRIGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': '201406'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}