{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('705', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '01030',
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 1),
                                                                                          'FormaPago': Code('1', 'Contado'),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '1508596.00'},
                                                                                         {'FechaPago': datetime.date(2014, 7, 2),
                                                                                          'FormaPago': Code('1', 'Contado'),
                                                                                          'InstrumentoMonetario': Code('2', 'Tarjeta de Crédito'),
                                                                                          'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '8598484.00'}],
                                                                    'DatosObjeto': [{'Descripcion': 'UN '
                                                                                                    'PICASSO',
                                                                                     'TipoObjeto': '1'},
                                                                                    {'Descripcion': 'DAVID',
                                                                                     'NumeroRegistro': '456545RR5R6',
                                                                                     'TipoObjeto': '2',
                                                                                     'ValorReferencia': '98575456.00'},
                                                                                    {'Descripcion': 'SALMA '
                                                                                                    'NATURAL',
                                                                                     'TipoObjeto': '5',
                                                                                     'ValorReferencia': '100.00'},
                                                                                    {'Descripcion': 'VOCHITO '
                                                                                                    '1RA '
                                                                                                    'EDICION '
                                                                                                    'ALEMAN',
                                                                                     'NumeroRegistro': '654653443',
                                                                                     'TipoObjeto': '8'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 14),
                                                                    'TipoOperacion': Code('702', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'URRUTIA',
                                                                                  'ApellidoPaterno': 'BANANAN',
                                                                                  'FechaNacimiento': datetime.date(1990, 8, 16),
                                                                                  'Nombre': 'JUANITA',
                                                                                  'PaisNacionalidad': Code('SE', 'SUECIA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Nacional': {'Calle': 'REVO',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '4848'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1119000', None),
                                                                             'ApellidoMaterno': 'GALDOS',
                                                                             'ApellidoPaterno': 'PEREZ',
                                                                             'FechaNacimiento': datetime.date(1956, 10, 15),
                                                                             'Nombre': 'BENITO',
                                                                             'PaisNacionalidad': Code('BO', 'BOLIVIA')}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF454R54R'}],
              'MesReportado': '201405',
              'SujetoObligado': {'ClaveActividad': Code('OBA', 'La subasta o comercialización habitual o profesional de obras de arte, en las que se involucren operaciones de compra o venta de dichos bienes'),
                                 'ClaveSujetoObligado': 'OCA891212T67'}}]}