{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('4104', None)},
                         'OperacionesPersona': {'DetalleOperaciones': {'OperacionesCompra': {'Compra': [{'ActivoVirtual': {'ActivoVirtualOperado': 1001,
                                                                                                                           'CantidadActivoVirtual': '0.3973460252',
                                                                                                                           'TipoCambioMn': '188752.36'},
                                                                                                         'FechaHoraOperacion': '20190421094152',
                                                                                                         'HashOperacion': '43E3CA273C3966A56465484654865438979846546546ACDEFCC216A383605163',
                                                                                                         'MonedaOperacion': 1,
                                                                                                         'MontoOperacion': '75000.00'},
                                                                                                        {'ActivoVirtual': {'ActivoVirtualOperado': 1001,
                                                                                                                           'CantidadActivoVirtual': '0.7268141443',
                                                                                                                           'TipoCambioMn': '185742.12'},
                                                                                                         'FechaHoraOperacion': '20190422103202',
                                                                                                         'HashOperacion': '745AD2626C3966A56465484654865438979846546546ACDEFCC216A3836051AD',
                                                                                                         'MonedaOperacion': 1,
                                                                                                         'MontoOperacion': '135000.00'}]},
                                                                       'OperacionesFondos': {'FondosDepositados': {'Deposito': [{'DatosOrdenante': {'NacionalidadCuenta': {'Extranjero': {'NombreBanco': 'BANCA '
                                                                                                                                                                                                         'EXTRANJERA',
                                                                                                                                                                                          'NumeroCuenta': '987654321987654321'}},
                                                                                                                                                    'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'COMPAÑIA '
                                                                                                                                                                                                          'SA '
                                                                                                                                                                                                          'DE '
                                                                                                                                                                                                          'CV'}}},
                                                                                                                                 'FechaHoraOperacion': '20190420150521',
                                                                                                                                 'InstrumentoMonetario': Code('4', 'Tarjeta de Prepago'),
                                                                                                                                 'MonedaOperacion': 1,
                                                                                                                                 'MontoOperacion': '450000.00'}]},
                                                                                             'FondosRetirados': {'Retiro': [{'DatosBeneficiario': {'NacionalidadCuenta': {'Nacional': {'ClabeDestino': '012345678912345678',
                                                                                                                                                                                       'ClaveInstitucionFinanciera': 154}},
                                                                                                                                                   'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'MOLINA',
                                                                                                                                                                                     'ApellidoPaterno': 'DE '
                                                                                                                                                                                                        'LA '
                                                                                                                                                                                                        'ROSA',
                                                                                                                                                                                     'Nombre': 'MIGUEL '
                                                                                                                                                                                               'GILBERTO'}}},
                                                                                                                             'FechaHoraOperacion': '20190515211402',
                                                                                                                             'InstrumentoMonetario': Code('6', 'Cheque de Caja'),
                                                                                                                             'MonedaOperacion': 1,
                                                                                                                             'MontoOperacion': '100000.00'}]}},
                                                                       'OperacionesIntercambio': {'Intercambio': [{'ActivoVirtualEnviado': {'ActivoVirtual': {'ActivoVirtualOperado': 999999,
                                                                                                                                                              'CantidadActivoVirtual': '1.8414369346',
                                                                                                                                                              'DescripcionActivoVirtual': 'DIGITAL '
                                                                                                                                                                                          'COIN',
                                                                                                                                                              'TipoCambioMn': '36421.85'},
                                                                                                                                            'MontoOperacionMn': '67068.54'},
                                                                                                                   'ActivoVirtualRecibido': {'ActivoVirtual': {'ActivoVirtualOperado': 1001,
                                                                                                                                                               'CantidadActivoVirtual': '0.4449496649',
                                                                                                                                                               'TipoCambioMn': '150732.87'},
                                                                                                                                             'MontoOperacionMn': '67068.54'},
                                                                                                                   'FechaHoraOperacion': '20190525170245',
                                                                                                                   'HashOperacion': '64631325642346584A5A5A464A498646146009846001048EFCC216A383605163'}]},
                                                                       'OperacionesTransferencia': {'TransferenciasEnviadas': {'Envio': [{'ActivoVirtual': {'ActivoVirtualOperado': 1003,
                                                                                                                                                            'CantidadActivoVirtual': '10000.00',
                                                                                                                                                            'TipoCambioMn': '6.12'},
                                                                                                                                          'FechaHoraOperacion': '20190427103154',
                                                                                                                                          'HashOperacion': '895613181964D6469D4664646CD6984794DA8412318909C7897896A383605163',
                                                                                                                                          'MontoOperacionMn': '61200.00'}]},
                                                                                                    'TransferenciasRecibidas': {'Recepcion': [{'ActivoVirtual': {'ActivoVirtualOperado': 1001,
                                                                                                                                                                 'CantidadActivoVirtual': '1.50',
                                                                                                                                                                 'TipoCambioMn': '167895.78'},
                                                                                                                                               'FechaHoraOperacion': '20190503192036',
                                                                                                                                               'HashOperacion': 'B465B64B6AA321A321A3946546498646146009846001048EFCC216A383605163',
                                                                                                                                               'MontoOperacionMn': '251843.67'}]}},
                                                                       'OperacionesVenta': {'Venta': [{'ActivoVirtual': {'ActivoVirtualOperado': 1001,
                                                                                                                         'CantidadActivoVirtual': '0.3502263487',
                                                                                                                         'TipoCambioMn': '202305.11'},
                                                                                                       'FechaHoraOperacion': '20190501122831',
                                                                                                       'HashOperacion': '056460046C3966A564654846548654361361498484632146416216A383605163',
                                                                                                       'MonedaOperacion': 1,
                                                                                                       'MontoOperacion': '70852.58'}]}},
                                                'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'PRADO',
                                                                                                         'ApellidoPaterno': 'PEREZ',
                                                                                                         'Curp': 'PEPJ910101HCSRRN09',
                                                                                                         'FechaNacimiento': datetime.date(1991, 1, 1),
                                                                                                         'Nombre': 'JUAN',
                                                                                                         'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                         'Rfc': 'PEPJ910101F45'}}}],
                                                'PersonaAviso': {'DatosCuentaPlataforma': {'ClabeInterbancaria': '012345678912345678',
                                                                                           'CuentaRelacionada': '3333222211110000',
                                                                                           'IdUsuario': 'USUARIO_0123ABC',
                                                                                           'MonedaCuenta': 1},
                                                                 'Telefono': {'ClavePais': Code('MX', 'MEXICO'),
                                                                              'CorreoElectronico': 'CORREO_GENERAL@MAIL.COM',
                                                                              'NumeroTelefono': '5523344255'},
                                                                 'TipoDomicilio': {'Nacional': {'Calle': 'CENTRO',
                                                                                                'CodigoPostal': '62389',
                                                                                                'Colonia': 'MORELOS',
                                                                                                'NumeroExterior': '10',
                                                                                                'NumeroInterior': '9A'}},
                                                                 'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'EMPRESA '
                                                                                                                       'SA '
                                                                                                                       'DE '
                                                                                                                       'CV',
                                                                                                  'FechaConstitucion': datetime.date(2018, 5, 16),
                                                                                                  'GiroMercantil': Code('1121000', None),
                                                                                                  'PaisNacionalidad': Code('ES', 'ESPAÑA'),
                                                                                                  'RepresentanteApoderado': {'ApellidoMaterno': 'MOLINA',
                                                                                                                             'ApellidoPaterno': 'DE '
                                                                                                                                                'LA '
                                                                                                                                                'ROSA',
                                                                                                                             'Curp': 'ROMM900505HTSSLG06',
                                                                                                                             'DocumentoIdentificacion': {'NumeroIdentificacion': '012208180920',
                                                                                                                                                         'TipoIdentificacion': 1},
                                                                                                                             'FechaNacimiento': datetime.date(1990, 5, 5),
                                                                                                                             'Nombre': 'MIGUEL '
                                                                                                                                       'GILBERTO',
                                                                                                                             'Rfc': 'ROMM900505NI8'},
                                                                                                  'Rfc': 'EPS180516UF3'}}}},
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF201901'}],
              'MesReportado': '202005',
              'SujetoObligado': {'ClaveActividad': Code('AVI', None),
                                 'ClaveSujetoObligado': 'ABCD900101XD6',
                                 'DominioPlataforma': 'SAFE-COIN'}}]}