{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('111', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '05480',
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2009, 9, 9),
                                                                                          'InstrumentoMonetario': Code('11', 'Orden de Pago'),
                                                                                          'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '258000.58'}],
                                                                    'FechaOperacion': datetime.date(2013, 10, 25),
                                                                    'TipoBien': {'DatosInmueble': {'CodigoPostal': '02100',
                                                                                                   'DatosParteBlindada': [{'NivelBlindaje': '6',
                                                                                                                           'ParteBlindada': '2'}],
                                                                                                   'TipoInmueble': '10'}},
                                                                    'TipoOperacion': Code('901', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'BARCENAS',
                                                                                  'ApellidoPaterno': 'BIDART',
                                                                                  'Curp': 'BIBB771213HDFDRR01',
                                                                                  'FechaNacimiento': datetime.date(1977, 12, 13),
                                                                                  'Nombre': 'BERNARDO',
                                                                                  'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                  'Rfc': 'BIBB771213AAA'}}}],
                         'PersonaAviso': [{'Telefono': {'ClavePais': Code('IL', 'ISRAEL'),
                                                        'CorreoElectronico': 'BBBB@BBB.COM',
                                                        'NumeroTelefono': '031212121212'},
                                           'TipoDomicilio': {'Extranjero': {'Calle': 'CALLE',
                                                                            'CiudadPoblacion': 'JERUSALEN',
                                                                            'CodigoPostal': '53454',
                                                                            'Colonia': 'NORTE',
                                                                            'EstadoProvincia': 'JERUSALEN',
                                                                            'NumeroExterior': '12',
                                                                            'NumeroInterior': '1',
                                                                            'Pais': Code('IL', 'ISRAEL')}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                 'PATITA '
                                                                                                 'SA',
                                                                            'FechaConstitucion': datetime.date(1989, 2, 15),
                                                                            'GiroMercantil': Code('6999174', None),
                                                                            'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'DE '
                                                                                                                          'LA '
                                                                                                                          'RIVA',
                                                                                                       'ApellidoPaterno': 'PEREZ',
                                                                                                       'Curp': 'PERJ401220HDFRLS01',
                                                                                                       'FechaNacimiento': datetime.date(1940, 12, 20),
                                                                                                       'Nombre': 'JOSE '
                                                                                                                 'CARLOS',
                                                                                                       'Rfc': 'PERJ401220AAA'},
                                                                            'Rfc': 'LAP890215AAA'}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'CARLOS1'}],
              'MesReportado': '201310',
              'SujetoObligado': {'ClaveActividad': Code('BLI', 'La prestación habitual o profesional de servicios de blindaje de vehículos terrestres, nuevos o usados, así como de bienes inmuebles'),
                                 'ClaveSujetoObligado': 'ROBN781212HX5'}}]}