{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('263', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'Cantidad': '150',
                                                                    'CodigoPostal': '01030',
                                                                    'DatosLiquidacion': [{'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '15500.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 15),
                                                                    'TipoOperacion': Code('262', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'LOPEZ',
                                                                                  'ApellidoPaterno': 'BADILLO',
                                                                                  'FechaNacimiento': datetime.date(1949, 2, 14),
                                                                                  'Nombre': 'NORMA',
                                                                                  'PaisNacionalidad': Code('AR', 'ARGENTINA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Nacional': {'Calle': 'VIALIDAD '
                                                                                   'NORTE',
                                                                          'CodigoPostal': '06820',
                                                                          'Colonia': 'TRANSITO',
                                                                          'NumeroExterior': '78'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1111000', None),
                                                                             'ApellidoMaterno': 'PRIETO',
                                                                             'ApellidoPaterno': 'GALAN',
                                                                             'FechaNacimiento': datetime.date(1987, 5, 15),
                                                                             'Nombre': 'JORGE',
                                                                             'PaisNacionalidad': Code('DE', 'ALEMANIA')}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF45F45F4'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('TDR', 'La emisión o comercialización, habitual o profesional, de monederos electrónicos, certificados, o cupones, en los que, sin que exista un depósito previo del titular de dichos instrumentos, le sean abonados recursoso a los mismos provenientes de premios, promociones, devoluciones o derivados de recompensas comerciales y puedan ser utilizados para la adquisición de bienes o servicios en establecimeintos distintos al emisor de los referidos instrumentos o para la disposición de dinero en efectivo a través de cajeros automáticos o terminales puntos de venta o cualquier otro medio'),
                                 'ClaveSujetoObligado': 'OCA891215G67'}}]}