{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('234', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'Cantidad': '50',
                                                                    'CodigoPostal': '06920',
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 5),
                                                                                          'InstrumentoMonetario': Code('2', 'Tarjeta de Crédito'),
                                                                                          'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '1500.00'},
                                                                                         {'FechaPago': datetime.date(2014, 7, 5),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('1', 'MXN'),
                                                                                          'MontoOperacion': '18575.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 1),
                                                                    'TipoOperacion': Code('231', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'PEREZ',
                                                                                  'ApellidoPaterno': 'FERNANDEZ',
                                                                                  'FechaNacimiento': datetime.date(1994, 7, 19),
                                                                                  'Nombre': 'JOSE '
                                                                                            'RAMON',
                                                                                  'PaisNacionalidad': Code('CA', 'CANADA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Extranjero': {'Calle': 'MOZAS',
                                                                            'CiudadPoblacion': 'MOZAMBIQUITO',
                                                                            'CodigoPostal': '015481',
                                                                            'Colonia': 'MOZAMBO',
                                                                            'EstadoProvincia': 'MOZAMBICON',
                                                                            'NumeroExterior': '45',
                                                                            'Pais': Code('MZ', 'MOZAMBIQUE')}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                 'MORALISTA '
                                                                                                 'SA '
                                                                                                 'DE '
                                                                                                 'CV',
                                                                            'FechaConstitucion': datetime.date(1901, 5, 18),
                                                                            'GiroMercantil': Code('5311190', None),
                                                                            'PaisNacionalidad': Code('UK', 'REINO UNIDO'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'CHAVEZ',
                                                                                                       'ApellidoPaterno': 'PEREZ',
                                                                                                       'FechaNacimiento': datetime.date(1995, 5, 17),
                                                                                                       'Nombre': 'NAYELI'}}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'R7E7F75757T75'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('TPP', 'La emisión o comercialización, habitual o profesional de tarjetas prepagadas, vales o cupones, impresos o electrónicos, que puedan ser utilizados o canjeados para la adquisición de bienes o servicios, que no sean emitidos o comercializados por Entidades Financieras'),
                                 'ClaveSujetoObligado': 'OGA950518G56'}}]}