{'Informe': [{'Aviso': [{'Alerta': {'DescripcionAlerta': 'OTRA ALERTA',
                                    'TipoAlerta': Code('9999', 'Otra alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2015, 9, 1),
                                                                    'TipoActividad': {'ContratoMutuoCredito': {'Autoridad': {'DomicilioOficina': {'Nacional': {'Calle': 'CALLE',
                                                                                                                                                               'CodigoPostal': '59000',
                                                                                                                                                               'Colonia': 'CENTRO',
                                                                                                                                                               'NumeroExterior': '500',
                                                                                                                                                               'NumeroInterior': 'B'}},
                                                                                                                             'TipoAutoridad': {'Administrativo': {'Cargo': 'CAGO '
                                                                                                                                                                           'AUT',
                                                                                                                                                                  'InstrumentoPublico': 'INSTPUB123',
                                                                                                                                                                  'Organo': 'ORGADMIN '
                                                                                                                                                                            '1'}}},
                                                                                                               'DatosAcreedor': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'XXXX',
                                                                                                                                                                    'ApellidoPaterno': 'BELTRAN',
                                                                                                                                                                    'FechaNacimiento': datetime.date(1993, 6, 6),
                                                                                                                                                                    'Nombre': 'PABLO',
                                                                                                                                                                    'PaisNacionalidad': Code('IL', 'ISRAEL')}}},
                                                                                                                                 {'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'EMPRESA',
                                                                                                                                                                   'FechaConstitucion': datetime.date(2010, 10, 10),
                                                                                                                                                                   'PaisNacionalidad': Code('DE', 'ALEMANIA')}}},
                                                                                                                                 {'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'EMRESA '
                                                                                                                                                                                       'SA',
                                                                                                                                                                  'Rfc': 'FRD890505DER'}}}],
                                                                                                               'DatosDeudor': [{'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'RAZON '
                                                                                                                                                                                     'SOCIAL',
                                                                                                                                                                'Rfc': 'HJT870404DE1'}}},
                                                                                                                               {'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'PERSONA '
                                                                                                                                                                                      'MORAL',
                                                                                                                                                                 'FechaConstitucion': datetime.date(2003, 10, 6),
                                                                                                                                                                 'PaisNacionalidad': Code('NP', 'NEPAL')}}},
                                                                                                                               {'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'XXXX',
                                                                                                                                                                  'ApellidoPaterno': 'GONZALEZ',
                                                                                                                                                                  'FechaNacimiento': datetime.date(1920, 6, 6),
                                                                                                                                                                  'Nombre': 'JORGE',
                                                                                                                                                                  'PaisNacionalidad': Code('BG', 'BULGARIA')}}}],
                                                                                                               'DatosGarantia': [{'DatosBienGarantia': {'DatosInmueble': {'CodigoPostal': '74000',
                                                                                                                                                                          'FolioReal': '56456456XC',
                                                                                                                                                                          'TipoInmueble': Code('2', 'Departamento'),
                                                                                                                                                                          'ValorReferencia': '1800000.00'}},
                                                                                                                                  'TipoGarantia': '2',
                                                                                                                                  'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'XXXX',
                                                                                                                                                                    'ApellidoPaterno': 'GALLARDO',
                                                                                                                                                                    'Nombre': 'LORENA',
                                                                                                                                                                    'Rfc': 'ERDF780505DE3'}}},
                                                                                                                                 {'DatosBienGarantia': {'DatosOtro': {'DescripcionGarantia': 'DESCRIPCION '
                                                                                                                                                                                             'GARANTIA'}},
                                                                                                                                  'TipoGarantia': '99'},
                                                                                                                                 {'TipoGarantia': '3',
                                                                                                                                  'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'EMPRESA',
                                                                                                                                                                   'Rfc': 'WED65020312D'}}}],
                                                                                                               'DatosLiquidacion': [{'Moneda': Code('2', 'USD'),
                                                                                                                                     'MontoOperacion': '195000.00'},
                                                                                                                                    {'Moneda': Code('1', 'MXN'),
                                                                                                                                     'MontoOperacion': '29000000.00'}],
                                                                                                               'PersonaSolicita': {'ApellidoMaterno': 'PEREX',
                                                                                                                                   'ApellidoPaterno': 'XXXX',
                                                                                                                                   'Nombre': 'FERNANDO',
                                                                                                                                   'PaisNacionalidad': Code('GG', 'GUERNESEY'),
                                                                                                                                   'Rfc': 'DREF890505DE3'},
                                                                                                               'TipoOtorgamiento': '2'}}}]},
                         'Prioridad': Code('2', '24 hrs. con operaciones'),
                         'ReferenciaAviso': 'REF18'}],
              'MesReportado': '201510',
              'TribunalDependencia': {'ClaveActividad': Code('FES', None),
                                      'ClaveTribunalDependencia': 'DRT890505DR4'}}]}