{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('101', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'DatosLiquidacion': [{'LiquidacionNumerario': {'FechaPago': datetime.date(2014, 7, 21),
                                                                                                                   'InstrumentoMonetario': Code('3', 'Tarjeta de Debito'),
                                                                                                                   'Moneda': Code('2', 'USD'),
                                                                                                                   'MontoOperacion': '57000000.00'}},
                                                                                         {'LiquidacionEspecie': {'BienLiquidacion': '1',
                                                                                                                 'DatosBienLiquidacion': {'DatosInmueble': {'CodigoPostal': '54200',
                                                                                                                                                            'FolioReal': 'FOLIOREAL1234567890',
                                                                                                                                                            'TipoInmueble': '1'}},
                                                                                                                 'Moneda': Code('1', 'MXN'),
                                                                                                                 'ValorBien': '1200000.00'}}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 21),
                                                                    'LineaNegocio': '1',
                                                                    'MedioOperacion': '1',
                                                                    'TipoOperacion': Code('103', None),
                                                                    'TipoSucursal': {'DatosSucursalPropia': {'CodigoPostal': '54100'}}}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'FID '
                                                                                                     'BENE',
                                                                                'IdentificadorFideicomiso': 'IDENFIDEI',
                                                                                'Rfc': 'FID980505DFG'}}}],
                         'PersonaAviso': [{'Telefono': {'ClavePais': Code('DE', 'ALEMANIA'),
                                                        'CorreoElectronico': 'CORREO@MAIL.COM',
                                                        'NumeroTelefono': '01800000000'},
                                           'TipoDomicilio': {'Nacional': {'Calle': 'CALLE',
                                                                          'CodigoPostal': '54000',
                                                                          'Colonia': 'TLALNEPANTLA  '
                                                                                     'CENTRO',
                                                                          'NumeroExterior': '1',
                                                                          'NumeroInterior': 'B'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1000000', 'NO APLICA'),
                                                                             'ApellidoMaterno': 'XXXX',
                                                                             'ApellidoPaterno': 'TOÑO',
                                                                             'Curp': 'TOJX870101HDFJHR09',
                                                                             'FechaNacimiento': datetime.date(1987, 1, 1),
                                                                             'Nombre': 'JRGE',
                                                                             'PaisNacionalidad': Code('DE', 'ALEMANIA'),
                                                                             'Rfc': 'TOJX870101RE4'}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF2'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('JYS', 'La venta de boletos, fichas o cualquier otro tipo de comprobante similar para la práctica de juegos con apuesta, concursos o sorteos que realicen organismos descentralizados, así como el pago del valor que representen dichos boletos, fichas o recibos o, en general, la entrega o pago de premios y la realización de cualquier operación financiera'),
                                 'ClaveSujetoObligado': 'GAMJ860503HJU'}}]}