{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CaracteristicasInmueble': [{'Calle': 'SDFSDFSDF',
                                                                                                 'CodigoPostal': '09230',
                                                                                                 'Colonia': 'EL '
                                                                                                            'PARAISO',
                                                                                                 'DimensionConstruido': '43434.00',
                                                                                                 'DimensionTerreno': '3434.00',
                                                                                                 'FolioReal': '343434',
                                                                                                 'NumeroExterior': 'W2',
                                                                                                 'TipoInmueble': Code('1', 'Casa/Casa en condominio'),
                                                                                                 'ValorPactado': '5820000.12'}],
                                                                    'ContratoInstrumentoPublico': {'DatosInstrumentoPublico': {'EntidadInstrumentoPublico': '4',
                                                                                                                               'FechaInstrumentoPublico': datetime.date(2014, 1, 2),
                                                                                                                               'NotarioInstrumentoPublico': '4455',
                                                                                                                               'NumeroInstrumentoPublico': '555',
                                                                                                                               'ValorAvaluoCatastral': '11121321.00'}},
                                                                    'DatosContraparte': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'SOL',
                                                                                                                            'ApellidoPaterno': 'RODRIGUEZ',
                                                                                                                            'FechaNacimiento': datetime.date(1978, 5, 22),
                                                                                                                            'Nombre': 'JOSE ',
                                                                                                                            'PaisNacionalidad': Code('DE', 'ALEMANIA')}}}],
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 1, 1),
                                                                                          'FormaPago': Code('2', 'Diferido o en parcialidades'),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '234234344.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'FiguraCliente': '2',
                                                                    'FiguraSo': '3',
                                                                    'TipoOperacion': Code('501', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'X',
                                                                                  'ApellidoPaterno': 'LOPEZ',
                                                                                  'FechaNacimiento': datetime.date(1989, 5, 16),
                                                                                  'Nombre': 'PEDRO',
                                                                                  'PaisNacionalidad': Code('AD', 'ANDORRA')}}}],
                         'PersonaAviso': [{'Telefono': {'NumeroTelefono': '5515485454'},
                                           'TipoDomicilio': {'Nacional': {'Calle': 'REVOLUCION',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '458'}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                 'MORALISTA',
                                                                            'FechaConstitucion': datetime.date(2005, 12, 12),
                                                                            'GiroMercantil': Code('1119000', None),
                                                                            'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'PEREZ',
                                                                                                       'ApellidoPaterno': 'GOMEZ',
                                                                                                       'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                       'Nombre': 'JUAN',
                                                                                                       'Rfc': 'GOPJ801212R45'}}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF15454FG454'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('INM', 'La prestación habitual o profesional de servicios de construcción o desarrollo de bienes inmuebles o de intermediación en la transmisión de la propiedad o constitución de derechos sobre dichos bienes, en los que se involucren operaciones de compra o venta de los propios bienes por cuenta o a favor de clientes de quienes presten dichos servicios'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}