{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('304', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '01030',
                                                                    'DatosCheque': [{'MonedaCheques': '4',
                                                                                     'NumeroCheques': '40825'},
                                                                                    {'MonedaCheques': '9',
                                                                                     'NumeroCheques': '45'}],
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 12),
                                                                                          'InstrumentoMonetario': Code('2', 'Tarjeta de Crédito'),
                                                                                          'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '15000.00'},
                                                                                         {'FechaPago': datetime.date(2014, 7, 12),
                                                                                          'InstrumentoMonetario': Code('7', 'Cheques de Viajero'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '154848.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 1),
                                                                    'TipoOperacion': Code('301', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'DDDDD',
                                                                                 'FechaConstitucion': datetime.date(1955, 12, 15),
                                                                                 'PaisNacionalidad': Code('DE', 'ALEMANIA')}}}],
                         'PersonaAviso': [{'Telefono': {'CorreoElectronico': 'GG@GGSGSGTRT.COM'},
                                           'TipoDomicilio': {'Extranjero': {'Calle': 'VFTRE',
                                                                            'CiudadPoblacion': 'ANG',
                                                                            'CodigoPostal': '125853',
                                                                            'Colonia': 'ANGUI',
                                                                            'EstadoProvincia': 'DFGHDFGHD ',
                                                                            'NumeroExterior': '45',
                                                                            'NumeroInterior': '45B',
                                                                            'Pais': Code('AO', 'ANGOLA')}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('2361130', None),
                                                                             'ApellidoMaterno': 'JUAREZ',
                                                                             'ApellidoPaterno': 'PEREZ',
                                                                             'FechaNacimiento': datetime.date(1990, 5, 16),
                                                                             'Nombre': 'RUTILIO',
                                                                             'PaisNacionalidad': Code('DE', 'ALEMANIA')}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': '4123545321'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('CHV', 'La emisión y comercialización habitual o profesional de cheques de viajero, distinta a la realizada por las Entidades Financieras'),
                                 'ClaveSujetoObligado': 'OJA781213J89'}}]}