{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '234234',
                                                                    'TipoActividad': {'Escision': {'DatosEscindente': {'CapitalSocialFijo': '12000036.00',
                                                                                                                       'CapitalSocialVariable': '566000333.00',
                                                                                                                       'DatosAccionistaEscindente': [{'NumeroAcciones': '25.00',
                                                                                                                                                      'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'SOLUCIONESAVANTE',
                                                                                                                                                                                      'IdentificadorFideicomiso': 'YUSIDO',
                                                                                                                                                                                      'Rfc': 'CHO000811KJL'}}}],
                                                                                                                       'DenominacionRazon': 'AVANTE',
                                                                                                                       'EscindenteSubsiste': 'SI',
                                                                                                                       'FechaConstitucion': datetime.date(1978, 7, 13),
                                                                                                                       'FolioMercantil': 'YUT678',
                                                                                                                       'GiroMercantil': Code('5411100', None),
                                                                                                                       'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                       'Rfc': 'AVA780713IIO'},
                                                                                                   'DatosEscindidas': {'DatoEscindida': [{'CapitalSocialFijo': '1200365.00',
                                                                                                                                          'CapitalSocialVariable': '23555066.00',
                                                                                                                                          'DatosAccionista': [{'NumeroAcciones': '23.00',
                                                                                                                                                               'TipoPersona': {'Fideicomiso': {'DenominacionRazon': 'SOLUCIONESAVANTE',
                                                                                                                                                                                               'IdentificadorFideicomiso': 'YUSIDO',
                                                                                                                                                                                               'Rfc': 'CHO000811KJL'}}}],
                                                                                                                                          'DenominacionRazon': 'UFIO',
                                                                                                                                          'FechaConstitucion': datetime.date(1990, 2, 1),
                                                                                                                                          'FolioMercantil': 'RUTU8473',
                                                                                                                                          'GiroMercantil': Code('4810000', None),
                                                                                                                                          'NumeroTotalAcciones': '21.00',
                                                                                                                                          'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                          'Rfc': 'UFI900201KKK'}],
                                                                                                                       'EscindidasDeterminadas': 'SI'}}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANOI',
                                           'ApellidoPaterno': 'RODRIGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE'}],
                         'Prioridad': Code('2', '24 hrs. con operaciones'),
                         'ReferenciaAviso': '201406'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveEntidadColegiada': 'ROS78052254M',
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}