{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('602', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '01030',
                                                                    'DatosBien': [{'CantidadComercializada': '756.00',
                                                                                   'TipoBien': '1',
                                                                                   'UnidadComercializada': '2'},
                                                                                  {'CantidadComercializada': '2.00',
                                                                                   'TipoBien': '6',
                                                                                   'UnidadComercializada': '1'},
                                                                                  {'CantidadComercializada': '5.00',
                                                                                   'TipoBien': '10',
                                                                                   'UnidadComercializada': '3'},
                                                                                  {'CantidadComercializada': '50.00',
                                                                                   'TipoBien': '5',
                                                                                   'UnidadComercializada': '1'}],
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 15),
                                                                                          'FormaPago': Code('1', 'Contado'),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '1547896.59'},
                                                                                         {'FechaPago': datetime.date(2014, 7, 15),
                                                                                          'FormaPago': Code('1', 'Contado'),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('1', 'MXN'),
                                                                                          'MontoOperacion': '500.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 16),
                                                                    'TipoOperacion': Code('601', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                      'MORALISTA',
                                                                                 'FechaConstitucion': datetime.date(1982, 2, 15),
                                                                                 'PaisNacionalidad': Code('ES', 'ESPAÑA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Nacional': {'Calle': 'REVOLUCION',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '458'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('4640000', None),
                                                                             'ApellidoMaterno': 'GOMEZ',
                                                                             'ApellidoPaterno': 'PEREZ',
                                                                             'FechaNacimiento': datetime.date(1995, 5, 15),
                                                                             'Nombre': 'JUAN',
                                                                             'PaisNacionalidad': Code('RO', 'RUMANIA')}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF1215F'}],
              'MesReportado': '201405',
              'SujetoObligado': {'ClaveActividad': Code('MJR', 'La comercialización o intermediación habitual o profesional de Metales Preciosos, Piedras Preciosas, joyas o relojes, en las que se involucren operaciones de compra o venta de dichos bienes'),
                                 'ClaveSujetoObligado': 'OCA881212G56'}}]}