{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '234234',
                                                                    'TipoActividad': {'OtorgamientoPoder': {'DatosApoderado': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'GONZALES',
                                                                                                                                                                  'ApellidoPaterno': 'ROBLES',
                                                                                                                                                                  'FechaNacimiento': datetime.date(1992, 11, 20),
                                                                                                                                                                  'Nombre': 'ANDREA',
                                                                                                                                                                  'PaisNacionalidad': Code('MX', 'MEXICO')}},
                                                                                                                                'TipoPoder': '2'},
                                                                                                                               {'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'PEREZ',
                                                                                                                                                                  'ApellidoPaterno': 'BARGAS',
                                                                                                                                                                  'FechaNacimiento': datetime.date(1989, 4, 12),
                                                                                                                                                                  'Nombre': 'YARELY',
                                                                                                                                                                  'PaisNacionalidad': Code('MX', 'MEXICO')}},
                                                                                                                                'TipoPoder': '1'}],
                                                                                                            'DatosPoderdante': [{'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'AZTECA',
                                                                                                                                                                  'FechaConstitucion': datetime.date(1980, 2, 2),
                                                                                                                                                                  'GiroMercantil': Code('5313110', None),
                                                                                                                                                                  'PaisNacionalidad': Code('MX', 'MEXICO')}}}]}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANOI',
                                           'ApellidoPaterno': 'RODRIGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': '201406'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}