{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '234234',
                                                                    'TipoActividad': {'Fusion': {'DatosFusionadas': {'DatosFusionada': [{'CapitalSocialFijo': '2200.00',
                                                                                                                                         'CapitalSocialVariable': '1250033.00',
                                                                                                                                         'DenominacionRazon': 'SAISOLUCIONES',
                                                                                                                                         'FechaConstitucion': datetime.date(2000, 11, 2),
                                                                                                                                         'FolioMercantil': '718183FG',
                                                                                                                                         'GiroMercantil': Code('5222200', None),
                                                                                                                                         'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                         'Rfc': 'SAI001102HJK'},
                                                                                                                                        {'CapitalSocialFijo': '250133.00',
                                                                                                                                         'CapitalSocialVariable': '256601.00',
                                                                                                                                         'DenominacionRazon': 'ITSOL',
                                                                                                                                         'FechaConstitucion': datetime.date(2001, 4, 3),
                                                                                                                                         'FolioMercantil': '245500300',
                                                                                                                                         'GiroMercantil': Code('5231100', None),
                                                                                                                                         'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                         'Rfc': 'ITS010403UIO'}]},
                                                                                                 'DatosFusionante': {'Fusionante': {'CapitalSocialFijo': '12000036.00',
                                                                                                                                    'CapitalSocialVariable': '566000333.00',
                                                                                                                                    'DatosAccionista': [{'NumeroAcciones': '20336900.00',
                                                                                                                                                         'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'PRADO',
                                                                                                                                                                                           'ApellidoPaterno': 'SALAZAR',
                                                                                                                                                                                           'Curp': 'SAPA800309HHJKKK23',
                                                                                                                                                                                           'FechaNacimiento': datetime.date(1980, 3, 9),
                                                                                                                                                                                           'Nombre': 'ANTONIO',
                                                                                                                                                                                           'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                                                                           'Rfc': 'SAPA800309JHJ'}}},
                                                                                                                                                        {'NumeroAcciones': '21122.00',
                                                                                                                                                         'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'BALTAR',
                                                                                                                                                                                           'ApellidoPaterno': 'ALCALA',
                                                                                                                                                                                           'Curp': 'ALBM820714HJJLLL22',
                                                                                                                                                                                           'FechaNacimiento': datetime.date(1982, 7, 14),
                                                                                                                                                                                           'Nombre': 'MATIAS',
                                                                                                                                                                                           'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                                                                           'Rfc': 'ALBM820714FHG'}}}],
                                                                                                                                    'DenominacionRazon': 'AVANTE',
                                                                                                                                    'FechaConstitucion': datetime.date(1978, 7, 13),
                                                                                                                                    'FolioMercantil': 'YUT678',
                                                                                                                                    'GiroMercantil': Code('5411100', None),
                                                                                                                                    'NumeroTotalAcciones': '1236685.00',
                                                                                                                                    'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                                                                                    'Rfc': 'AVA780713IIO'},
                                                                                                                     'FusionanteDeterminadas': 'SI'},
                                                                                                 'TipoFusion': '1'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANOI',
                                           'ApellidoPaterno': 'RODRIGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE'}],
                         'Prioridad': Code('2', '24 hrs. con operaciones'),
                         'ReferenciaAviso': '201406'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveEntidadColegiada': 'ROS78052254M',
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}