{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('521', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '09230',
                                                                    'DatosGarantia': [{'DatosBienMutuo': {'DatosInmueble': {'CodigoPostal': '09230',
                                                                                                                            'FolioReal': '211561',
                                                                                                                            'TipoInmueble': Code('1', 'Casa/Casa en condominio'),
                                                                                                                            'ValorReferencia': '55555555.00'}},
                                                                                       'TipoGarantia': '2',
                                                                                       'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'SOLANO',
                                                                                                                         'ApellidoPaterno': 'RODRIGUEZ ',
                                                                                                                         'FechaNacimiento': datetime.date(1978, 5, 22),
                                                                                                                         'Nombre': 'JOSE '}}}],
                                                                    'DatosLiquidacion': [{'FechaDisposicion': datetime.date(2014, 1, 1),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('2', 'USD'),
                                                                                          'MontoOperacion': '234234344.00'}],
                                                                    'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'TipoOperacion': Code('402', None)}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'X',
                                                                                  'ApellidoPaterno': 'LOPEZ',
                                                                                  'FechaNacimiento': datetime.date(1989, 5, 16),
                                                                                  'Nombre': 'PEDRO',
                                                                                  'PaisNacionalidad': Code('AD', 'ANDORRA')}}}],
                         'PersonaAviso': [{'Telefono': {'NumeroTelefono': '5515485454'},
                                           'TipoDomicilio': {'Nacional': {'Calle': 'REVOLUCION',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '458'}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'LA '
                                                                                                 'MORALISTA',
                                                                            'FechaConstitucion': datetime.date(2005, 12, 12),
                                                                            'GiroMercantil': Code('1119000', None),
                                                                            'PaisNacionalidad': Code('MX', 'MEXICO'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'PEREZ',
                                                                                                       'ApellidoPaterno': 'GOMEZ',
                                                                                                       'FechaNacimiento': datetime.date(1980, 12, 12),
                                                                                                       'Nombre': 'JUAN',
                                                                                                       'Rfc': 'GOPJ801212R45'}}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF15454FG454'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('MPC', 'El ofrecimiento habitual o profesional de operaciones de mutuo o de garantía o de otorgamiento de préstamos o créditos, con o sin garantía, por parte de sujetos distintos a las Entidades Financieras'),
                                 'ClaveSujetoObligado': 'OGA751212G56'}}]}