{'Informe': [{'Aviso': [{'Alerta': {'DescripcionAlerta': 'AAAA',
                                    'TipoAlerta': Code('9999', 'Otra alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2013, 12, 12),
                                                                    'InstrumentoPublico': 'A',
                                                                    'TipoActividad': {'ConstitucionModificacionFideicomiso': {'DatosFideicomisarios': [{'DatosFideicomisariosDeterminados': 'NO',
                                                                                                                                                        'TipoPersona': [{'PersonaFisica': {'ActividadEconomica': Code('1300003', None),
                                                                                                                                                                                           'ApellidoMaterno': 'C',
                                                                                                                                                                                           'ApellidoPaterno': 'C',
                                                                                                                                                                                           'FechaNacimiento': datetime.date(1998, 12, 12),
                                                                                                                                                                                           'Nombre': 'C',
                                                                                                                                                                                           'PaisNacionalidad': Code('AD', 'ANDORRA')},
                                                                                                                                                                         'TipoMovimientoFideicomisario': '1'}]}],
                                                                                                                              'DatosFideicomitente': [{'DatosTipoPatrimonio': [{'PatrimonioMonetario': {'Moneda': Code('1', 'MXN'),
                                                                                                                                                                                                        'MontoOperacion': '10000000.00'}},
                                                                                                                                                                               {'PatrimonioOtroBien': {'Descripcion': 'DESC '
                                                                                                                                                                                                                      'OTRO '
                                                                                                                                                                                                                      'BIEN',
                                                                                                                                                                                                       'ValorBien': '2000000.00'}}],
                                                                                                                                                       'TipoMovimientoFideicomitente': '1',
                                                                                                                                                       'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('0300004', None),
                                                                                                                                                                                         'ApellidoMaterno': 'C',
                                                                                                                                                                                         'ApellidoPaterno': 'C',
                                                                                                                                                                                         'FechaNacimiento': datetime.date(1990, 12, 12),
                                                                                                                                                                                         'Nombre': 'C',
                                                                                                                                                                                         'PaisNacionalidad': Code('AF', 'AFGANISTAN')}}}],
                                                                                                                              'DatosMiembroComiteTecnico': {'ComiteTecnico': 'SI',
                                                                                                                                                            'ModificacionComiteTecnico': 'NO'},
                                                                                                                              'DenominacionRazon': 'FID',
                                                                                                                              'Descripcion': 'DESCRIPCION '
                                                                                                                                             'CONSTITUCION '
                                                                                                                                             'MODIFICACION '
                                                                                                                                             'FIDEICOMISO',
                                                                                                                              'IdentificadorFideicomiso': '1A',
                                                                                                                              'MontoPatrimonio': '5900000.40',
                                                                                                                              'TipoFideicomiso': '1',
                                                                                                                              'TipoMovimiento': '4'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'C',
                                           'ApellidoPaterno': 'C',
                                           'FechaNacimiento': datetime.date(1980, 12, 12),
                                           'Nombre': 'C'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'AAAA'}],
              'MesReportado': '201312',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'GOG630101AAA'}}]}