{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('206', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaPeriodo': '201407',
                                                                    'MontoGasto': '4555484.00',
                                                                    'NumeroIdentificador': '1254874125145489',
                                                                    'TipoOperacion': Code('201', None),
                                                                    'TipoTarjeta': '1'}]},
                         'PersonaAviso': [{'TipoDomicilio': {'Extranjero': {'Calle': 'DAVERGENSSEN',
                                                                            'CiudadPoblacion': 'MUNIC',
                                                                            'CodigoPostal': '01454',
                                                                            'Colonia': 'COLONIA',
                                                                            'EstadoProvincia': 'MUNICH',
                                                                            'NumeroExterior': '45',
                                                                            'Pais': Code('DE', 'ALEMANIA')}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1121000', None),
                                                                             'ApellidoMaterno': 'ZUBILLAGA',
                                                                             'ApellidoPaterno': 'BADILLO',
                                                                             'FechaNacimiento': datetime.date(1958, 1, 12),
                                                                             'Nombre': 'NOMA',
                                                                             'PaisNacionalidad': Code('AO', 'ANGOLA')}}},
                                          {'TipoPersona': {'Fideicomiso': {'ApoderadoDelegado': {'ApellidoMaterno': 'PLIEGO',
                                                                                                 'ApellidoPaterno': 'SALINAS',
                                                                                                 'Nombre': 'CARLOS',
                                                                                                 'Rfc': 'SAPC581212U78'},
                                                                           'DenominacionRazon': 'EL '
                                                                                                'SUPER '
                                                                                                'FIDE',
                                                                           'Rfc': 'ELS950505R45'}}},
                                          {'TipoDomicilio': {'Nacional': {'Calle': 'INSURGENTES',
                                                                          'CodigoPostal': '01030',
                                                                          'Colonia': 'FLORIDA',
                                                                          'NumeroExterior': '487'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('5620000', None),
                                                                             'ApellidoMaterno': 'URRUTIA',
                                                                             'ApellidoPaterno': 'GOMEZ',
                                                                             'Nombre': 'JOSE',
                                                                             'PaisNacionalidad': Code('AF', 'AFGANISTAN'),
                                                                             'Rfc': 'GOUJ750617R67'}}},
                                          {'TipoDomicilio': {'Nacional': {'Calle': 'REVOLUCION',
                                                                          'CodigoPostal': '01020',
                                                                          'Colonia': 'GUADALUPE '
                                                                                     'INN',
                                                                          'NumeroExterior': '450'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('5620000', None),
                                                                             'ApellidoMaterno': 'UGALDE',
                                                                             'ApellidoPaterno': 'GOMEZ',
                                                                             'Nombre': 'JOSE',
                                                                             'PaisNacionalidad': Code('AF', 'AFGANISTAN'),
                                                                             'Rfc': 'GOUJ750617R67'}}},
                                          {'TipoDomicilio': {'Nacional': {'Calle': 'CEMPRE',
                                                                          'CodigoPostal': '01040',
                                                                          'Colonia': 'CAMPESTRE',
                                                                          'NumeroExterior': '454'}},
                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'EL '
                                                                                                 'PENALISTA',
                                                                            'FechaConstitucion': datetime.date(1905, 10, 12),
                                                                            'GiroMercantil': Code('1113000', None),
                                                                            'PaisNacionalidad': Code('AD', 'ANDORRA'),
                                                                            'RepresentanteApoderado': {'ApellidoMaterno': 'ELU',
                                                                                                       'ApellidoPaterno': 'SLIM',
                                                                                                       'FechaNacimiento': datetime.date(1950, 5, 16),
                                                                                                       'Nombre': 'CARLOS '}}}},
                                          {'TipoDomicilio': {'Extranjero': {'Calle': 'HISERG',
                                                                            'CiudadPoblacion': 'JUHYRESESRETR',
                                                                            'CodigoPostal': '458014',
                                                                            'Colonia': 'NUGINAER',
                                                                            'EstadoProvincia': 'GHYB ',
                                                                            'NumeroExterior': '786',
                                                                            'Pais': Code('BA', 'BOSNIA Y HERZEGOVINA')}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('5620000', None),
                                                                             'ApellidoMaterno': 'URRUTIA',
                                                                             'ApellidoPaterno': 'LARA',
                                                                             'Nombre': 'JOSE',
                                                                             'PaisNacionalidad': Code('AF', 'AFGANISTAN'),
                                                                             'Rfc': 'GOUJ750617R67'}}},
                                          {'TipoPersona': {'Fideicomiso': {'ApoderadoDelegado': {'ApellidoMaterno': 'PORTILLO',
                                                                                                 'ApellidoPaterno': 'LOPEZ',
                                                                                                 'FechaNacimiento': datetime.date(1940, 8, 15),
                                                                                                 'Nombre': 'JOSE'},
                                                                           'DenominacionRazon': 'EL '
                                                                                                'FIDEL',
                                                                           'IdentificadorFideicomiso': '1455143'}}},
                                          {'TipoDomicilio': {'Nacional': {'Calle': 'GARZA',
                                                                          'CodigoPostal': '66670',
                                                                          'Colonia': 'DULCES '
                                                                                     'NOMBRES',
                                                                          'NumeroExterior': '458'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('5620000', None),
                                                                             'ApellidoMaterno': 'URRUTIA',
                                                                             'ApellidoPaterno': 'PEREZ',
                                                                             'Nombre': 'JOSE',
                                                                             'PaisNacionalidad': Code('AF', 'AFGANISTAN'),
                                                                             'Rfc': 'GOUJ750617R67'}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REFY6Y5H4B56M'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('TSC', 'La emisión o comercialización, habitual o profesional, de tarjetas de servicios o de crédito que no sean emitidas o comercializadas por Entidades Financieras'),
                                 'ClaveSujetoObligado': 'OGA780512G56'}}]}