{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('1201', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '4456',
                                                                    'TipoActividad': {'CesionDerechosFideicomitenteFideicomisario': {'DatosCedente': {'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('0300004', None),
                                                                                                                                                                                        'ApellidoMaterno': 'C',
                                                                                                                                                                                        'ApellidoPaterno': 'C',
                                                                                                                                                                                        'FechaNacimiento': datetime.date(1990, 12, 12),
                                                                                                                                                                                        'Nombre': 'C',
                                                                                                                                                                                        'PaisNacionalidad': Code('AF', 'AFGANISTAN')}}},
                                                                                                                                     'DatosCesion': {'MontoCesion': '115621261.00'},
                                                                                                                                     'DatosCesionario': {'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('1300003', None),
                                                                                                                                                                                           'ApellidoMaterno': 'C',
                                                                                                                                                                                           'ApellidoPaterno': 'C',
                                                                                                                                                                                           'FechaNacimiento': datetime.date(1998, 12, 12),
                                                                                                                                                                                           'Nombre': 'C',
                                                                                                                                                                                           'PaisNacionalidad': Code('AD', 'ANDORRA')}}},
                                                                                                                                     'DenominacionRazon': 'ASDASDASDASDD',
                                                                                                                                     'IdentificadorFideicomiso': '44564',
                                                                                                                                     'Rfc': 'ROS7805225M4',
                                                                                                                                     'TipoCesion': '1'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'SOLANO',
                                           'ApellidoPaterno': 'RODRIOGUEZ',
                                           'FechaNacimiento': datetime.date(1978, 5, 22),
                                           'Nombre': 'JOSE ',
                                           'Rfc': 'ROSM7805225M4'}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'AAA111'}],
              'MesReportado': '201401',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'CAOM820309AM3'}}]}