{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('803', None)},
                         'DetalleOperaciones': {'DatosOperacion': [{'CodigoPostal': '01030',
                                                                    'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 14),
                                                                                          'FormaPago': Code('1', 'Contado'),
                                                                                          'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                          'Moneda': Code('3', 'EUR'),
                                                                                          'MontoOperacion': '2728458.10'}],
                                                                    'FechaOperacion': datetime.date(2014, 7, 14),
                                                                    'TipoOperacion': Code('802', None),
                                                                    'TipoVehiculo': [{'DatosVehiculoTerrestre': {'Anio': '2014',
                                                                                                                 'MarcaFabricante': 'FORD',
                                                                                                                 'Modelo': 'MUSTANG '
                                                                                                                           'GT',
                                                                                                                 'NivelBlindaje': '3',
                                                                                                                 'Placas': 'ABC123',
                                                                                                                 'Repuve': '23452452',
                                                                                                                 'Vin': 'JKLSD789SDIFLGHS8'}},
                                                                                     {'DatosVehiculoTerrestre': {'Anio': '2013',
                                                                                                                 'MarcaFabricante': 'LINCOLN',
                                                                                                                 'Modelo': 'GT',
                                                                                                                 'NivelBlindaje': '9',
                                                                                                                 'Placas': '123ABC',
                                                                                                                 'Repuve': '39476390',
                                                                                                                 'Vin': 'ALSKJDALSJFAS75UF'}},
                                                                                     {'DatosVehiculoMaritimo': {'Anio': '2011',
                                                                                                                'Bandera': Code('AI', 'ANGUILA'),
                                                                                                                'MarcaFabricante': 'SPLNTEER',
                                                                                                                'Matricula': 'ASDFA43234',
                                                                                                                'Modelo': '508AS',
                                                                                                                'NivelBlindaje': '1',
                                                                                                                'NumeroSerie': '54555-FF'}},
                                                                                     {'DatosVehiculoMaritimo': {'Anio': '2013',
                                                                                                                'Bandera': Code('MM', 'MYANMAR'),
                                                                                                                'MarcaFabricante': 'BARRACUDA',
                                                                                                                'Matricula': 'J6J4B6N5',
                                                                                                                'Modelo': '4KLH435LK',
                                                                                                                'NivelBlindaje': '9',
                                                                                                                'NumeroSerie': 'LKEH56KJ45'}},
                                                                                     {'DatosVehiculoAereo': {'Anio': '2005',
                                                                                                             'Bandera': Code('AI', 'ANGUILA'),
                                                                                                             'MarcaFabricante': 'BOING',
                                                                                                             'Matricula': 'SDFK4534',
                                                                                                             'Modelo': '742',
                                                                                                             'NivelBlindaje': '9',
                                                                                                             'NumeroSerie': 'DFG654DF5G'}}]}]},
                         'DuenoBeneficiario': [{'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'GALDOS',
                                                                                  'ApellidoPaterno': 'PEREZ',
                                                                                  'FechaNacimiento': datetime.date(1956, 5, 16),
                                                                                  'Nombre': 'BENITO',
                                                                                  'PaisNacionalidad': Code('AI', 'ANGUILA')}}}],
                         'PersonaAviso': [{'TipoDomicilio': {'Nacional': {'Calle': 'VIOLANTE',
                                                                          'CodigoPostal': '06920',
                                                                          'Colonia': 'SAN '
                                                                                     'SIMON '
                                                                                     'TOLNAHUAC',
                                                                          'NumeroExterior': '887'}},
                                           'TipoPersona': {'PersonaFisica': {'ActividadEconomica': Code('6117000', None),
                                                                             'ApellidoMaterno': 'VALLE',
                                                                             'ApellidoPaterno': 'MORENO',
                                                                             'FechaNacimiento': datetime.date(1989, 5, 16),
                                                                             'Nombre': 'JOSE '
                                                                                       'ELIAS',
                                                                             'PaisNacionalidad': Code('RW', 'RUANDA')}}},
                                          {'TipoPersona': {'Fideicomiso': {'ApoderadoDelegado': {'ApellidoMaterno': 'LOPEZ',
                                                                                                 'ApellidoPaterno': 'ALMONTE',
                                                                                                 'FechaNacimiento': datetime.date(1905, 8, 16),
                                                                                                 'Nombre': 'NEPOMUNCENO'},
                                                                           'DenominacionRazon': 'EL '
                                                                                                'FIDE',
                                                                           'IdentificadorFideicomiso': '21353056'}}}],
                         'Prioridad': Code('1', 'Normal'),
                         'ReferenciaAviso': 'REF45K4J643'}],
              'MesReportado': '201407',
              'SujetoObligado': {'ClaveActividad': Code('VEH', 'La comercialización o distribución habitual profesional de vehículos, nuevos o usados, ya sean aéreos, marítimos o terrestres'),
                                 'ClaveSujetoObligado': 'OCA891122K87'}}]}