{'Informe': [{'Aviso': [{'Alerta': {'TipoAlerta': Code('100', 'Sin alerta')},
                         'DetalleOperaciones': {'DatosOperacion': [{'FechaOperacion': datetime.date(2014, 1, 1),
                                                                    'InstrumentoPublico': '1411',
                                                                    'TipoActividad': {'CompraVentaAcciones': {'DatosLiquidacion': [{'FechaPago': datetime.date(2014, 7, 1),
                                                                                                                                    'InstrumentoMonetario': Code('1', 'Efectivo'),
                                                                                                                                    'Moneda': Code('1', 'MXN'),
                                                                                                                                    'MontoOperacion': '1800000.12'}],
                                                                                                              'PersonaMoralAcciones': [{'DatosComprador': [{'NumeroAccionesCompradas': '40.00',
                                                                                                                                                            'TipoPersona': {'PersonaFisica': {'ApellidoMaterno': 'GONZALES',
                                                                                                                                                                                              'ApellidoPaterno': 'ROBLES',
                                                                                                                                                                                              'FechaNacimiento': datetime.date(1992, 11, 20),
                                                                                                                                                                                              'Nombre': 'ANDREA',
                                                                                                                                                                                              'PaisNacionalidad': Code('MX', 'MEXICO')}}}],
                                                                                                                                        'DatosVendedor': [{'NumeroAccionesVendidas': '45.00',
                                                                                                                                                           'TipoPersona': {'PersonaMoral': {'DenominacionRazon': 'AZTECA',
                                                                                                                                                                                            'FechaConstitucion': datetime.date(1980, 2, 2),
                                                                                                                                                                                            'PaisNacionalidad': Code('MX', 'MEXICO')}}}],
                                                                                                                                        'DenominacionRazon': 'PEDRO',
                                                                                                                                        'FechaConstitucion': datetime.date(1800, 1, 1),
                                                                                                                                        'NumeroAcciones': '45.00',
                                                                                                                                        'PaisNacionalidad': Code('AL', 'ALBANIA'),
                                                                                                                                        'ValorNominal': '112223215158.00'}],
                                                                                                              'TipoOperacion': '1'}}}]},
                         'PersonaAviso': [{'ApellidoMaterno': 'OLI',
                                           'ApellidoPaterno': 'CAS',
                                           'FechaNacimiento': datetime.date(1982, 3, 9),
                                           'Nombre': 'MAR',
                                           'Rfc': 'CAOM820309AM3'}],
                         'Prioridad': Code('2', '24 hrs. con operaciones'),
                         'ReferenciaAviso': 'REF01'}],
              'MesReportado': '201312',
              'SujetoObligado': {'ClaveActividad': Code('FEP', 'La prestación de servicios de fe pública, en los términos establecidos en el Artículo 17 fracción XII de la LFPIORPI'),
                                 'ClaveSujetoObligado': 'ORGA780216F45'}}]}