{'Addenda': None,
 'Certificado': 'MIIGAjCCA+qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0NjAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjIwMTcwMjQwWhcNMjMwNjE5MTcwMjQwWjCB9zEmMCQGA1UEAxQdSEVSUkVSSUEgJiBFTEVDVFJJQ09TIFMgREUgQ1YxJjAkBgNVBCkUHUhFUlJFUklBICYgRUxFQ1RSSUNPUyBTIERFIENWMSYwJAYDVQQKFB1IRVJSRVJJQSAmIEVMRUNUUklDT1MgUyBERSBDVjELMAkGA1UEBhMCTVgxKTAnBgkqhkiG9w0BCQEWGnBydWViYXMuc2F0QHBydWViYXMuZ29iLm14MSUwIwYDVQQtFBxIJkU5NTExMjg0NjkgLyBYT0pJNzQwOTE5VTQ4MR4wHAYDVQQFExUgLyBYT0pJNzQwOTE5TVFURE1OMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCystUoikV7leAFvyR4CyNAfcWugApKe9c4F7PwoE8z8waUOXUdWMVGIzt++OCPcc570xZ4IQFZwn6zjB8apZ2IqAmPeEoO89wC8jViNvo7YKiF++gWo3DBGl795wVlfrqb94zRQtokj7YuU33RsyNH0XudY8DShM/qvA2eqX5M0c/8CzTJesDoQJxvJDetYLR+ksJASj+PuDJedK/OoKE5S9LmwgZEAQ1HKyjDnMolY4VdmiGdw/Aljh2iO4TY4IB7vHry23mJOm+HdwJqwXg48A1Vp86JtbkDCg3IzI+PAEdncP3WjVkmkJyKSI899un7VXeUoh9oHIJcFdXrHOdxAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggIBAI2Qaj4co5YUuWa6jtUZFpKAxx5StDlOmVhyBpf3GFEvtTEvS7mLTHTARIOOcmHFHHc8mmVD3dPsUTrDxlo1qWR2qwrvrUn38bxkEF5IJK/XKcG0LOupl67V2gvnrm5bVkT9kJuYjYHdPFuSao4yEJhzHnMHOvT6rC3hhjywo6QGegQTuR+oTrwHQeU8SplNqkwd6k/GWL7Ba/2bVhH79lB4QpjuO2BXip0sHhLbctwu98Sp1FSiaooDlMzQeQoVWW8QgUQp15LaClsOTZRnXxztOR/h6cd25XQezdxqEoV0rS9BW+sgABPQNXDRWK87aeJ3R5lByjUhbt0eONod42l/emAiDE9S85tztQ4KkvMFA3e0vIth70sinS5eV/j1l4Ws+Ft/pdNA/AP3a2R6b+Lw4P7hCBVLtunx8pbh15KzX5g947JN5KVhMKvnqciCoMC9GowLzua/VNJX5pPiKXD6fm5bljW5JQ5F4Ue30Hve6lmftLGDXtOCDfj74+Zs3f3Y9gXkPAsK4y2WyZ1Xpw9dAIJJv5HajJwxbQVP2B48aN0ai46Dc6tQEp+Oa4oNHTRRyNNlqXwEb+IGtQ4FwiL13c55gOaSie1buy26a0yAO3ogcDfNyTcbfC73W9R0Zi4gsb+6xLuHZOLTJWUWLY9bE43P++KbWCGKz0uwIA3u',
 'CfdiRelacionados': None,
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2020, 1, 11, 0, 0),
                                         'Leyenda': None,
                                         'NoCertificadoSAT': '30001000000400002460',
                                         'RfcProvCertif': 'SAT970701NN3',
                                         'SelloCFD': 'ITnWt9XD28y3p9TifH554OrrvBoPcnsr+v33Tkhq+P+XD1tqg3dsKnC6GqYJezTdCbdpS9+VOaAK6b7/0Efw5KmwRKJ/zXHcdaG5vjHNoAljH+HHu/t4gbK+ToSkLnT2mSEr8dbGeUWMUXsu/yTonZQfw0aXcd8NXxwCJeB/EH1sAlAesZ1uMMVdcNhbOfiDPwFuMuGaKvTXj6pRpbU4SdZ5BKboqyOBfiBtXC+B/n8R/NoniMs+SAhPj9QF4hFPh5v62eFFrP1/KeK16uwHhUaF4VQmqvIgKmoh84kaFhXLXRLD80q0ShgfnYWof8uDZH7o7fIon02FMDUxSZdmgQ==',
                                         'SelloSAT': 'Bs+W7EiR2Aunl7bwlw+P7/Cg3MMSjYi/rBIDhXQRFCPZM7clokx51hVGNZqhwA/noGGCPtGPPLrZVOJiL95bt9DMjL8YbKpBptBG+xGGpErPIDb6xHUdva+JmY/nQ6l1vp6OdfUmDt8H4vmpu4usdtDV4gz8GUP7ujOddBjmmkhUR3yQQpb9s/RlCJnFUj/Xtefya7ZIa3MFeVWnxsyAT/8tDdxEmydcw7wRhBYGmp7zK8C0i/4Uy9KGJQCed4kqUt/p4D/IOyq/XKr+GkYFofiw5iVPFbrjvfFv5ufeew5+qLz43yyQ5Vvs0vdAgEhpC7X1SKurXTk16RW4zCakkw==',
                                         'UUID': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                         'Version': '1.1'}},
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': Decimal('1.00'),
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': '1234567890',
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('15390.30'),
                'Impuestos': {'Traslados': [{'Base': Decimal('15390.30'),
                                             'Importe': None,
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': None,
                                             'TipoFactor': <TipoFactor.EXENTO: 'Exento'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('15390.30'),
                '_traslados_incluidos': False}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'HERRERIA & ELECTRICOS',
            'RegimenFiscal': '601',
            'Rfc': RFC('H&E951128469')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'TotalImpuestosTrasladados': 0,
               'Traslados': [{'Base': Decimal('15390.30'),
                              'Importe': None,
                              'Impuesto': <Impuesto.IVA: '002'>,
                              'TasaOCuota': None,
                              'TipoFactor': <TipoFactor.EXENTO: 'Exento'>}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002460',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': 'ITnWt9XD28y3p9TifH554OrrvBoPcnsr+v33Tkhq+P+XD1tqg3dsKnC6GqYJezTdCbdpS9+VOaAK6b7/0Efw5KmwRKJ/zXHcdaG5vjHNoAljH+HHu/t4gbK+ToSkLnT2mSEr8dbGeUWMUXsu/yTonZQfw0aXcd8NXxwCJeB/EH1sAlAesZ1uMMVdcNhbOfiDPwFuMuGaKvTXj6pRpbU4SdZ5BKboqyOBfiBtXC+B/n8R/NoniMs+SAhPj9QF4hFPh5v62eFFrP1/KeK16uwHhUaF4VQmqvIgKmoh84kaFhXLXRLD80q0ShgfnYWof8uDZH7o7fIon02FMDUxSZdmgQ==',
 'Serie': 'A',
 'SubTotal': Decimal('15390.30'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('15390.30'),
 'Version': '4.0'}