{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': {'Deducciones': {'Deduccion': [{'Clave': '300',
                                                'Concepto': 'ISR A CARGO',
                                                'Importe': Decimal('1234.73'),
                                                'TipoDeduccion': '002'},
                                               {'Clave': '204',
                                                'Concepto': 'FONDO DE AHORRO '
                                                            'EMPLEADOS',
                                                'Importe': Decimal('521.10'),
                                                'TipoDeduccion': '004'}],
                                 'TotalImpuestosRetenidos': Decimal('1234.73'),
                                 'TotalJubilacionPensionRetiro': 0,
                                 'TotalOtrasDeducciones': Decimal('521.10'),
                                 'TotalSeparacionIndemnizacion': 0},
                 'Emisor': {'RegistroPatronal': 'Z1234567890'},
                 'FechaFinalPago': datetime.date(2020, 1, 31),
                 'FechaInicialPago': datetime.date(2020, 1, 16),
                 'FechaPago': datetime.date(2020, 1, 30),
                 'Incapacidades': [{'DiasIncapacidad': 2,
                                    'ImporteMonetario': Decimal('1000.00'),
                                    'TipoIncapacidad': '02'}],
                 'NumDiasPagados': Decimal('16.000'),
                 'OtrosPagos': [{'Clave': '046',
                                 'Concepto': 'REEMBOLSO DE GASTOS',
                                 'Importe': Decimal('456.00'),
                                 'TipoOtroPago': '999'},
                                {'Clave': '002',
                                 'Concepto': 'SUBSIDIO EMPLEO',
                                 'Importe': Decimal('0.00'),
                                 'SubsidioAlEmpleo': Decimal('0.00'),
                                 'TipoOtroPago': '002'}],
                 'Percepciones': {'Percepcion': [{'Clave': '001',
                                                  'Concepto': 'SUELDO',
                                                  'ImporteExento': Decimal('400.00'),
                                                  'ImporteGravado': Decimal('1200.00'),
                                                  'TipoPercepcion': '001'}],
                                  'TotalExento': Decimal('400.00'),
                                  'TotalGravado': Decimal('1200.00'),
                                  'TotalSueldos': Decimal('1600.00')},
                 'Receptor': {'Antigüedad': 'P96W',
                              'ClaveEntFed': 'MOR',
                              'CuentaBancaria': '0001000200030004',
                              'Curp': 'XIQB891116MCHZRL72',
                              'Departamento': 'Departamento del Trabajo',
                              'FechaInicioRelLaboral': datetime.date(2020, 1, 1),
                              'NumEmpleado': '12345678',
                              'NumSeguridadSocial': '987654321',
                              'PeriodicidadPago': '04',
                              'Puesto': 'Trabajador',
                              'RiesgoPuesto': '2',
                              'SalarioDiarioIntegrado': Decimal('100.01'),
                              'Sindicalizado': 'No',
                              'TipoContrato': '01',
                              'TipoJornada': '01',
                              'TipoRegimen': '02'},
                 'TipoNomina': 'O',
                 'TotalDeducciones': Decimal('1755.83'),
                 'TotalOtrosPagos': Decimal('456.00'),
                 'TotalPercepciones': Decimal('1600.00'),
                 'Version': '1.2'},
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '84111505',
                'ClaveUnidad': 'ACT',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'Pago de nómina',
                'Descuento': Decimal('1755.83'),
                'Importe': Decimal('2056.00'),
                'Impuestos': None,
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '03',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('2056.00')}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': Decimal('1755.83'),
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 9, 29, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': '99',
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PUE',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'CN01'},
 'Sello': 'bbKiSMAtgypfEAhdUx3Lwxw1n3yZe7yR6py7WRXw49FZ97KY65eFDoN1zMpg8HkqWc/rC238271AHw0o4RGQc6X+Y8nDZ4IgQvFxrC86wZ+d/yqYG/btYd+mvtXAtbDovkqdPzs/4FmhvWrLDXoT6XXj9vs6XdMAQAhPWvfM/n6P6S55X2ZbVUM2Cyp+t5zrO2CV/3GgTw39aYafJIzblK3EqdNyLvI1zniaApoH2X6n0y20JNWYlzqy++HcLKdWKxJOMAMpHFGelYeq1LB3D4ysP0HWn8aVkOhETLIxh8sUmfy+yDH5Sd3GGTzu1y827Pns58N1/WtrO2S++QDAkw==',
 'Serie': 'A',
 'SubTotal': Decimal('2056.00'),
 'TipoCambio': None,
 'TipoDeComprobante': 'N',
 'Total': Decimal('300.17'),
 'Version': '4.0'}