{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': None,
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.03'),
                'Impuestos': {'Traslados': [{'Base': Decimal('100.03'),
                                             'Importe': Decimal('16.00'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.03'),
                '_traslados_incluidos': False},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.03'),
                'Impuestos': {'Traslados': [{'Base': Decimal('100.03'),
                                             'Importe': Decimal('16.00'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.03'),
                '_traslados_incluidos': False}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'TotalImpuestosTrasladados': Decimal('32.01'),
               'Traslados': [{'Base': Decimal('200.06'),
                              'Importe': Decimal('32.01'),
                              'Impuesto': <Impuesto.IVA: '002'>,
                              'TasaOCuota': Decimal('0.160000'),
                              'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': 'T59GluNZjmodDh0AJMV8LTvuw82HfKjtUVUfFjsahXdI/TBG4pVTsqT5gd5vRzV7/CxqVzjrIq2593sKOxS73OQWamwFx7dIXHwNKfQDVNdgBsi9uvwozrf3Bb0HUMk/1Rx8NyA3LKlm4PrdpG0bOvcPzAK6nsaKkxjDzVv4+cweGhaqKyna0YNaczYrvgCfMamKQd3T7mspbq7Ene0jmYK1WQLCEjBGnZqYmTJcJmrpxen9FZoseVD4dxYyAxRLmqAowWaZQJYfQSoVxltUrZVcdcqAP6W/awaxagpZHZ2clPJSQJper7tnK83t6Rc26TN9F4XoKqsz+b/UR0cw6g==',
 'Serie': 'A',
 'SubTotal': Decimal('200.06'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('232.07'),
 'Version': '4.0'}