{'Addenda': None,
 'Certificado': 'MIIGAjCCA+qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0NjAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjIwMTcwMjQwWhcNMjMwNjE5MTcwMjQwWjCB9zEmMCQGA1UEAxQdSEVSUkVSSUEgJiBFTEVDVFJJQ09TIFMgREUgQ1YxJjAkBgNVBCkUHUhFUlJFUklBICYgRUxFQ1RSSUNPUyBTIERFIENWMSYwJAYDVQQKFB1IRVJSRVJJQSAmIEVMRUNUUklDT1MgUyBERSBDVjELMAkGA1UEBhMCTVgxKTAnBgkqhkiG9w0BCQEWGnBydWViYXMuc2F0QHBydWViYXMuZ29iLm14MSUwIwYDVQQtFBxIJkU5NTExMjg0NjkgLyBYT0pJNzQwOTE5VTQ4MR4wHAYDVQQFExUgLyBYT0pJNzQwOTE5TVFURE1OMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCystUoikV7leAFvyR4CyNAfcWugApKe9c4F7PwoE8z8waUOXUdWMVGIzt++OCPcc570xZ4IQFZwn6zjB8apZ2IqAmPeEoO89wC8jViNvo7YKiF++gWo3DBGl795wVlfrqb94zRQtokj7YuU33RsyNH0XudY8DShM/qvA2eqX5M0c/8CzTJesDoQJxvJDetYLR+ksJASj+PuDJedK/OoKE5S9LmwgZEAQ1HKyjDnMolY4VdmiGdw/Aljh2iO4TY4IB7vHry23mJOm+HdwJqwXg48A1Vp86JtbkDCg3IzI+PAEdncP3WjVkmkJyKSI899un7VXeUoh9oHIJcFdXrHOdxAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggIBAI2Qaj4co5YUuWa6jtUZFpKAxx5StDlOmVhyBpf3GFEvtTEvS7mLTHTARIOOcmHFHHc8mmVD3dPsUTrDxlo1qWR2qwrvrUn38bxkEF5IJK/XKcG0LOupl67V2gvnrm5bVkT9kJuYjYHdPFuSao4yEJhzHnMHOvT6rC3hhjywo6QGegQTuR+oTrwHQeU8SplNqkwd6k/GWL7Ba/2bVhH79lB4QpjuO2BXip0sHhLbctwu98Sp1FSiaooDlMzQeQoVWW8QgUQp15LaClsOTZRnXxztOR/h6cd25XQezdxqEoV0rS9BW+sgABPQNXDRWK87aeJ3R5lByjUhbt0eONod42l/emAiDE9S85tztQ4KkvMFA3e0vIth70sinS5eV/j1l4Ws+Ft/pdNA/AP3a2R6b+Lw4P7hCBVLtunx8pbh15KzX5g947JN5KVhMKvnqciCoMC9GowLzua/VNJX5pPiKXD6fm5bljW5JQ5F4Ue30Hve6lmftLGDXtOCDfj74+Zs3f3Y9gXkPAsK4y2WyZ1Xpw9dAIJJv5HajJwxbQVP2B48aN0ai46Dc6tQEp+Oa4oNHTRRyNNlqXwEb+IGtQ4FwiL13c55gOaSie1buy26a0yAO3ogcDfNyTcbfC73W9R0Zi4gsb+6xLuHZOLTJWUWLY9bE43P++KbWCGKz0uwIA3u',
 'CfdiRelacionados': None,
 'Complemento': {'Pago': [{'DoctoRelacionado': [{'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('3245.12'),
                                                 'ImpSaldoAnt': Decimal('5000.43'),
                                                 'ImpSaldoInsoluto': Decimal('1755.31'),
                                                 'ImpuestosDR': {'TrasladosDR': [{'BaseDR': Decimal('2797.52'),
                                                                                  'ImporteDR': Decimal('447.60'),
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': Decimal('0.160000'),
                                                                                  'TipoFactorDR': Code('Tasa', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 2,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'}],
                           'FechaPago': datetime.datetime(2020, 1, 2, 22, 40, 38),
                           'FormaDePagoP': '03',
                           'ImpuestosP': {'TrasladosP': [{'BaseP': Decimal('2797.52'),
                                                          'ImporteP': Decimal('447.60'),
                                                          'ImpuestoP': Code('002', 'IVA'),
                                                          'TasaOCuotaP': Decimal('0.160000'),
                                                          'TipoFactorP': Code('Tasa', None)}]},
                           'MonedaP': Code('MXN', 'Peso Mexicano'),
                           'Monto': Decimal('3245.12'),
                           'TipoCambioP': 1}],
                 'Totales': {'MontoTotalPagos': Decimal('3245.12'),
                             'TotalTrasladosBaseIVA16': Decimal('2797.52'),
                             'TotalTrasladosImpuestoIVA16': Decimal('447.60')},
                 'Version': '2.0'},
 'Conceptos': {'ACuentaTerceros': None,
               'Cantidad': 1,
               'ClaveProdServ': '84111506',
               'ClaveUnidad': 'ACT',
               'ComplementoConcepto': None,
               'CuentaPredial': None,
               'Descripcion': 'Pago',
               'Descuento': None,
               'Importe': Decimal('0'),
               'Impuestos': None,
               'InformacionAduanera': None,
               'NoIdentificacion': None,
               'ObjetoImp': '01',
               'Parte': None,
               'Unidad': None,
               'ValorUnitario': Decimal('0'),
               '_traslados_incluidos': False},
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'Nombre': 'HERRERIA & ELECTRICOS',
            'RegimenFiscal': '606',
            'Rfc': RFC('H&E951128469')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': None,
 'Moneda': 'XXX',
 'NoCertificado': '30001000000400002460',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'RegimenFiscalReceptor': Code('601', 'General de Ley Personas Morales'),
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'CP01'},
 'Sello': 'p78XEYNfPGab0Mi+z2c6XuL1oWSwTlMtoAVn2PnjIa1e7Ei8Ymoyg/wBdxO/P5F5ENrwyu6fw0aJHtEqLsrUNezLi4lbRbWP6ZfNZSqQObyp7rMkEYQplVnDqxJwMOrYW7gf5vizplNM9wP+yT/oUGKHBjhZoCo1kE6BsTWly046CGVdIi9p1k7WM8hzp/KV7hP9yBeRpdMMFfWCaxDuw3+GwPwN2Q1A9Io3x2Fx2EXk5dhMWxGf96+eCECODfmasFKPB53udAzZVxl7mtjh6JEUNxgFplLx0EINx7P9VuzJrX0W2ll/STTCYGK6kqTP19s7deJICO1JS8Iz/mDqLw==',
 'Serie': 'A',
 'SubTotal': Decimal('0'),
 'TipoCambio': None,
 'TipoDeComprobante': 'P',
 'Total': Decimal('0'),
 'Version': '4.0'}