{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': {'Pago': [{'DoctoRelacionado': [{'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('13851.27'),
                                                 'ImpSaldoAnt': Decimal('13851.27'),
                                                 'ImpSaldoInsoluto': Decimal('0.00'),
                                                 'ImpuestosDR': {'RetencionesDR': [{'BaseDR': Decimal('15390.30'),
                                                                                    'ImporteDR': Decimal('1539.03'),
                                                                                    'ImpuestoDR': Code('001', 'ISR'),
                                                                                    'TasaOCuotaDR': Decimal('0.100000'),
                                                                                    'TipoFactorDR': Code('Tasa', None)}],
                                                                 'TrasladosDR': [{'BaseDR': Decimal('15390.30'),
                                                                                  'ImporteDR': None,
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': None,
                                                                                  'TipoFactorDR': Code('Exento', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 1,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'}],
                           'FechaPago': datetime.datetime(2020, 1, 2, 22, 40, 38),
                           'FormaDePagoP': '03',
                           'ImpuestosP': {'RetencionesP': [{'ImporteP': Decimal('1539.03'),
                                                            'ImpuestoP': Code('001', 'ISR')}],
                                          'TrasladosP': [{'BaseP': Decimal('15390.30'),
                                                          'ImporteP': None,
                                                          'ImpuestoP': Code('002', 'IVA'),
                                                          'TasaOCuotaP': None,
                                                          'TipoFactorP': Code('Exento', None)}]},
                           'MonedaP': Code('MXN', 'Peso Mexicano'),
                           'Monto': Decimal('13851.27'),
                           'TipoCambioP': 1}],
                 'Totales': {'MontoTotalPagos': Decimal('13851.27'),
                             'TotalRetencionesISR': Decimal('1539.03'),
                             'TotalTrasladosBaseIVAExento': Decimal('15390.30')},
                 'Version': '2.0'},
 'Conceptos': {'ACuentaTerceros': None,
               'Cantidad': 1,
               'ClaveProdServ': '84111506',
               'ClaveUnidad': 'ACT',
               'ComplementoConcepto': None,
               'CuentaPredial': None,
               'Descripcion': 'Pago',
               'Descuento': None,
               'Importe': Decimal('0'),
               'Impuestos': None,
               'InformacionAduanera': None,
               'NoIdentificacion': None,
               'ObjetoImp': '01',
               'Parte': None,
               'Unidad': None,
               'ValorUnitario': Decimal('0'),
               '_traslados_incluidos': False},
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '606',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': None,
 'Moneda': 'XXX',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'RegimenFiscalReceptor': Code('601', 'General de Ley Personas Morales'),
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'CP01'},
 'Sello': 'UWNnxmFhpsflnPeP79fGoU2vx+VZrm/RpbdzW+eg++5KF/njgdu2421VQkv577wH01Ce0e9Wv2clDJEZOPo8XfOgwrGANvhGlTotGssKlrGRF87aCGc/4wbdtnVWsskVyGnq5NN1yDCRVY6YEfoRmdgoxNz2J40l7goIzxf0xnR7zM0E+0r3yFscAKkLsXA2rLQMdZfYF3RbRrg/QNF9VpLYNug+iY9vyqN4zZy1UC3sTAMPJrk73lhHZwfyXEbBTuPOjhIb6BvpK6H+Iv9J69wWxtH3M8+zwRNMUfTa/ULqfPqfWPw/iIRhx4KzB63TJOCVRG2Cylk6dC+M0kZtsA==',
 'Serie': 'A',
 'SubTotal': Decimal('0'),
 'TipoCambio': None,
 'TipoDeComprobante': 'P',
 'Total': Decimal('0'),
 'Version': '4.0'}