{'Addenda': None,
 'Certificado': 'MIIGAjCCA+qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0NjAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjIwMTcwMjQwWhcNMjMwNjE5MTcwMjQwWjCB9zEmMCQGA1UEAxQdSEVSUkVSSUEgJiBFTEVDVFJJQ09TIFMgREUgQ1YxJjAkBgNVBCkUHUhFUlJFUklBICYgRUxFQ1RSSUNPUyBTIERFIENWMSYwJAYDVQQKFB1IRVJSRVJJQSAmIEVMRUNUUklDT1MgUyBERSBDVjELMAkGA1UEBhMCTVgxKTAnBgkqhkiG9w0BCQEWGnBydWViYXMuc2F0QHBydWViYXMuZ29iLm14MSUwIwYDVQQtFBxIJkU5NTExMjg0NjkgLyBYT0pJNzQwOTE5VTQ4MR4wHAYDVQQFExUgLyBYT0pJNzQwOTE5TVFURE1OMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCystUoikV7leAFvyR4CyNAfcWugApKe9c4F7PwoE8z8waUOXUdWMVGIzt++OCPcc570xZ4IQFZwn6zjB8apZ2IqAmPeEoO89wC8jViNvo7YKiF++gWo3DBGl795wVlfrqb94zRQtokj7YuU33RsyNH0XudY8DShM/qvA2eqX5M0c/8CzTJesDoQJxvJDetYLR+ksJASj+PuDJedK/OoKE5S9LmwgZEAQ1HKyjDnMolY4VdmiGdw/Aljh2iO4TY4IB7vHry23mJOm+HdwJqwXg48A1Vp86JtbkDCg3IzI+PAEdncP3WjVkmkJyKSI899un7VXeUoh9oHIJcFdXrHOdxAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggIBAI2Qaj4co5YUuWa6jtUZFpKAxx5StDlOmVhyBpf3GFEvtTEvS7mLTHTARIOOcmHFHHc8mmVD3dPsUTrDxlo1qWR2qwrvrUn38bxkEF5IJK/XKcG0LOupl67V2gvnrm5bVkT9kJuYjYHdPFuSao4yEJhzHnMHOvT6rC3hhjywo6QGegQTuR+oTrwHQeU8SplNqkwd6k/GWL7Ba/2bVhH79lB4QpjuO2BXip0sHhLbctwu98Sp1FSiaooDlMzQeQoVWW8QgUQp15LaClsOTZRnXxztOR/h6cd25XQezdxqEoV0rS9BW+sgABPQNXDRWK87aeJ3R5lByjUhbt0eONod42l/emAiDE9S85tztQ4KkvMFA3e0vIth70sinS5eV/j1l4Ws+Ft/pdNA/AP3a2R6b+Lw4P7hCBVLtunx8pbh15KzX5g947JN5KVhMKvnqciCoMC9GowLzua/VNJX5pPiKXD6fm5bljW5JQ5F4Ue30Hve6lmftLGDXtOCDfj74+Zs3f3Y9gXkPAsK4y2WyZ1Xpw9dAIJJv5HajJwxbQVP2B48aN0ai46Dc6tQEp+Oa4oNHTRRyNNlqXwEb+IGtQ4FwiL13c55gOaSie1buy26a0yAO3ogcDfNyTcbfC73W9R0Zi4gsb+6xLuHZOLTJWUWLY9bE43P++KbWCGKz0uwIA3u',
 'CfdiRelacionados': None,
 'Complemento': {'Pago': [{'DoctoRelacionado': [{'EquivalenciaDR': 1,
                                                 'Folio': '123456',
                                                 'IdDocumento': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                                 'ImpPagado': Decimal('15390.30'),
                                                 'ImpSaldoAnt': Decimal('15390.30'),
                                                 'ImpSaldoInsoluto': Decimal('0.00'),
                                                 'ImpuestosDR': {'TrasladosDR': [{'BaseDR': Decimal('15390.30'),
                                                                                  'ImporteDR': None,
                                                                                  'ImpuestoDR': Code('002', 'IVA'),
                                                                                  'TasaOCuotaDR': None,
                                                                                  'TipoFactorDR': Code('Exento', None)}]},
                                                 'MetodoDePagoDR': Code('PPD', 'Pago en parcialidades o diferido'),
                                                 'MonedaDR': Code('MXN', 'Peso Mexicano'),
                                                 'NumParcialidad': 1,
                                                 'ObjetoImpDR': '02',
                                                 'Serie': 'A'}],
                           'FechaPago': datetime.datetime(2020, 1, 2, 22, 40, 38),
                           'FormaDePagoP': '03',
                           'ImpuestosP': {'TrasladosP': [{'BaseP': Decimal('15390.30'),
                                                          'ImporteP': None,
                                                          'ImpuestoP': Code('002', 'IVA'),
                                                          'TasaOCuotaP': None,
                                                          'TipoFactorP': Code('Exento', None)}]},
                           'MonedaP': Code('MXN', 'Peso Mexicano'),
                           'Monto': Decimal('15390.30'),
                           'TipoCambioP': 1}],
                 'Totales': {'MontoTotalPagos': Decimal('15390.30'),
                             'TotalTrasladosBaseIVAExento': Decimal('15390.30')},
                 'Version': '2.0'},
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '84111506',
                'ClaveUnidad': 'ACT',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'Pago',
                'Descuento': None,
                'Importe': Decimal('0'),
                'Impuestos': None,
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '01',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('0')}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'HERRERIA & ELECTRICOS',
            'RegimenFiscal': '601',
            'Rfc': RFC('H&E951128469')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': None,
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': None,
 'Moneda': 'XXX',
 'NoCertificado': '30001000000400002460',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'RegimenFiscalReceptor': Code('601', 'General de Ley Personas Morales'),
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'CP01'},
 'Sello': 'mvI0V1XjRdO2LPJzrJswI63tnITmtnxI2xRZfGCpNs+8Crl85a6yDL6EZFx/pmkdcFN6g0Lumy/O1TWwpsBgE1Ivl67FFIRehQef+3ZBrRdvNnns5bFJlNiBI+6Wdyhz5N/oDgHx6wKrl+OrkxyNVxaesV7hPNyEdn+3elxfKmDJqUy3BgMp2SKgal8S0T6w69Zjq3E+Kn9APzGUsB2oNYcYhptjdays/5fygvtcwGis8aGNnj+PKyl21mHuSCSjz0JQmYySKgeLnj3HnMVfJn1AhKcltfHsFcsVwwz9B75AdEfu45z0fe2FvGRgPwtIbnpk0JnTE8v+D//ksRIaWw==',
 'Serie': 'A',
 'SubTotal': Decimal('0'),
 'TipoCambio': None,
 'TipoDeComprobante': 'P',
 'Total': Decimal('0'),
 'Version': '4.0'}