{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': None,
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.01'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.67'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.01'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.67'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.00'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.68'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.01'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.67'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.00'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.67'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')},
               {'ACuentaTerceros': None,
                'Cantidad': 1,
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': None,
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('100.06'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.01'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>},
                                              {'Base': Decimal('100.06'),
                                               'Importe': Decimal('10.68'),
                                               'Impuesto': <Impuesto.IVA: '002'>,
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('100.06'),
                                             'Importe': Decimal('16.01'),
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('100.06')}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'Retenciones': [{'Importe': Decimal('60.04'),
                                'Impuesto': <Impuesto.ISR: '001'>},
                               {'Importe': Decimal('64.04'),
                                'Impuesto': <Impuesto.IVA: '002'>}],
               'TotalImpuestosRetenidos': Decimal('124.08'),
               'TotalImpuestosTrasladados': Decimal('96.06'),
               'Traslados': [{'Base': Decimal('600.36'),
                              'Importe': Decimal('96.06'),
                              'Impuesto': <Impuesto.IVA: '002'>,
                              'TasaOCuota': Decimal('0.160000'),
                              'TipoFactor': <TipoFactor.TASA: 'Tasa'>}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': 'Y+zZzrecJoqeOvojFUPak+eLlbZhyAgJYld5evkPgZ0gQc1QBvdP96kDfOQVdAZgHHLscxcgLT8B6XtQHolyCq/Ra5Uec9QVMNGwCibjvFhGYFDIrkV9gACxCWX9CVVWxbQPiqbUOI4JsSD5tYdVKqU9/PjSeNxOZ00dYEJQ1Ld1L8DI6g1eG8WrnbOh/h4fHLOJj+E43Z0p0TEbwdsSpd8WHwMWkKuRCu/DlRuNggbghnkXT3ZgE7lezD8RIA/KjG7ZBoXMP/RkgfDD/vg4TdAIMar2tURs0pBlEwW4+vWcNpx+W3qJwpaYVHIQdqLE02qLg9FQWuLI8Z5gI1t5Vg==',
 'Serie': 'A',
 'SubTotal': Decimal('600.36'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('572.34'),
 'Version': '4.0'}