{'Addenda': None,
 'Certificado': 'MIIF1DCCA7ygAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMTEwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI4MjE1ODQyWhcNMjMwNTI3MjE1ODQyWjCByTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTELMAkGA1UEBhMCTVgxJTAjBgkqhkiG9w0BCQEWFnBydWViYXNAcHJ1ZWJhcy5nb2IubXgxFjAUBgNVBC0TDVhJUUI4OTExMTZRRTQxGzAZBgNVBAUTElhJUUI4OTExMTZNR1JNWlIwNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJJLU6Iu3cOyJ14hkh9mjCy3XN5i1M36+60vnwTap8Uv1vQQxJqIB4WK85CSJxujhZE0XY2OT6QPJMQ3kqcuMk8Yz+KptHq51Uhs4jiShI0GGoVUqZ/8qSmY+DnYM/WGvSzuaMMm+cMwgMVYusKHE5FI+K39ht9aSP045KIR84ImnDuVp6DJeUaHEtlqspnQfMvZHfmT71IT7niBJOWYThjmCKMX6Y5tnlng8pOs9hjwHzlpUhVlGRjjUSJjeIZZY66kgbQcpOFCUsoyR2SbOZDMWSqlsXNsRZ5sjICxFrMqZ6GoCzobx7tn6WYisTVvMIvkNHzi8a8idyAMVrDhNb0CAwEAAaNPME0wDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCA9gwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMEBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAFFyKKTbclgM9SellL9BCWusArCHwtERUXnaFzQzVbcXzZ9rrXoiXLo8OCCkE5fT4ig8FcWiH1bkh6ZABQSHKcEEY9ewJWZpD3bA8E7DLHfDHmG1EqRKStajIG1aq3GSvFAetMvJE2epFsWvkO7CkN2hNT9SwsFkBYl+aiCP27LzQ4uD+mXJ6Pg79nD/ayuQDa7RGJ6u5KHY1I66xcpVxOegQr+zolYQ6RfAye6Fk6JxUnYBVXtnsC3GLpB0fMb+53NZGzARVD9/762A3dy3GHlMWs9FVoRN7DBJyNsVSlAodi9ClETC3Tr7WuXIzPZTbu17JEcqgL6Ovrk6L/SLULvhDe89eBmZHGIm5Vaye2X1OeY+CmpKZ0nMzu16+hOhE3ecRTmxHFUCWzyHuH8qyBetiJY64vyHMwgbyqwM3Lk7lEQowhYb4s8vGyJgb0qQoyt0lACbtkM73CwzasPTtxnHZFKzt0C9aYIZvSVQidmK5EbGNh5YWL8tk352Sqjk4yxlZRqH8SkKHoMjPOrTcBJJwzWWQtz9hOl78kLqcYi+TK4ZWvunGXtZqDyQ2omhZBokSAHqUDjcRmOnuMpazF68j8U73Bz2voQtimMJlB/yyT6luFlzUbEK3ckUYBkk0PKxDe/6T7NXj+H4UWhpTivKnrqNWL7qAHLSP1tnmG8s=',
 'CfdiRelacionados': None,
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2020, 1, 11, 0, 0),
                                         'Leyenda': None,
                                         'NoCertificadoSAT': '30001000000400002311',
                                         'RfcProvCertif': 'SAT970701NN3',
                                         'SelloCFD': 'YPKNnHGZ7/wca9lyotn53nOB1E2tgFp3wmkTRchsfxIrUiyKDnayk/W3twHW7qnL4euEc8JWftxceRdZkRRbJPY1YFbF5WrFYURwl2fJzGt+pwJIZ5qRMqATocZjISvaOxT+NdFb8xV11VjDJAL2fqh530le830M/0DA5tGs7V3PngQU7BKCRLSemLaVmrAGSpR2QzBVgJq5dmCTJ2FJPxHLrP7tx5qpsaFQ686y3bjpKALJuO84bSZ1M5M5MU5xlYhdOcQdx+prPxVLQvCbPag95HJ/1uStd6Qri5mMjKkVgau5ah7Lewah0DdL5taVxjpgi6m1IJgPO99XlclOxg==',
                                         'SelloSAT': 'gzrwyQjdNjqgj9PVo4OM64N2j8H0EpkvqPaXFj0BCxHwpgJ45zqSZI4Wwdoy/rlF57leQlNYO3v6YzpHr6MPg7Te/es88uugwYz7I5lJm4/YvoCJEyW8k0ixSG47gCwOrtJieIKHpxdIrp20lMx6syeKK02aIFxo8y9uCmdr6A3cNbQKzQc6drjKv2AOan2JQ7sAiCz1RushzkBiyPFCfoZcg5ZlrGPbhYQcCeEGQCGn3LJpknhgTc/BLYRK5bmxIju7DLjqEevx8qVcbN4edXjT/6C05luvdISknt9lLK9+w8hAxZD9RLSqrC5Bs2/twUlGwu6HzCcEgS9cBFKoJQ==',
                                         'UUID': '6d7434a6-e3f2-47ad-9e4c-08849946afa0',
                                         'Version': '1.1'}},
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': Decimal('1.00'),
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': '1234567890',
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('15390.30'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1539.03'),
                                               'Impuesto': <Impuesto.ISR: '001'>,
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': <TipoFactor.TASA: 'Tasa'>}],
                              'Traslados': [{'Base': Decimal('15390.30'),
                                             'Importe': None,
                                             'Impuesto': <Impuesto.IVA: '002'>,
                                             'TasaOCuota': None,
                                             'TipoFactor': <TipoFactor.EXENTO: 'Exento'>}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('15390.30'),
                '_traslados_incluidos': False}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'BERENICE XIMO QUEZADA',
            'RegimenFiscal': '601',
            'Rfc': RFC('XIQB891116QE4')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 1, 1, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'Retenciones': [{'Importe': Decimal('1539.03'),
                                'Impuesto': <Impuesto.ISR: '001'>}],
               'TotalImpuestosRetenidos': Decimal('1539.03'),
               'TotalImpuestosTrasladados': 0,
               'Traslados': [{'Base': Decimal('15390.30'),
                              'Importe': None,
                              'Impuesto': <Impuesto.IVA: '002'>,
                              'TasaOCuota': None,
                              'TipoFactor': <TipoFactor.EXENTO: 'Exento'>}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002311',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': 'YPKNnHGZ7/wca9lyotn53nOB1E2tgFp3wmkTRchsfxIrUiyKDnayk/W3twHW7qnL4euEc8JWftxceRdZkRRbJPY1YFbF5WrFYURwl2fJzGt+pwJIZ5qRMqATocZjISvaOxT+NdFb8xV11VjDJAL2fqh530le830M/0DA5tGs7V3PngQU7BKCRLSemLaVmrAGSpR2QzBVgJq5dmCTJ2FJPxHLrP7tx5qpsaFQ686y3bjpKALJuO84bSZ1M5M5MU5xlYhdOcQdx+prPxVLQvCbPag95HJ/1uStd6Qri5mMjKkVgau5ah7Lewah0DdL5taVxjpgi6m1IJgPO99XlclOxg==',
 'Serie': 'A',
 'SubTotal': Decimal('15390.30'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('13851.27'),
 'Version': '4.0'}