{'Addenda': {'ClavesDescripcion': None,
             'Complemento': None,
             'Conceptos': None,
             'Emisor': None,
             'Generales': {'Embarque': None,
                           'FechaEntrega': None,
                           'FechaTipoCambio': None,
                           'NombreTransportista': None,
                           'NumeroEntrega': None,
                           'NumeroOrden': None,
                           'Observaciones': None,
                           'TerminosPago': None,
                           'TipoDocumento': 'Factura',
                           'TotalConLetra': None},
             'Receptor': None,
             'Version': '1.1'},
 'Certificado': 'MIIGAjCCA+qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0NjAwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjIwMTcwMjQwWhcNMjMwNjE5MTcwMjQwWjCB9zEmMCQGA1UEAxQdSEVSUkVSSUEgJiBFTEVDVFJJQ09TIFMgREUgQ1YxJjAkBgNVBCkUHUhFUlJFUklBICYgRUxFQ1RSSUNPUyBTIERFIENWMSYwJAYDVQQKFB1IRVJSRVJJQSAmIEVMRUNUUklDT1MgUyBERSBDVjELMAkGA1UEBhMCTVgxKTAnBgkqhkiG9w0BCQEWGnBydWViYXMuc2F0QHBydWViYXMuZ29iLm14MSUwIwYDVQQtFBxIJkU5NTExMjg0NjkgLyBYT0pJNzQwOTE5VTQ4MR4wHAYDVQQFExUgLyBYT0pJNzQwOTE5TVFURE1OMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCystUoikV7leAFvyR4CyNAfcWugApKe9c4F7PwoE8z8waUOXUdWMVGIzt++OCPcc570xZ4IQFZwn6zjB8apZ2IqAmPeEoO89wC8jViNvo7YKiF++gWo3DBGl795wVlfrqb94zRQtokj7YuU33RsyNH0XudY8DShM/qvA2eqX5M0c/8CzTJesDoQJxvJDetYLR+ksJASj+PuDJedK/OoKE5S9LmwgZEAQ1HKyjDnMolY4VdmiGdw/Aljh2iO4TY4IB7vHry23mJOm+HdwJqwXg48A1Vp86JtbkDCg3IzI+PAEdncP3WjVkmkJyKSI899un7VXeUoh9oHIJcFdXrHOdxAgMBAAGjTzBNMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgPYMBEGCWCGSAGG+EIBAQQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggIBAI2Qaj4co5YUuWa6jtUZFpKAxx5StDlOmVhyBpf3GFEvtTEvS7mLTHTARIOOcmHFHHc8mmVD3dPsUTrDxlo1qWR2qwrvrUn38bxkEF5IJK/XKcG0LOupl67V2gvnrm5bVkT9kJuYjYHdPFuSao4yEJhzHnMHOvT6rC3hhjywo6QGegQTuR+oTrwHQeU8SplNqkwd6k/GWL7Ba/2bVhH79lB4QpjuO2BXip0sHhLbctwu98Sp1FSiaooDlMzQeQoVWW8QgUQp15LaClsOTZRnXxztOR/h6cd25XQezdxqEoV0rS9BW+sgABPQNXDRWK87aeJ3R5lByjUhbt0eONod42l/emAiDE9S85tztQ4KkvMFA3e0vIth70sinS5eV/j1l4Ws+Ft/pdNA/AP3a2R6b+Lw4P7hCBVLtunx8pbh15KzX5g947JN5KVhMKvnqciCoMC9GowLzua/VNJX5pPiKXD6fm5bljW5JQ5F4Ue30Hve6lmftLGDXtOCDfj74+Zs3f3Y9gXkPAsK4y2WyZ1Xpw9dAIJJv5HajJwxbQVP2B48aN0ai46Dc6tQEp+Oa4oNHTRRyNNlqXwEb+IGtQ4FwiL13c55gOaSie1buy26a0yAO3ogcDfNyTcbfC73W9R0Zi4gsb+6xLuHZOLTJWUWLY9bE43P++KbWCGKz0uwIA3u',
 'CfdiRelacionados': None,
 'Complemento': None,
 'Conceptos': [{'ACuentaTerceros': None,
                'Cantidad': Decimal('1.00'),
                'ClaveProdServ': '10101702',
                'ClaveUnidad': 'E48',
                'ComplementoConcepto': None,
                'CuentaPredial': '1234567890',
                'Descripcion': 'SERVICIOS DE FACTURACION',
                'Descuento': None,
                'Importe': Decimal('15390.30'),
                'Impuestos': {'Retenciones': [{'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1539.03'),
                                               'Impuesto': '001',
                                               'TasaOCuota': Decimal('0.100000'),
                                               'TipoFactor': 'Tasa'},
                                              {'Base': Decimal('15390.30'),
                                               'Importe': Decimal('1641.64'),
                                               'Impuesto': '002',
                                               'TasaOCuota': Decimal('0.106667'),
                                               'TipoFactor': 'Tasa'}],
                              'Traslados': [{'Base': Decimal('15390.30'),
                                             'Importe': Decimal('2462.45'),
                                             'Impuesto': '002',
                                             'TasaOCuota': Decimal('0.160000'),
                                             'TipoFactor': 'Tasa'}]},
                'InformacionAduanera': None,
                'NoIdentificacion': None,
                'ObjetoImp': '02',
                'Parte': None,
                'Unidad': None,
                'ValorUnitario': Decimal('15390.30'),
                '_traslados_incluidos': False}],
 'CondicionesDePago': None,
 'Confirmacion': None,
 'Descuento': None,
 'Emisor': {'FacAtrAdquirente': None,
            'Nombre': 'HERRERIA & ELECTRICOS',
            'RegimenFiscal': '606',
            'Rfc': RFC('H&E951128469')},
 'Exportacion': '01',
 'Fecha': datetime.datetime(2020, 9, 29, 22, 40, 38),
 'Folio': '123456',
 'FormaPago': None,
 'Impuestos': {'Retenciones': [{'Importe': Decimal('1539.03'),
                                'Impuesto': '001'},
                               {'Importe': Decimal('1641.64'),
                                'Impuesto': '002'}],
               'TotalImpuestosRetenidos': Decimal('3180.67'),
               'TotalImpuestosTrasladados': Decimal('2462.45'),
               'Traslados': [{'Base': Decimal('15390.30'),
                              'Importe': Decimal('2462.45'),
                              'Impuesto': '002',
                              'TasaOCuota': Decimal('0.160000'),
                              'TipoFactor': 'Tasa'}]},
 'InformacionGlobal': None,
 'LugarExpedicion': '56820',
 'MetodoPago': 'PPD',
 'Moneda': 'MXN',
 'NoCertificado': '30001000000400002460',
 'Receptor': {'DomicilioFiscalReceptor': '59820',
              'Nombre': 'KIJ, S.A DE C.V.',
              'NumRegIdTrib': None,
              'RegimenFiscalReceptor': '601',
              'ResidenciaFiscal': None,
              'Rfc': 'KIJ0906199R1',
              'UsoCFDI': 'G03'},
 'Sello': 'sq149WhsUa0BHUq49RTo2Wr0k+ZrVHqVE1gaw7fbAKIpG1ltzVjUzlI+1DlKGvb07XJtUydPpq1Rse+a6XwmHwj31YnJViITLs0ZU1xTRZk8/X3wk2EGF3PH4GJKNiD6ZvTCyen4Uce5icERTf3+BNf3eZmPv+QFCWbjLTo+LAnzefgM3xZsW1oPckkuaczsoMy2XWfSaCyNS5oe1G0jgR35PTwod37xo2MW5HF38++qmT/omy14TaHoj1QsVDtfv1bCRRWw+MfRA5MWKCbR3rxYQnDLO/p0fLtOpareYwy59NVUfXfgPvQ8TC6omDBgrmN09tzgZTbhzefAGVKwUQ==',
 'Serie': 'A',
 'SubTotal': Decimal('15390.30'),
 'TipoCambio': None,
 'TipoDeComprobante': 'I',
 'Total': Decimal('14672.08'),
 'Version': '4.0'}