{'Certificado': 'MIIEdDCCA1ygAwIBAgIUMjAwMDEwMDAwMDAxMDAwMDU4NjcwDQYJKoZIhvcNAQEFBQAwggFvMRgwFgYDVQQDDA9BLkMuIGRlIHBydWViYXMxLzAtBgNVBAoMJlNlcnZpY2lvIGRlIEFkbWluaXN0cmFjacOzbiBUcmlidXRhcmlhMTgwNgYDVQQLDC9BZG1pbmlzdHJhY2nDs24gZGUgU2VndXJpZGFkIGRlIGxhIEluZm9ybWFjacOzbjEpMCcGCSqGSIb3DQEJARYaYXNpc25ldEBwcnVlYmFzLnNhdC5nb2IubXgxJjAkBgNVBAkMHUF2LiBIaWRhbGdvIDc3LCBDb2wuIEd1ZXJyZXJvMQ4wDAYDVQQRDAUwNjMwMDELMAkGA1UEBhMCTVgxGTAXBgNVBAgMEERpc3RyaXRvIEZlZGVyYWwxEjAQBgNVBAcMCUNveW9hY8OhbjEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMTIwMAYJKoZIhvcNAQkCDCNSZXNwb25zYWJsZTogSMOpY3RvciBPcm5lbGFzIEFyY2lnYTAeFw0xMjA3MjcxNzAyMDBaFw0xNjA3MjcxNzAyMDBaMIHbMSkwJwYDVQQDEyBBQ0NFTSBTRVJWSUNJT1MgRU1QUkVTQVJJQUxFUyBTQzEpMCcGA1UEKRMgQUNDRU0gU0VSVklDSU9TIEVNUFJFU0FSSUFMRVMgU0MxKTAnBgNVBAoTIEFDQ0VNIFNFUlZJQ0lPUyBFTVBSRVNBUklBTEVTIFNDMSUwIwYDVQQtExxBQUEwMTAxMDFBQUEgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxETAPBgNVBAsTCFVuaWRhZCAxMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2TTQSPONBOVxpXv9wLYo8jezBrb34i/tLx8jGdtyy27BcesOav2c1NS/Gdv10u9SkWtwdy34uRAVe7H0a3VMRLHAkvp2qMCHaZc4T8k47Jtb9wrOEh/XFS8LgT4y5OQYo6civfXXdlvxWU/gdM/e6I2lg6FGorP8H4GPAJ/qCNwIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQUFAAOCAQEATxMecTpMbdhSHo6KVUg4QVF4Op2IBhiMaOrtrXBdJgzGotUFcJgdBCMjtTZXSlq1S4DG1jr8p4NzQlzxsdTxaB8nSKJ4KEMgIT7E62xRUj15jI49qFz7f2uMttZLNThipunsN/NF1XtvESMTDwQFvas/Ugig6qwEfSZc0MDxMpKLEkEePmQwtZD+zXFSMVa6hmOu4M+FzGiRXbj4YJXn9Myjd8xbL/c+9UIcrYoZskxDvMxc6/6M3rNNDY3OFhBK+V/sPMzWWGt8S1yjmtPfXgFs1t65AZ2hcTwTAuHrKwDatJ1ZPfa482ZBROAAX1waz7WwXp0gso7sDCm2/yUVww==',
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2015, 2, 17, 11, 49, 20),
                                         'NoCertificadoSAT': '20001000000100005761',
                                         'SelloCFD': 'MMakX8Q1RyedjoNEQdHN64DgpZesmkcPSye2Tb+nELqFNNzITTicyc7WRcr/gj4UQX1ffhBuWmO959453o4pkMO9omip2DiM0Ud2KitU58+P4yRyxdjhmaRS9QSsUSpcKIrLB4viSJ9GD32pJYnxmpxYi8+GO+n3HvIAMHega+A=',
                                         'SelloSAT': 'HZcDZ/W0obh9pzd6XGSXfAEEzCp1bYLYHmptBRZLhYGgyo/nYegLpv1ULshKA2WiFnf9OpiemBQ9q0Z/To8QFINH1JqTBtEu0lo+8NWDBi6Zwc2VsR3uYE6ZmZKdQS7LtSt6uSqCiejXDqIV57EkJy3LE6JnTBsbQ7GmST1Wx/M=',
                                         'UUID': 'e403f396-6a57-4625-adb4-bb436b00789f',
                                         'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'Descripcion': 'Módulo de embarque serie A-6743-Ñ',
                'Importe': Decimal('35000.00'),
                'Unidad': 'LTE',
                'ValorUnitario': Decimal('35000.00')}],
 'Descuento': Decimal('0'),
 'Emisor': {'DomicilioFiscal': {'Calle': 'Encinos',
                                'CodigoPostal': '64000',
                                'Colonia': 'Fracc. San Pedro',
                                'Estado': 'Nuevo León',
                                'Municipio': 'Monterrey',
                                'NoExterior': '1452',
                                'Pais': 'México'},
            'Nombre': 'Empresa de Pruebas SA',
            'RegimenFiscal': ['Regimen General de Ley Personas Morales de '
                              'Prueba'],
            'Rfc': 'AAA010101AAA'},
 'Fecha': datetime.datetime(2015, 2, 18, 11, 49, 20),
 'Folio': '38',
 'FormaDePago': 'PAGO EN UNA SOLA EXHIBICION',
 'Impuestos': {'Retenciones': [{'Importe': Decimal('0.00'), 'Impuesto': 'ISR'},
                               {'Importe': Decimal('0.00'), 'Impuesto': 'IVA'}],
               'TotalImpuestosRetenidos': Decimal('0.00'),
               'TotalImpuestosTrasladados': Decimal('5600.00'),
               'Traslados': [{'Importe': Decimal('5600.00'),
                              'Impuesto': 'IVA',
                              'Tasa': Decimal('16.00')}]},
 'LugarExpedicion': 'Monterrey, Nuevo León',
 'MetodoDePago': 'No Identificado',
 'Moneda': 'Pesos',
 'NoCertificado': '20001000000100005867',
 'NumCtaPago': 'No Identificado',
 'Receptor': {'Domicilio': {'Calle': 'Av. Principal',
                            'CodigoPostal': '99170',
                            'Colonia': 'Ejido La Siembra',
                            'Estado': 'Zacatecas',
                            'Localidad': 'Ejido La Siembra',
                            'Municipio': 'Zacatecas',
                            'NoExterior': '102',
                            'Pais': 'México'},
              'Nombre': 'Exportadora de Ganado HOLSTEIN S.A.',
              'Rfc': 'E&Ñ831019M53'},
 'Sello': 'MMakX8Q1RyedjoNEQdHN64DgpZesmkcPSye2Tb+nELqFNNzITTicyc7WRcr/gj4UQX1ffhBuWmO959453o4pkMO9omip2DiM0Ud2KitU58+P4yRyxdjhmaRS9QSsUSpcKIrLB4viSJ9GD32pJYnxmpxYi8+GO+n3HvIAMHega+A=',
 'Serie': 'C',
 'SubTotal': Decimal('35000.00'),
 'TipoDeComprobante': 'ingreso',
 'Total': Decimal('40600.00'),
 'Version': '3.2'}