{'Addenda': {},
 'Certificado': 'MIIEdDCCA1ygAwIBAgIUMjAwMDEwMDAwMDAxMDAwMDU4NjcwDQYJKoZIhvcNAQEFBQAwggFvMRgwFgYDVQQDDA9BLkMuIGRlIHBydWViYXMxLzAtBgNVBAoMJlNlcnZpY2lvIGRlIEFkbWluaXN0cmFjacOzbiBUcmlidXRhcmlhMTgwNgYDVQQLDC9BZG1pbmlzdHJhY2nDs24gZGUgU2VndXJpZGFkIGRlIGxhIEluZm9ybWFjacOzbjEpMCcGCSqGSIb3DQEJARYaYXNpc25ldEBwcnVlYmFzLnNhdC5nb2IubXgxJjAkBgNVBAkMHUF2LiBIaWRhbGdvIDc3LCBDb2wuIEd1ZXJyZXJvMQ4wDAYDVQQRDAUwNjMwMDELMAkGA1UEBhMCTVgxGTAXBgNVBAgMEERpc3RyaXRvIEZlZGVyYWwxEjAQBgNVBAcMCUNveW9hY8OhbjEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMTIwMAYJKoZIhvcNAQkCDCNSZXNwb25zYWJsZTogSMOpY3RvciBPcm5lbGFzIEFyY2lnYTAeFw0xMjA3MjcxNzAyMDBaFw0xNjA3MjcxNzAyMDBaMIHbMSkwJwYDVQQDEyBBQ0NFTSBTRVJWSUNJT1MgRU1QUkVTQVJJQUxFUyBTQzEpMCcGA1UEKRMgQUNDRU0gU0VSVklDSU9TIEVNUFJFU0FSSUFMRVMgU0MxKTAnBgNVBAoTIEFDQ0VNIFNFUlZJQ0lPUyBFTVBSRVNBUklBTEVTIFNDMSUwIwYDVQQtExxBQUEwMTAxMDFBQUEgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxETAPBgNVBAsTCFVuaWRhZCAxMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2TTQSPONBOVxpXv9wLYo8jezBrb34i/tLx8jGdtyy27BcesOav2c1NS/Gdv10u9SkWtwdy34uRAVe7H0a3VMRLHAkvp2qMCHaZc4T8k47Jtb9wrOEh/XFS8LgT4y5OQYo6civfXXdlvxWU/gdM/e6I2lg6FGorP8H4GPAJ/qCNwIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQUFAAOCAQEATxMecTpMbdhSHo6KVUg4QVF4Op2IBhiMaOrtrXBdJgzGotUFcJgdBCMjtTZXSlq1S4DG1jr8p4NzQlzxsdTxaB8nSKJ4KEMgIT7E62xRUj15jI49qFz7f2uMttZLNThipunsN/NF1XtvESMTDwQFvas/Ugig6qwEfSZc0MDxMpKLEkEePmQwtZD+zXFSMVa6hmOu4M+FzGiRXbj4YJXn9Myjd8xbL/c+9UIcrYoZskxDvMxc6/6M3rNNDY3OFhBK+V/sPMzWWGt8S1yjmtPfXgFs1t65AZ2hcTwTAuHrKwDatJ1ZPfa482ZBROAAX1waz7WwXp0gso7sDCm2/yUVww==',
 'Complemento': {'TimbreFiscalDigital': {'FechaTimbrado': datetime.datetime(2015, 3, 5, 10, 33, 52),
                                         'NoCertificadoSAT': '20001000000100005761',
                                         'SelloCFD': 'KYqT5HxO25ixW1pNcxTLaZw662cbHs1CIcsMleegRbamCkY3Ce8jfjjuPsSty369rdWc8tb0RnheYoBsNtanme2ahNX3HHwVr0KMh85+pBNIbUtQqikizZf8/9RBwSGkZKwLdJ6hvVcmby53AN5WDKS6y69bg6HCfV5gV2tixkk=',
                                         'SelloSAT': 'FtRoK4ZoBUaH0CPtku4fu5F3FQCevfzDmX+/ZVqzg8pjzf9GmEJgTY9H7BE0g5B4XV5moz30P9OaCVr9keB4lhdxW56JcObXCuOgU67HENVWZlxjRhX5RkLe+RQ4n5OHcbfyUm3ITtAtIZX+JJR0uvPc4jDuKioYRZjJoR4OuVk=',
                                         'UUID': '443a4d3e-86e9-4b08-b51e-880d3472c620',
                                         'Version': '1.0'}},
 'Conceptos': [{'Cantidad': Decimal('1'),
                'ComplementoConcepto': {'instEducativas': {'AutRVOE': 'PEFHS821923KSDJ823',
                                                           'CURP': 'AAAA010101HNLRNL09',
                                                           'NivelEducativo': 'Secundaria',
                                                           'NombreAlumno': 'Jaime '
                                                                           'García '
                                                                           'Sanchez',
                                                           'RfcPago': 'BBB010101AAA',
                                                           'Version': '1.0'}},
                'Descripcion': 'Colegiatura 2015-2016',
                'Importe': Decimal('35000.00'),
                'Unidad': 'LTE',
                'ValorUnitario': Decimal('35000.00')}],
 'Descuento': Decimal('0.00'),
 'Emisor': {'DomicilioFiscal': {'Calle': 'Encinos',
                                'CodigoPostal': '64000',
                                'Colonia': 'Fracc. San Pedro',
                                'Estado': 'Nuevo León',
                                'Municipio': 'Monterrey',
                                'NoExterior': '1452',
                                'Pais': 'México'},
            'Nombre': 'Empresa de Pruebas SA',
            'RegimenFiscal': ['Regimen General de Ley Personas Morales de '
                              'Prueba'],
            'Rfc': 'AAA010101AAA'},
 'Fecha': datetime.datetime(2015, 3, 5, 10, 33, 52),
 'Folio': '38',
 'FormaDePago': 'PAGO EN UNA SOLA EXHIBICION',
 'Impuestos': {'Retenciones': [{'Importe': Decimal('0.00'), 'Impuesto': 'ISR'},
                               {'Importe': Decimal('0.00'), 'Impuesto': 'IVA'}],
               'TotalImpuestosRetenidos': Decimal('0.00'),
               'TotalImpuestosTrasladados': Decimal('5600.00'),
               'Traslados': [{'Importe': Decimal('5600.00'),
                              'Impuesto': 'IVA',
                              'Tasa': Decimal('16.00')}]},
 'LugarExpedicion': 'Monterrey, Nuevo León',
 'MetodoDePago': 'No Identificado',
 'Moneda': 'Pesos',
 'NoCertificado': '20001000000100005867',
 'NumCtaPago': 'No Identificado',
 'Receptor': {'Domicilio': {'Calle': 'Av. Principal',
                            'CodigoPostal': '99170',
                            'Colonia': 'Ejido La Siembra',
                            'Estado': 'Zacatecas',
                            'Localidad': 'Ejido La Siembra',
                            'Municipio': 'Zacatecas',
                            'NoExterior': '102',
                            'Pais': 'México'},
              'Nombre': 'Exportadora de Ganado HOLSTEIN S.A.',
              'Rfc': 'E&Ñ831019M53'},
 'Sello': 'KYqT5HxO25ixW1pNcxTLaZw662cbHs1CIcsMleegRbamCkY3Ce8jfjjuPsSty369rdWc8tb0RnheYoBsNtanme2ahNX3HHwVr0KMh85+pBNIbUtQqikizZf8/9RBwSGkZKwLdJ6hvVcmby53AN5WDKS6y69bg6HCfV5gV2tixkk=',
 'Serie': 'C',
 'SubTotal': Decimal('35000.00'),
 'TipoDeComprobante': 'ingreso',
 'Total': Decimal('40600.00'),
 'Version': '3.2'}