{'Anio': 2023,
 'Cuenta': [{'DesCta': 'MiBanco',
             'DetalleAux': [{'Concepto': 'Total',
                             'Debe': Decimal('12911.94'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0001'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('2420.00'),
                             'NumUnIdenPol': '2023-12-C-0002'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('400.00'),
                             'NumUnIdenPol': '2023-12-C-0003'}],
             'NumCta': '1102.1.1',
             'SaldoFin': Decimal('10091.94'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Clientes Nacionales',
             'DetalleAux': [{'Concepto': 'Total',
                             'Debe': Decimal('12911.94'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-I-0001'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('12911.94'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '1103.1',
             'SaldoFin': Decimal('0.00'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Otros impuestos a favor',
             'DetalleAux': [{'Concepto': 'ISR Retenido',
                             'Debe': Decimal('1354.40'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-I-0001'},
                            {'Concepto': 'IVA Retenido',
                             'Debe': Decimal('1444.70'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-I-0001'},
                            {'Concepto': 'ISR Retenido',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('1354.40'),
                             'NumUnIdenPol': '2023-12-C-0001'},
                            {'Concepto': 'IVA Retenido',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('1444.70'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '1104.2',
             'SaldoFin': Decimal('0.00'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'IVA Trasladado Cobrado',
             'DetalleAux': [{'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('2167.04'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '2153.1',
             'SaldoFin': Decimal('2167.04'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'IVA Trasladado No Cobrado',
             'DetalleAux': [{'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('2167.04'),
                             'NumUnIdenPol': '2023-12-I-0001'}],
             'NumCta': '2152.1',
             'SaldoFin': Decimal('2167.04'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Impuestos Retenidos de ISR',
             'DetalleAux': [{'Concepto': 'ISR Retenido',
                             'Debe': Decimal('1354.40'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '2151.1',
             'SaldoFin': Decimal('-1354.40'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Impuestos Retenidos de IVA',
             'DetalleAux': [{'Concepto': 'IVA Retenido',
                             'Debe': Decimal('1444.70'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '2151.2',
             'SaldoFin': Decimal('-1444.70'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Ingresos',
             'DetalleAux': [{'Concepto': 'Subtotal',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('13544.00'),
                             'NumUnIdenPol': '2023-12-I-0001'},
                            {'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('2167.04'),
                             'Fecha': datetime.date(2023, 12, 1),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0001'}],
             'NumCta': '4100.1',
             'SaldoFin': Decimal('11376.96'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Otros Gastos de Administración',
             'DetalleAux': [{'Concepto': 'Subtotal',
                             'Debe': Decimal('2086.21'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-E-0001'},
                            {'Concepto': 'Subtotal',
                             'Debe': Decimal('344.83'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-E-0002'}],
             'NumCta': '5202.1',
             'SaldoFin': Decimal('2431.04'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'IVA Acreditable Pagado',
             'DetalleAux': [{'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('333.79'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0002'},
                            {'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('55.17'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0003'}],
             'NumCta': '1152.1',
             'SaldoFin': Decimal('388.96'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'IVA Pendiente de Pago',
             'DetalleAux': [{'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('333.79'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-E-0001'},
                            {'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('55.17'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-E-0002'},
                            {'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('333.79'),
                             'NumUnIdenPol': '2023-12-C-0002'},
                            {'Concepto': 'IVA Trasladado',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('55.17'),
                             'NumUnIdenPol': '2023-12-C-0003'}],
             'NumCta': '1153.1',
             'SaldoFin': Decimal('0.00'),
             'SaldoIni': Decimal('0')},
            {'DesCta': 'Proveedores nacionales',
             'DetalleAux': [{'Concepto': 'Total',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('2420.00'),
                             'NumUnIdenPol': '2023-12-E-0001'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('0'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('400.00'),
                             'NumUnIdenPol': '2023-12-E-0002'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('2420.00'),
                             'Fecha': datetime.date(2023, 12, 27),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0002'},
                            {'Concepto': 'Total',
                             'Debe': Decimal('400.00'),
                             'Fecha': datetime.date(2023, 12, 22),
                             'Haber': Decimal('0'),
                             'NumUnIdenPol': '2023-12-C-0003'}],
             'NumCta': '2101.1',
             'SaldoFin': Decimal('0.00'),
             'SaldoIni': Decimal('0')}],
 'Mes': '12',
 'RFC': 'CACX7605101P8',
 'TipoSolicitud': 'AF',
 'Version': '1.3'}