{'Anio': 2023,
 'Ctas': [{'CodAgrup': Code('102', 'Bancos'),
           'Desc': 'BANCOS',
           'Natur': 'D',
           'Nivel': 1,
           'NumCta': '1102'},
          {'CodAgrup': Code('102.01', 'Bancos nacionales'),
           'Desc': 'NACIONALES',
           'Natur': 'D',
           'Nivel': 2,
           'NumCta': '1102.1',
           'SubCtaDe': '1102'},
          {'CodAgrup': Code('102.01', 'Bancos nacionales'),
           'Desc': 'HSBC',
           'Natur': 'D',
           'Nivel': 3,
           'NumCta': '1102.1.1',
           'SubCtaDe': '1102.1'},
          {'CodAgrup': Code('102.02', 'Bancos extranjeros'),
           'Desc': 'EXTRANJEROS',
           'Natur': 'D',
           'Nivel': 2,
           'NumCta': '1102.2',
           'SubCtaDe': '1102'},
          {'CodAgrup': Code('105', 'Clientes'),
           'Desc': 'CLIENTES',
           'Natur': 'D',
           'Nivel': 1,
           'NumCta': '1103'},
          {'CodAgrup': Code('105.01', 'Clientes nacionales'),
           'Desc': 'CLIENTES NACIONALES',
           'Natur': 'D',
           'Nivel': 2,
           'NumCta': '1103.1',
           'SubCtaDe': '1103'},
          {'CodAgrup': Code('105.02', 'Clientes extranjeros'),
           'Desc': 'CLIENTES EXTRANJEROS',
           'Natur': 'D',
           'Nivel': 2,
           'NumCta': '1103.2',
           'SubCtaDe': '1103'},
          {'CodAgrup': Code('113', 'Impuestos a favor'),
           'Desc': 'IMPUESTOS A FAVOR',
           'Natur': 'D',
           'Nivel': 1,
           'NumCta': '1104'},
          {'CodAgrup': Code('113.01', 'IVA a favor'),
           'Desc': 'IVA A FAVOR',
           'Natur': 'D',
           'Nivel': 2,
           'NumCta': '1104.1',
           'SubCtaDe': '1104'},
          {'CodAgrup': Code('208', 'Impuestos trasladados cobrados'),
           'Desc': 'IMPUESTOS TRASLADAOS COBRADOS',
           'Natur': 'A',
           'Nivel': 1,
           'NumCta': '2153'},
          {'CodAgrup': Code('208.01', 'IVA trasladado cobrado'),
           'Desc': 'IVA TRASLADADO COBRADO',
           'Natur': 'A',
           'Nivel': 2,
           'NumCta': '2153.1',
           'SubCtaDe': '2153'},
          {'CodAgrup': Code('209', 'Impuestos trasladados no cobrados'),
           'Desc': 'IMPUESTOS TRASLADADOS NO COBRADOS',
           'Natur': 'A',
           'Nivel': 1,
           'NumCta': '2152'},
          {'CodAgrup': Code('209.01', 'IVA trasladado no cobrado'),
           'Desc': 'IVA TRASLADADO NO COBRADO',
           'Natur': 'A',
           'Nivel': 2,
           'NumCta': '2152.1',
           'SubCtaDe': '2152'},
          {'CodAgrup': Code('216', 'Impuestos retenidos'),
           'Desc': 'IMPUESTOS RETENIDOS',
           'Natur': 'A',
           'Nivel': 1,
           'NumCta': '2151'},
          {'CodAgrup': Code('216.03', 'Impuestos retenidos de ISR por arrendamiento'),
           'Desc': 'IMPUESTOS RETENIDOS DE ISR',
           'Natur': 'A',
           'Nivel': 2,
           'NumCta': '2151.1',
           'SubCtaDe': '2151'},
          {'CodAgrup': Code('216.03', 'Impuestos retenidos de ISR por arrendamiento'),
           'Desc': 'IMPUESTOS RETENIDOS DE ISR ACREDITABLE',
           'Natur': 'A',
           'Nivel': 3,
           'NumCta': '2151.1.1',
           'SubCtaDe': '2151.1'},
          {'CodAgrup': Code('216.03', 'Impuestos retenidos de ISR por arrendamiento'),
           'Desc': 'IMPUESTOS RETENIDOS DE ISR PENDIENTE',
           'Natur': 'A',
           'Nivel': 3,
           'NumCta': '2151.1.2',
           'SubCtaDe': '2151.1'},
          {'CodAgrup': Code('401', 'Ingresos'),
           'Desc': 'INGRESOS',
           'Natur': 'A',
           'Nivel': 1,
           'NumCta': '4100'},
          {'CodAgrup': Code('401.22', 'Ingresos por arrendamiento'),
           'Desc': 'INGRESOS POR VENTAS',
           'Natur': 'A',
           'Nivel': 2,
           'NumCta': '4100.1',
           'SubCtaDe': '4100'}],
 'Mes': '12',
 'RFC': 'CACX7605101P8',
 'Version': '1.3'}