{'Anio': 2023,
 'Mes': '12',
 'Poliza': [{'Concepto': 'Ingreso - Venta',
             'Fecha': datetime.date(2023, 12, 1),
             'NumUnIdenPol': '2023-12-I-0001',
             'Transaccion': [{'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'Subtotal',
                              'Debe': Decimal('0'),
                              'DesCta': 'INGRESOS',
                              'Haber': Decimal('13544.00'),
                              'NumCta': '4100.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'IVA Trasladado',
                              'Debe': Decimal('0'),
                              'DesCta': 'IVA TRASLADADO NO COBRADO',
                              'Haber': Decimal('2167.04'),
                              'NumCta': '2152.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'ISR Retenido',
                              'Debe': Decimal('1354.40'),
                              'DesCta': 'IMPUESTOS RETENIDOS DE ISR PENDIENTE',
                              'Haber': Decimal('0'),
                              'NumCta': '2151.1.2'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'IVA Retenido',
                              'Debe': Decimal('1444.70'),
                              'DesCta': 'IVA A FAVOR',
                              'Haber': Decimal('0'),
                              'NumCta': '1104.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'Total',
                              'Debe': Decimal('14911.94'),
                              'DesCta': 'CLIENTES NACIONALES',
                              'Haber': Decimal('0'),
                              'NumCta': '1103.1'}]},
            {'Concepto': 'Ingreso - Venta',
             'Fecha': datetime.date(2023, 12, 1),
             'NumUnIdenPol': '2023-12-I-0001',
             'Transaccion': [{'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'Subtotal',
                              'Debe': Decimal('0'),
                              'DesCta': 'INGRESOS',
                              'Haber': Decimal('13544.00'),
                              'NumCta': '4100.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'IVA Trasladado',
                              'Debe': Decimal('0'),
                              'DesCta': 'IVA TRASLADADO NO COBRADO',
                              'Haber': Decimal('2167.04'),
                              'NumCta': '2152.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'ISR Retenido',
                              'Debe': Decimal('1354.40'),
                              'DesCta': 'IMPUESTOS RETENIDOS DE ISR PENDIENTE',
                              'Haber': Decimal('0'),
                              'NumCta': '2151.1.2'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'IVA Retenido',
                              'Debe': Decimal('1444.70'),
                              'DesCta': 'IVA A FAVOR',
                              'Haber': Decimal('0'),
                              'NumCta': '1104.1'},
                             {'CompNal': [{'MontoTotal': Decimal('14911.94'),
                                           'RFC': 'EWE1709045U0',
                                           'UUID_CFDI': 'a262228b-b105-4b90-9b02-ffe0e2d881cc'}],
                              'Concepto': 'Total',
                              'Debe': Decimal('14911.94'),
                              'DesCta': 'CLIENTES NACIONALES',
                              'Haber': Decimal('0'),
                              'NumCta': '1103.1'}]}],
 'RFC': 'CACX7605101P8',
 'TipoSolicitud': 'AF',
 'Version': '1.3'}